- API.md
- README.md
- src/net/index.js
- src/net/smooth/index.js
- src/net/smooth/mp4.js
- src/net/smooth/parser.js
- src/net/smooth/tt-sami.js
- src/net/smooth/tt-ttml.js
- test/index.js
- test/net/smooth/parser.test.js
- test/net/smooth/tt-sami.test.js
- test/net/smooth/tt-ttml.test.js
> Smooth Streaming

- API.md
- src/core/compat.js
- src/core/eme.js
- src/core/stream.js
Support for EME license persistency.
> eme: license persistency

- src/core/buffer.js
Depuis Chrome 46, l'algo de GC media ayant changé pour se rapprocher de la spec MSE, l'applicatif doit réagir à des erreurs du type QuotaExceededError: The SourceBuffer is full, and cannot free space to append additional buffers.
Voici un algo rudimentaire de GC pour réagir proprement à ces erreurs.
cf: https://codereview.chromium.org/1013923002/ et https://w3c.github.io/media-source/#sourcebuffer-coded-frame-eviction
> buffer: add garbage collector

- .gitignore
- README.md
A quick minimal example of player usage.
> Add an example in doc.

- doc/api/loadVideo_options.md
- src/core/stream/initial_time.js
Needed by some targets. To test and review.
> api: add percentage to startAt

- src/compat/eme/MediaKeys.ts
The commit says it all.
This allows to use building tools normally again
> misc: find better workaround for typescript issue #20104

- src/core/compat.js
- src/core/eme.js
- src/core/player.js
- src/index.js
> eme: add closeSessionsOnStop to keySytem on old v2

- src/core/eme/index.ts
- src/core/eme/sessions_set/persisted.ts
- src/net/dash/manifest/helpers.ts
- src/net/dash/texttracks.ts
- src/net/smooth/manifest/index.ts
- src/net/smooth/mp4.ts
- src/parsers/texttracks/sami/html.ts
- src/parsers/texttracks/sami/native.ts
- src/utils/__tests__/array-includes.test.ts
- src/utils/__tests__/assert.test.ts
- src/utils/__tests__/starts-with.test.ts
- src/utils/array-includes.ts
- src/utils/assert.ts
- src/utils/bytes.ts
- src/utils/starts-with.ts
- src/utils/weak_map_memory.ts
Fixing some broken windows from the Pre-TypeScript era...
> misc/utils: cleaner implementation for assert functions

- src/core/api/index.ts
- src/core/eme/attach_media_keys.ts
- src/core/eme/dispose_media_keys.ts
- src/core/eme/find_key_system.ts
- src/core/eme/get_media_keys.ts
- src/core/eme/index.ts
- src/core/eme/media_keys_infos_store.ts
Tests to remove any previous global variable that could interfere with the implementation of multiple DRMized media elements at the same time
> eme: Multiple DRMized Media Element on Multiple instances

- src/core/buffer/representation_buffer.ts
- tests/integration/scenarios/dash_live.js
- tests/integration/scenarios/dash_static.js
Not so easy to implement, The previous one caused problems with SegmentBase.
Scheduled for a next release
> buffer: remove initialization parallelization for now

- src/parsers/manifest/dash/indexes/base.ts
- src/parsers/manifest/dash/indexes/helpers.ts
- src/parsers/manifest/dash/indexes/list.ts
- src/parsers/manifest/dash/indexes/template.ts
- src/parsers/manifest/dash/indexes/timeline.ts
- src/parsers/manifest/smooth/representationIndex.ts
SegmentTemplate number should not take into account presentationTimeOffset +
index.presentationTimeOffset is different from period start time.
> Fix: correct usage of presentation time offset

- src/compat/index.ts
- src/core/stream/video_events.ts
If auto-play seems to be restricted, warn user.
> stream: warn when auto-play is unavailable

- src/core/abr/representation_chooser.ts
- src/core/buffer/index.ts
Various fixes / improvments on ABR, in particular in sudden bandwitch fall handling.
> Some abr improvments

- doc/api/index.md
- src/core/api/index.ts
api: skip state change until content has played for the first time or ended
> Skip state change

- src/parsers/containers/isobmff/index.ts
Re-write isobmff parsers in a more readable way.
It wasn't touched since we were on the project and the syntax didn't look really like it belonged in the same code than the rest.
> parsers/isobmff: simplify isobmff parsers

- src/core/api/clock.ts
First step to allow multiple future improvements. Such as adding the possibility to ask an "instant tick" (needed for example by the buffer-based ABR or for adding playback infos to fatal errors).
I also removed the `isMediaInfoState` function and replaced it by more restrictive typings.
> clock: re-write clock as a composed observable

- src/core/buffers/adaptation/adaptation_buffer.ts
- src/core/buffers/buffer_orchestrator.ts
- src/core/buffers/period/period_buffer.ts
- src/core/buffers/representation/append_data.ts
- src/core/buffers/representation/representation_buffer.ts
- src/core/init/initialize_media_source.ts
- src/core/init/load_on_media_source.ts
We should try to limit the buffer goal when a QuotaExceededError happens.
The buffer goal ratio reduce the wanted buffer ahead to determine a new buffer goal.
If the buffer goal ratio is too low, throw an error.
> Buffer goal ratio

- src/compat/event_listeners.ts
> Removed misinterpreted debounceTime operator

- src/parsers/manifest/smooth/representation_index.ts
Playing Smooth contents with the `aggressiveMode` `transportOptions` enabled could lead to a lot of 412.
The new logic now make sure that at least the beginning of the segment had time to be generated on the server's side before doing the request.
The only difference with the regular mode is that:
- in regular mode we wait until we're sure the segment had time to be finished on the server's side and then we download it
- in aggressive mode, we wait only until it begins to be generated
We can even imagine a DASH version of the aggressive mode now, only doing things for SegmentTemplate without SegmentTimelines akin to what we do on that matter with low-latency contents.
> Aggressive mode now also checks if the segment technically began

- src/parsers/manifest/dash/__tests__/get_periods_time_infos.test.ts
- src/parsers/manifest/dash/get_periods_time_infos.ts
- src/parsers/manifest/dash/parse_periods.ts
As indexes now need to get period end, and as we create indexes when parsing the period, we should anticipate period end calculation before indexes creation.
> Get period end from next period before parsing period content

- demo/full/scripts/components/BufferContentGraph.jsx
- demo/full/scripts/components/FocusedInput.jsx
- demo/full/scripts/components/ImageTip.jsx
- demo/full/scripts/components/ToolTip.jsx
- demo/full/scripts/controllers/ContentList.jsx
- demo/full/scripts/controllers/ProgressBar.jsx
- demo/full/scripts/controllers/charts/BufferContent.jsx
- demo/full/scripts/controllers/charts/index.jsx
- demo/full/scripts/lib/capitalizeFirstLetter.js
- demo/full/scripts/lib/shuffleArray.js
- demo/full/scripts/modules/player/events.js
- demo/full/scripts/modules/player/index.js
- demo/full/styles/style.css
- src/core/api/public_api.ts
- src/core/init/events_generators.ts
- src/core/init/initialize_directfile.ts
- src/core/init/load_on_media_source.ts
- src/core/init/types.ts
:open_hands: 
This PR also includes components rewritten with hooks when it became much more readable and short to do so
> demo: add buffer content graphs in the demo page

- demo/full/assets/play.svg
- demo/full/scripts/controllers/Player.jsx
- demo/full/scripts/modules/player/events.js
- demo/full/scripts/modules/player/index.js
- demo/full/styles/style.css
> demo: add a play button on the video player when autoplay is blocked due to browser policies

- demo/full/scripts/contents.js
Change *Tears of Steal* in *Tears of Steel*
> Fix typo in demo content name

- src/core/api/media_element_track_choice_manager.ts
There was an issue with directfile track management, where we re-setted the preferred audio, video and text track every time the track list changed.
We know about those preferences through the track preferences APIs:
- the constructor's `preferredAudioTracks`, `preferredTextTracks` and `preferredVideoTracks` option
- the corresponding setter methods: `setPreferredAudioTracks`, `setPreferredTextTracks` and `setPreferredVideoTracks`
This is fine in most cases because the preferred tracks ... are usually the preferred tracks.
--
But there is one case where this is not what we want: when we have chosen a specific track (or when we have chosen to have no track at at all) through the `setAudioTrack`, `setVideoTrack`, `setTextTrack`, `disableVideoTrack` and `disableTextTrack` methods.
Here, even …
> Keep manually set audio, video or text track even when the tracklist changes

- README.md
This is a README.md update, so that:
1. after a "popular" approval, the title part is now centered
2. quicklinks to the documentation (and other important links) were added after I was given the input that it was hard to reach from it
3. the "why a new player?" part was re-written so we can talk more about the player (the origin of the project, key features) and less about RxJS. If its content sounds to much like marketing-speak, please signal it :P
> update Readme.md with quick links and new "why a new player?" text

- src/core/buffers/representation/get_needed_segments.ts
Fixes #772 
There was an issue in the previous `filterGarbageCollectedSegments` code where we would consider the end of a segment to be garbage collected even if a segment can be found exactly after it (its start equal our first segment's end).
This is not wanted behavior and was the source of an issue in firefox with our multi-period DASH test stream.
Here, we might think that a given audio segment at the end of the first period is garbage collected, in which case we would just request it in a loop.
I profited from that fix by rewriting `filterGarbageCollectedSegments` as it was hard to read for a logic that seems straightforward.
I only factorized the two complex conditions into two functions: `isStartGarbageCollected` and `isEndGarbageCollected`.
> buffers: simplify code readability for the `filterGarbageCollectedSegments` and fix end check issue

- src/core/buffers/representation/get_needed_segments.ts
I worked a lot on the code found in `get_needed_segments.ts` recently to debug some problems with some stream with ad-insertion.
As I added breakpoints and console.logs, I realized that that code is not the most easy to follow in the player:
1. what is `currentSegments` vs `possibleSegments` vs `completeSegments` vs `consideredSegments`? (Yeah they all designate something different here)
2. what does `getCorrespondingBufferedSegments` do? If you though it just return every segment buffered for a given range, you're wrong (well, almost right). It actually return all _decipherable_ buffered segment for a given range.
So I decided to change some things:
1. Now there is only `bufferedSegments` which designates the current buffered segments considered. That variable is muted in place as we …
> buffers: rename variables and functions to make get_needed_segments.ts more readable

- src/core/api/clock.ts
- src/core/source_buffers/segment_inventory.ts
While debugging on more "embedded" platforms, I found out that the majority of the time spent while debugging platform issues was taken by just finding out what segments were buffered.
This can be make simpler by just including that information in our debug logs.
This commit adds two main logs:
- at each clock tick, we display a visual representation of what has been buffered on the current media element, relatively to the
current position.
- at each SegmentInventory synchronization, we display information about which segments are currently available in the corresponding SourceBuffer.
This is relatively difficult to represent it visually, as such, I chose a system were letters are used to represent a given Representation followed a legend linking both.
Because both of those logs add …
> misc: improve logging situation in clock and SegmentInventory

- demo/full/scripts/components/BufferContentGraph.jsx
- demo/full/scripts/controllers/Player.jsx
- demo/full/scripts/modules/player/events.js
- src/core/api/track_choice_manager.ts
- src/core/eme/types.ts
- src/core/stream/period/create_empty_adaptation_stream.ts
- src/experimental/tools/createMetaplaylist/get_duration_from_manifest.ts
- src/manifest/adaptation.ts
- src/parsers/images/bif.ts
- src/parsers/manifest/dash/indexes/__tests__/tokens.test.ts
- src/parsers/manifest/dash/indexes/get_segments_from_timeline.ts
- src/parsers/manifest/dash/indexes/template.ts
- src/parsers/manifest/dash/indexes/tokens.ts
- tests/integration/scenarios/dash_live_utc_timings.js
- tests/integration/scenarios/dash_static.js
This commit contains minor code updates after running the sonarcloud tool (which basically is a static analysys tool which reviews "code smells", "Security Hotspots" and "Bugs" in our code) as I usually try to do before releases.
All modifications performed here are to fix what sonarcloud considers as "code smells" for [what I consider] good reasons.
Most of them were already there last release, as no "code smell" fix here led to a real issue.
Amongst issues fixed here:
- Multiple variables of the same name in the same scope
- I stopped defining some closures in imbricated loops.
I used curried functions instead to partially apply initial arguments and ultimately remove one level of function definition.
> misc: Minor code updates after sonarcloud checks

- doc/api/index.md
> fix typo for setVideoTrack subchapter in doc

- doc/infos/dash/presentationTimeOffset.md
> Fix typo presentationMediaOffset

- src/core/segment_buffers/implementations/audio_video/audio_video_segment_buffer.ts
This commit fix a not-yet released regression where an initialization segment would not be pushed again - because it had the same content than the last one pushed in that SourceBuffer - despite the fact that we called the `changeType` API in the meantime.
This is a highly specific issue that only showed in tests for now.
To reproduce it, we need to have multiple Representations with the exact same initialization segment data but with different codecs or profiles in the Manifest. We also need to be on a browser that support the `sourceBuffer.changeType` API.
In that very very rare situation, the RxPlayer would call the `changeType` API when pushing segment data from a Representation with a different codec (or profile) than the previous one. From my tests on Firefox and Chrome, it seems …
> segment_buffers: Push init data again when changeType is called

- src/core/api/clock.ts
The previous type definition for `IStalledStatus`, which is used in the clock to anounce that current playback is stalled and why, included the `null` value, for when we had no active stall.
Including a `null` value to our types is somewhat unusual in our code, we generally prefer defining an interface and then defining a sum type grouping both (`Interface | null`) when needed.
Also, this commit does a second minor thing. The `getRange` function was called two times in the clock: once implicitely in `getLeftSizeOfRange` and then explicitely.
I re-wrote that code so we only need to calculate that value once per clock tick.
> clock: re-define `IStalledStatus` interface so it does not include `null`

- src/core/segment_buffers/segment_inventory.ts
This commit fixes a bug where the RxPlayer would request the same segment in a loop if it really ended a lot after what we thought it ended at. This usually happens only for the last segment in the content, for various reasons and was easily reproducible by playing close to the end of our multi-Period content in the demo.
As usual with requests happening in a loop, this is due to the RxPlayer believing that segments that have been pushed have since been garbage collected.
The source of the issue was in the (too-)complex `SegmentInventory` code.
Here, we link to each segments multiple properties including what is of interest here is:
- `end`: what the end of the segment should be once pushed (based on Manifest information, ISOBMFF metadata, or even on what has really been buffered after …
> avoid re-downloading a segment when it ends a lot before it should

- doc/api/index.md
- scripts/doc-generator/styles/style.css
This PR regroups several documentation updates:
1. For every method in the API, I added a "syntax" part which shows quickly and easily the different forms the method can have.
The main motivation was to be more explicit on optional parameters, like for `reload` (which can have no option at all), `setPreferredAudioTracks` (which can take a boolean as second argument, or nothing) or `removeEventListener` (whose behavior change based on if a second argument is present or not).
The syntax of that syntax part has been inspired from MDN, which has a similar introduction for methods. 
2. A visual block has been added regrouping syntax, arguments and the return value for every method.
The form of `arguments`' value has been unified, as it was weirdly different for some methods
3. I added some …
> Documentation improvements for v3.23

- src/core/abr/network_analyzer.ts
The RxPlayer has several mechanisms to adapt the current chosen video and audio quality to the network's bandwidth.
Most of them rely on bandwidth calculations based on the time each previous segment requests made, but we noticed that this is sometimes not enough.
Sometimes the fall of bandwidth is so sudden and acute that we cannot afford waiting for the current segment requests to finish (prerequisite to the regular behavior).
For those cases, the RxPlayer has a second logic specifically when the buffer is "starving" - which means that is has no or few data left in its buffer.
When in "starvation mode", the RxPlayer will pay attention to the progress made by current requests, and ask to cancel those to switch in quality if that progression seems to slow.
---
The "starvation mode" …
> Fixes on handling sudden fall in bandwidth

- src/core/eme/eme_manager.ts
This PR is based on the `singleLicensePer` one (#904).
Here, only the last commit is of interest!
Before this PR, persistent MediaKeySessions were added to the `PersistentSessionsStore` (for later retrieval) as soon as possible:
when their `sessionId` property was known (meaning as soon as the `generateRequest` API answered).
This worked pretty well, but we found a persistence-related issue that could profit from taking another strategy:
After loading a persistent MediaKeySessions (that has previously been added to the `PersistentSessionsStore`), the RxPlayer immediately checks the status of its keys through the `keyStatuses` property.
However, on some platforms, the `keyStatuses` property is not directly populated once the `load` call is done, but only after a
difficult-to-predict delay …
>  eme: only persist MediaKeySessions once its keys are known 

- package-lock.json
- package.json
- src/core/eme/__tests__/__global__/get_license.test.ts
- src/core/eme/__tests__/__global__/init_data.test.ts
- src/core/eme/__tests__/__global__/media_key_system_access.test.ts
- src/core/eme/__tests__/__global__/media_keys.test.ts
- src/core/eme/__tests__/__global__/server_certificate.test.ts
- src/core/stream/orchestrator/stream_orchestrator.ts
- src/core/stream/period/period_stream.ts
- src/experimental/tools/createMetaplaylist/index.ts
- src/experimental/tools/mediaCapabilitiesProber/probers/DRMInfos.ts
- src/experimental/tools/mediaCapabilitiesProber/probers/HDCPPolicy.ts
- src/utils/__tests__/concat_map_latest.test.ts
This is an update of RxJS from v6.x.x to its v7.0.0.
It _seems_ to come with better performance and a smaller size.
The main differences are type and Observable to Promise conversions, as can be seen here.
> Update RxJS to v7.0.0

- demo/full/scripts/components/Button.jsx
- demo/full/scripts/components/CheckBox.jsx
- demo/full/scripts/components/Options/AudioAdaptiveSettings.jsx
- demo/full/scripts/components/Options/BufferOptions.jsx
- demo/full/scripts/components/Options/NetworkConfig.jsx
- demo/full/scripts/components/Options/Option.jsx
- demo/full/scripts/components/Options/Playback.jsx
- demo/full/scripts/components/Options/TrackSwitch.jsx
- demo/full/scripts/components/Options/VideoAdaptiveSettings.jsx
- demo/full/scripts/components/Select.jsx
- demo/full/scripts/controllers/ContentList.jsx
- demo/full/scripts/controllers/Player.jsx
- demo/full/scripts/controllers/Settings.jsx
- demo/full/scripts/controllers/charts/index.jsx
- demo/full/scripts/controllers/knobs/AudioBitrate.jsx
- demo/full/scripts/controllers/knobs/AudioTrack.jsx
- demo/full/scripts/controllers/knobs/SpeedKnob.jsx
- demo/full/scripts/controllers/knobs/Subtitles.jsx
- demo/full/scripts/controllers/knobs/VideoBitrate.jsx
- demo/full/scripts/controllers/knobs/VideoTrack.jsx
- demo/full/scripts/lib/defaultOptionsValues.js
- demo/full/scripts/lib/getCheckboxValue.js
- demo/full/scripts/lib/isEqual.js
- demo/full/scripts/lib/withModulesState.jsx
- demo/full/scripts/modules/player/index.js
- demo/full/styles/style.css
We decided to give more love to the demo by exposing a bunch of options that the player can set in order to influence the playback.
Here is a screenshot that gives a hint of what it will look like:
> Expose player options in the demo

- src/core/abr/representation_estimator.ts
- src/core/fetchers/segment/segment_fetcher.ts
One of the main upcoming improvement of the v3.26.2 is [the addition of the `GuessBasedChooser`](https://github.com/canalplus/rx-player/pull/1025), an adaptive algorithm more adapted to low-latency DASH contents than what we have now.
One of its main input is the "Representation score", a RxPlayer concept which indicates if a quality (or Representation) seems to be maintainable or not, that is, if its media segments can be loaded faster (or at least at the same pace) than those segments' duration.
_When the score is on the "maintainable" side, the `GuessBasedChooser` might decide to choose a better Representation, when the score is on the "not maintanable" side, the `GuessBasedChooser` will probably choose to rollback to the previous quality and wait some exponentially-growing delay …
> abr: find a way to calculate the RepresentationScore when a segment duration is not known in advance

- src/parsers/manifest/dash/common/indexes/timeline/timeline_representation_index.ts
Some DASH MPD rely on `SegmentTimeline` elements to describe which segments are available.
A `SegmentTimeline` contains `<S>` XML elements, indicating through their attributes time information (start time and duration) for either a single segment or a group of consecutive segments.
Usually, at least the first of those `<S>` elements indicates a start time, as a `t` attribute (this is rarely seen for the consecutive `<S>` however, as here the starting time can simply be calculated by summing the initial time and the other segment's duration).
However there could be cases where even the first `<S>` element does not indicate a time. Here, it is to the RxPlayer to infer the time associated to the first segment. This is this process which I tried to fix in this PR.
The previous operation …
> DASH: don't include presentationTimeOffset for the default initial time of a`<S>`

- src/core/decrypt/content_decryptor.ts
We noticed of a regression that has been introduced in our DRM-related code last release (a risk we took considering the complete DRM overhaul occuring in it), where we could be left in an infinite rebuffering situation under very specific conditions when a license is requested in a complex `singleLicensePer` mode (`"periods"` or `"content"`).
For this bug to occur, we should be in a situation where we:
1. have already loaded the same content recently or persisted its license in a complex `singleLicensePer` setting
2. load that cached session when loading again that content, also under a complex `singleLicensePer` setting (note that we _might_ also have had the issue in a simple `singleLicensePer`, still only if the first load was in a complex one)
3. load as a first quality a content …
> Fix fallback for license missing kid in an extended `singleLicensePer` setting

- src/core/init/content_time_boundaries_observer.ts
- src/core/init/load_on_media_source.ts
This commit is a very small fix whose main side-effect should be only to avoid seeing duplicate "end-of-stream"/"resume-stream" logs - though it could have been much worse.
The issue is that in `load_on_media_source.ts`, the observable returned by the `StreamOrchestrator` was subscribed twice:
- once by the `ContentTimeBoundariesObserver`, which will listen for track changes to re-calculate the current content's duration
- another time by the whole Observable returned by the `loadContentOnMediaSource` function defined in this file, to bubble up its event.
Because those two subscriptions are not on a shared Observables, side-effects in them are provoked twice in a row each time. Depending on the type of side-effects that could be very problematic. Thankfully, it seems that the only real …
> Fix redundant endOfStream handling

- src/parsers/manifest/dash/common/parse_adaptation_sets.ts
This is a reimplementation of #1210, but which targets the future v3.30.0 version now instead of the v4.
This is because:
1, it appears that not merging video "main" Adaptation Sets make more sense in general
2. it didn't seem to break any existent use-case, at least on tested contents
3. Canal+ will need to rely on this.
We first planned to only implement it to `canal`-tagged versions on npm, but we finally thought that it make more sense to generalize this behavior.
> Next: Do not merge "main" video AdaptationSet anymore

- src/core/decrypt/session_events_listener.ts
This fixes an issue in the v3.30.0 - for now only in pre-release - and v4.0.0-beta.0.
When playing a content whose MediaKeySession(s) were already cached and which need to have Representation fallback(s) (some Representation are not decipherable), it was possible to be left in an infinite rebuffering case.
The reason is very simple and a classic issue: since the removal of RxJS in the `SessionEventListener` code, the DRM code only alerted of unusable key-ids after the `keyStatusesChange` `MediaKeySession` event was triggered. Thus it would not alert of unusable key ids if all statuses were already known from the beginning - such as in a reused cached `MediaKeySession` case.
The fix is straightforward and is similar to the logic before the removal of RxJS: as soon as the …
> DRM: check key statuses initially linked to a MediaKeySession

- src/core/stream/adaptation/adaptation_stream.ts
The `QuotaExceededError` error is sent by the `SourceBuffer`s when they cannot receive another segment due to them being full.
The previous RxPlayer error handling in that situation was to:
1. Try to remove some data from the buffer
2. retry to push the segment, if it fails again, go to 3
3. reduce the maximum amount of the pre-buffered data (if it was already reduced too much time - like 3 times -, we actually stop on a `BUFFER_FULL_ERROR` directly)
This reduced amount can be seen as the actually relied on `wantedBufferAhead` / "buffer goal" value.
4. Restart directly the `RepresentationStream`, which will load and push segments, with the new, reduced pre-buffering amount
---
Though even with that, we still saw several `BUFFER_FULL_ERROR` in the wild, which means that we went through …
> Wait 4 seconds before restarting streams after receiving a QuotaExceededError

- src/core/api/option_utils.ts
avoid using cast and use more reliable typescript check
> refactor: remplace typescript cast by runtime check
