canalplus/rx-player

webpack-demo.config.js

Without antislash, the period allow any character

Escape dot in RegExp

---

package.json

Without webpack-dev-server `make test` fails

add missing dev dependency - webpack-dev-server

---

src/core/player.js

A paused event was emitted before the ended event

fix(state): fix paused event emitted right before the ended event

---

src/parsers/texttracks/ttml/style.ts

Easy fix for when a style was set directly on a an attribute of a corresponding element (not on a style).
The issue was that the ``currentStyle`` object, which is a dictionary of every styling values to apply to our elements, contained the string ``tts:nameOfTheStyle`` - which is the attribute name in the ttml spec - instead of just ``nameOfTheStyle`` - which is what we go with in the code.
The attribute name without the ``tts:`` part was already computed, but the original name was put in the ``currentStyle`` object instead of it by mistake.

text/ttml: apply correctly a style if directly set on an attribute

---

src/core/manifest.js
src/core/stream.js
src/core/timings.js
src/manifest/manifest.js
src/net/smooth/parser.js

Feature needed by NCP.
With this implementation, non-live Smooth Streaming Manifest will begin at a specific timestamp, which is the max between:
- The first time Reference of the first video adaptation
- The first time Reference of the first audio adaptation
The Duration defined in the manifest will be added to this timestamp to define the "real" duration of the content.
I'm still hesitating between this or always push the content at a 0 timestamp with Smooth static content.
This implementation is closer to the Manifest and the ISOBMFF's tfrf and tfxd but:
- I don't think that's what NCP want
- that's not how the hasplayer handle it

Smooth vod contents with start timestamp != 0, implementation 2, start at manifest

---

src/core/buffer/create_fake_buffer.ts
src/core/buffer/representation_buffer.ts
src/core/stream/buffers_handler.ts
src/core/stream/live_events_handler.ts

The title says it all, we do not care enough for discontinuities in subtitles or images to seek past them when encountered. We do however for audio and video segments.
To simplify the exploitation of the different events emitted by the RepresentationBuffer, we add bufferType information to all of them.
This could be added by higher-layers such as the BufferHandler but it would be too redundant to do so (we would have to re-declare the types) so this can be seen as a middle-level solution.

buffer: perform discontinuity seeks only for native source buffers

---

src/parsers/texttracks/webvtt/native.ts
src/typings/browser.d.ts

Fix for _"Failed to set the 'line' property on 'VTTCue': The provided value '44' is not a valid enum value of type AutoKeyword."_
VTTCue line property must be double or AutoKeyword. This PR fixes a
crash when attempting to set line as string.
https://w3c.github.io/webvtt/#typedefdef-lineandpositionsetting

vtt: set cue line property as number

---

src/parsers/manifest/dash/indexes/template.ts

Time as miscalculated from number in Template Index, provocating:
-> Re-downloading of already bufferized segments
-> Impossible to find segment being requested in ABR.
One line fix.

parsers: fixed time computation in template index

---

src/parsers/manifest/dash/node_parsers/index.ts

When the first parsed adaptation is a main adaptation, we ignored it.

fix: consider main adaptation when it is the first parsed

---

src/parsers/texttracks/ttml/html/createElement.ts
src/parsers/texttracks/ttml/html/index.ts
src/parsers/texttracks/ttml/html/parseCue.ts
src/parsers/texttracks/ttml/native/index.ts

- Keep HTML escape caracters on ttml content:
DOMParser turn HTML escape caracters into caracters, that can be misunderstood by VTTCue API (typically, a less-than sign can be interpreted as the beginning of a HTML tag). After being parsed, all the concerned caracters are know turned back into HTML escape caracters.
- Parse xml:space attribute in all nodes from tt to text tag:
Before, we parsed the attribute in the style tag from ttml. We know look for it at every node level, so we can apply it to subtitle style-sheet (in HTML and native mode).
- Consider paragraph parent div: 
We check for style attributes in the parent div of paragraphs.

Various ttml subtitles fixes

---

src/core/stream/directfile.ts

Fixes a bug introduced in 64eafd4b, that cause the loadedEvent to emit
the loaded function instead of the loaded event object.
Reproducible at http://developers.canal-plus.com/rx-player/. Try to start a directfile. The video starts, but the spinner is still visible.

direct: fix loadedEvent

---

src/parsers/manifest/dash/node_parsers/index.ts

Only video "main" adaptation should be reduced into one:

parsers: reduce main video adaptations only

---

src/core/api/option_parsers.ts

Documentation states that `manualBitrateSwitchingMode` should be optional. This change makes `manualBitrateSwitchingMode` optional in `ILoadVideoOptions`.

misc: make manualBitrateSwitchingMode optional

---

src/compat/index.ts
src/core/buffer/append_data.ts
src/core/buffer/representation_buffer.ts
src/core/source_buffers/abstract_source_buffer.ts
src/core/source_buffers/index.ts
src/core/source_buffers/queued_source_buffer.ts
src/core/source_buffers/text/native/index.ts
src/features/types.ts

Use the very new [1] [sourceBuffer.changeType](https://developer.mozilla.org/en-US/docs/Web/API/SourceBuffer/changeType) API to allow codec-switching.
For now, if the current browser does not have this API, push the content with another codec without doing anything (which might crash, but was the previous behavior).
[1] Chromium 70; Firefox 63 and that's all for now

codec-switching with sourceBuffer.changeType

---

src/parsers/manifest/smooth/index.ts

Easy fix on the HSS manifest parser:
The ``firstTimeReference`` variable was already a value expressed in seconds.
We previously divided it by the timescale a second time. This behaviour led to the following problems:
- The duration for HSS VOD contents not starting at a `0` time was too high.
- The default initial position for HSS VOD contents not starting at a `0` time was before the actual first segment of the manifest.
- ``getMinimumPosition`` for HSS VOD contents not starting at a `0` time returned a time inferior to what it should be

smooth: fix first time reference calculation

---

src/core/pipelines/create_loader.ts

Hi,
It's currently not possible to play manifest urls that have been redirected, because the `xhr.responseUrl` is lost in `create_loader.ts`. Not sure if this worked before.
See: https://switcher.cdn.svt.se/1383013-001A_072aba30.mpd
This change will modify the response value from the pipeline. Previously the url was assigned from `resolverResponse` (which is { url: '...' } in dash).
Also not sure if this is the best fix. Thoughts?
P.S. do you want PRs to master or release branches?

fix: use response url in create_loader

---

src/parsers/manifest/dash/node_parsers/index.ts
src/parsers/manifest/smooth/get_codecs.ts
src/parsers/texttracks/ttml/style.ts
src/utils/__tests__/starts-with.test.ts
src/utils/bytes.ts
src/utils/starts-with.ts
src/utils/url.ts
tslint.json

Using both `substr` and `substring` in the code is confusing.
Also, MDN [tells us](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) that `substr` is now considered a legacy function (even if I didn't find any other source on that one.
What I did there:
- ban `substr` from being used
- use `substring` instead in any part of the code where `substr` was used.

misc: use substring instead of substr

---

src/compat/eme/MediaKeys.ts
src/experimental/tools/mediaCapabilitiesProber/probers/DRMInfos/index.ts
tests/integration/experimental/mediaCapabilitiesProber/getCompatibleDRM.js
tests/integration/index.js

Resolve with result when `requestMediaKeySystemAccess` not available.
Ponyfill of `requestMediaKeySystemAccess`, even when not IE11 (when `isTypeSupported` exists on MediaKeys, as in Safari's Webkit).

Fixed requestMediaKeySystemAccess in mediaCapabiltiiesProber and compat.

---

src/parsers/manifest/dash/indexes/base.ts
src/parsers/manifest/dash/indexes/helpers.ts
src/parsers/manifest/dash/indexes/timeline.ts
src/parsers/manifest/dash/node_parsers/S.ts
src/parsers/manifest/dash/node_parsers/SegmentTimeline.ts
src/parsers/manifest/dash/parseAdaptationSets.ts
src/parsers/manifest/dash/parsePeriods.ts
src/parsers/manifest/dash/parseRepresentations.ts

- dash: handle `S` nodes (segments) with an @r attribute at `-1` in an MPD
- dash: handle `SegmentTimeline` which have as a first `S` node (segment) an undefined @t attribute in an MPD

dash: handle `S` nodes (segments) with an @r attribute at `-1`

---

src/core/api/from_wallclock_time.ts
src/manifest/index.ts

- use availabilityStartTime when it exists to fallback on in case the `minimumTime` property is not set.
- update `minimumTime` on Manifest updates
Also stop throwing in ``__DEV__`` mode for missing live properties.

Manifest: better infer the minimum time of a manifest

---

src/core/api/index.ts
src/core/buffers/adaptation/adaptation_buffer.ts
src/core/buffers/buffer_orchestrator.ts
src/core/buffers/period/period_buffer.ts
src/core/buffers/representation/representation_buffer.ts
src/core/init/create_buffer_clock.ts
src/core/init/events_generators.ts
src/core/init/index.ts
src/core/init/load_on_media_source.ts
src/core/init/types.ts
src/manifest/index.ts
src/utils/eventemitter.ts

The previous redefinition of Manifest as a BehaviorSubject() was ideal but made no real-world sense:
- The API still communicates the Manifest. It would be better for the user if it updated in place
- Never mutating the manifest would complexify the whole chain of buffers where everything from the Manifest to the Segment might need to be re-defined as a BehaviorSubject
- Each part of the code updating the manifest had to use the subject to communicate the change to the rest of the code.
Now, the Manifest itself is an EventEmitter, and trigger a `manifestUpdate` event each time it is mutated (through its `update` method).
Each part of the code that wants to react to those updates now just need to add an event listener to the Manifest.
Unfortunately, the `fromEvent` function from `rxjs` was …

manifest: redefine Manifest to be an EventEmitter

---

src/manifest/manifest.ts

A __really__ dumb typo made most DASH dynamic contents based on SegmentTimeline not "updatable".
This is a major issue.

manifest: fix update mechanism due to inversion of arguments

---

src/compat/__tests__/clear_element_src.test.ts
src/compat/clear_element_src.ts

Reduce the risk to throw when clearing element source on firefox

compat: safely remove track elements on stop on firefox

---

src/parsers/manifest/dash/parse_mpd.ts

Hi!
We noticed that the manifest didn't refresh on our live streams (segment template without segment timeline) as it did before. If you specify a `minimumUpdatePeriod` in the manifest, it should be reflected in the manifest lifetime property.
Thanks!

dash: set manifest lifetime to minimumUpdatePeriod

---

tests/contents/DASH_dynamic_SegmentTimeline/index.js
tests/contents/DASH_static_SegmentBase_multi_codecs/index.js
tests/contents/DASH_static_SegmentTemplate_Multi_Periods/index.js
tests/contents/DASH_static_SegmentTimeline/index.js
tests/contents/Smooth_static/empty_text_track.js
tests/contents/Smooth_static/not_starting_at_0.js
tests/contents/Smooth_static/regular.js

Fixes some raw-loader `require`s which broke in https://github.com/canalplus/rx-player/commit/5dff37824faad91622f9bf680f6ab5e8cdd27e53#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R156
https://github.com/webpack-contrib/raw-loader/pull/69

tests: repair raw-loader requires

---

src/transports/dash/pipelines.ts
src/transports/dash/pipelines_text.ts
src/transports/dash/segment_loader.ts
src/transports/smooth/pipelines.ts
src/transports/smooth/segment_loader.ts
src/transports/utils/manifest_loader.ts
src/utils/request/xhr_request.ts

This helps to simplify the usage of the `xhrRequest` utils, which now will only emit the response by default. This simplification helps encouraging future tools to use the same function to perform XHR request.

code/utils: replace `ignoreProgressEvents` `request` option by `sendProgressEvents` option

---

doc/api/loadVideo_options.md
src/core/eme/_tests__/init_media_keys.test.ts
src/core/eme/eme_manager.ts
src/core/eme/find_key_system.ts
src/core/eme/init_media_keys.ts
src/core/eme/types.ts
src/core/init/__tests__/is_eme_ready.test.ts
src/core/init/initialize_directfile.ts
src/core/init/initialize_media_source.ts
src/core/init/is_eme_ready.ts

Implement ``disableMediaKeysAttachmentLock`` keySystem option, to allow user to opt-out the lock we made in the release `v3.11.0` to be able to load content with both encrypted and unencrypted data in Chrome desktop.
We couldn't find a solution that worked both ways so I had to fall back to one or the other type of deal.
As this only causes problem on some STBs, I choose to let this lock on by default.
I'm still unsure whether this should just be an "experimental" feature or a plain announced, maintained and documented feature. I choose to do all that for now and we will see what to really do before releasing.
I updated the `EMEManager` to communicate more clearly about what it does. More precizely, it now sends two more events:
- `ICreatedMediaKeysEvent`
- `IAttachedMediaKeysEvent`
Those …

eme/api: add disableMediaKeysAttachmentLock keySystem option

---

doc/api/loadVideo_options.md
src/core/eme/handle_session_events.ts
src/core/eme/types.ts

`getLicenseConfig` can be an object with two properties:
- `retry` (`Number`|`undefined`) (default: `2`): number of time `getLicense` is retried on error or on timeout before we fail on a `KEY_LOAD_ERROR`
- `timeout` (`Number`|`undefined`) (default: `10000`): timeout, in ms, after which we consider the `getLicense` callback to have failed.

 api/eme: add getLicenseConfig property to keySystems 

---

src/core/buffers/adaptation/adaptation_buffer.ts
src/core/buffers/events_generators.ts
src/core/buffers/period/period_buffer.ts
src/core/buffers/types.ts
src/core/init/create_buffer_clock.ts
src/core/init/initialize_media_source.ts
src/core/init/load_on_media_source.ts

Previously the `currentTime` and `paused` status was entirely based on the media element.
This could cause problem if we were reloading when we we were not yet playing.
Now, the entity asking for a reload has to provide the time and pausing status at which it wishes to reload.

Provide `currentTime` and `isPaused` when reloading the MediaSource

---

scripts/generate_builds

macOS's sed if a BSD version. It does not work in the same way than GNU one. The -i argument on sed doesn't work with a zero-length extension. Thus, we declare an extension, and then delete back-up unwanted files.
Also, some elements of the regex used in generate_builds are not supported by macOS's sed regex version. (such as `\b`, considered as an enhanced feature instead of an extended regex on macOS).

Update generate_builds script to be compatible with macOS

---

src/core/init/initialize_media_source.ts
src/core/pipelines/manifest/create_manifest_pipeline.ts
src/manifest/manifest.ts
src/parsers/manifest/dash/__tests__/parse_from_document.test.ts
src/parsers/manifest/dash/parse_mpd.ts
src/transports/dash/pipelines.ts
src/transports/types.ts

The previous behavior led to a bug for dynamic SegmentTemplate-based contents without a single SegmentTimeline. This is linked to the fact that we only fetch the UTCTiming the first time the Manifest is parsed and pass for the other ones (as we already have it). The problem is that in a certain condition - the one aforementioned - we use that timing to calculate the maximum possible position (basically the live time here). Without it, we used `Date.now() - 10 seconds` instead (which is most of the time behind the real UTC Time).
The new Behavior now is to actually communicate the clock offset to the parser if we have one. The MPD parser may then use it directly

dash: give the clockoffset to the parser instead of just telling it we have one

---

src/core/buffers/active_period_emitter.ts
src/core/buffers/buffer_orchestrator.ts

Fourth (!) implementation fixing the old "periodChange event before all Representation have been chosen" behavior.
With this one, the `ActivePeriodEmitter` just receive the whole buffers array (one per type).
As with our other new implementations, it emits the first chronoligical period which has every RepresentationBuffer.

Wait for buffers to make adap/rep choices before emitting active period (v4) 

---

src/compat/__tests__/should_use_webkit_media_keys.test.ts
src/compat/browser_compatibility_types.ts
src/compat/browser_detection.ts
src/compat/eme/custom_media_keys.ts
src/compat/should_use_webkit_media_keys.ts

Since Safari 12.1, EME APIs are available without webkit prefix.
However, it seems that since fairplay CDM implementation within the browser is not standard with EME w3c current spec, the requestMediaKeySystemAccess API doesn't resolve positively, even if the drm (fairplay in most cases) is supported.
Therefore, we prefer not to use requestMediaKeySystemAccess on Safari when webkit API is available.

Prefer WebKit EME API on Safari

---

src/parsers/manifest/dash/indexes/template.ts
src/parsers/manifest/dash/indexes/timeline.ts

We didn't update manifest bounds calculator, which is tricky is some of his properties change.

Correctly update indexes when loading a new manifest

---

doc/api/plugins.md
src/transports/dash/low_latency_segment_loader.ts
src/transports/dash/segment_loader.ts
src/transports/smooth/segment_loader.ts
src/transports/types.ts

Add `progress` callback to the segmentLoader API, to improve our adaptive logic when P2P is involved.
Without that callback, we are much less performant after a sudden fall in bandwidth.

api/transports: add `progress` callback to segmentLoader

---

src/manifest/__tests__/update_periods.test.ts
src/manifest/update_periods.ts

Fixed a wrong splice into the update_period function +
Wrote unit tests for this function
In RxPlayer logic, in live conditions, when a new manifest is loaded during playback, all existing periods are updated with new segments to load, in their segment index (theses periods still are the same js objects while they exists in the manifest).
Due to the bug, some periods could be removed and re-added from manifest, instead of being updated.
It means that the period js object handled by the part of the player which is managing buffers was different from the newly created one, while being the same DASH periods.
The new segments existed in the new period indexes, but not in the old one. So, the RxPlayer was buffering because no new segments were available in the period indexes.

Fixed bug in update periods logic

---

demo/full/scripts/components/GenerateLinkURL.jsx
demo/full/scripts/controllers/ContentList.jsx
demo/full/scripts/lib/parseDRMConfigurations.js
demo/full/scripts/lib/url_hash.js

Add the possibility to set a custom key system in the demo page.
To choose a custom key system, the user just as to select the "Other" drm type. Doing that will make a new field appear to specify which key system a user want.

demo: add an "Other" drm choice to specify a custom key system

---

src/custom_source_buffers/text/html/__tests__/utils.test.ts
src/custom_source_buffers/text/html/buffer_manager.ts
src/custom_source_buffers/text/html/html_text_source_buffer.ts
src/custom_source_buffers/text/html/utils.ts
tests/integration/utils/launch_tests_for_content.js

In this branch:
1. we are much less aggressive with text track garbage collection: When removing in the middle of a cue in a given segment, we update the start of the segment but keep the corresponding cue (it was removed before).
It will just last less time than initially set for (but that's what we want)
2. Some fixes have been brought in the `remove` function of the HTML text track BufferManager.
The remove function missed some possible cases.
3. Be exhaustive in the different possibilities in the `insert` function of the HTML text track BufferManager.
Using GC means that we will be left with sub-parts of a segment in the buffer instead of the whole thing. When comparing it to a new, complete, segment which should be put somewhere around it, we have to compare both of their placement …

Fix text track garbage collection / re-insertion (when manual GC is enabled)

---

doc/api/deprecated.md
doc/api/loadVideo_options.md
src/core/api/option_parsers.ts

As far as I know, this API was only used at a time when only native subtitles were available.
It makes little sense know, at least under this form.
The funny thing is that I thought that we deprecated that option a long time ago already (there's even an implicit mention in the changelog about it being already deprecated if we scroll down to the v3.11.0 - version which dates back to march 2019!):
```md
- api: fix (deprecated) option `hideNativeSubtitles`
```

api/doc: deprecate `hideNativeSubtitles`

---

doc/api/deprecated.md
doc/api/index.md
doc/api/parseBifThumbnails.md
doc/api/player_events.md
src/core/api/option_parsers.ts
src/core/api/public_api.ts
src/experimental/tools/index.ts
src/experimental/tools/parseBIFThumbnails.ts
src/parsers/images/bif.ts

Add experimental `parseBifThumbnails` tool, which simply parse a BIF (thumbnails) file into an exploitable object.
I consequently deprecated the following elements from the API:
- the `imageTrackUpdate` event
- the `getImageTrackData` method
- the `supplementaryImageTracks` loadVideo option
There are multiple reasons. The most important ones are about BIF in general:
1. How it should be specified for live contents of for multi-Period DASH contents is not clear enough. Today, no solution exist.
2. Integrating it in the RxPlayer's API means that it had to take multiple choices that we prefer to let to the application: whether to retry the request if the it fails or if it is unavailable, whether to do the request at all for users with a low bitrate...
3. The task of displaying those …

Add parseBifThumbnails tools and deprecate other BIF-related APIs

---

src/parsers/texttracks/ttml/__tests__/resolve_styles_inheritance.test.ts
src/parsers/texttracks/ttml/get_styling.ts
src/parsers/texttracks/ttml/html/__tests__/ttml_color_to_css_color.test.ts
src/parsers/texttracks/ttml/html/parse_ttml_to_div.ts
src/parsers/texttracks/ttml/html/ttml_color_to_css_color.ts
src/parsers/texttracks/ttml/native/parse_ttml_to_vtt.ts
src/parsers/texttracks/ttml/regexps.ts
src/parsers/texttracks/ttml/resolve_styles_inheritance.ts

This PR brings a fix and a feature relative to TTML subtitles:
1. fix alpha information from a "rgba" value in TTML. The bug was due to the fact that we previously thought that it works the same way than for a rgba CSS value. It does not. In CSS it goes from a range starting at 0 (transparent) and ending at 1 (opaque) whereas for TTML it goes from 0 (transparent) to 255 (opaque).
2. Style elements can inherit from other style elements. This was previously not done because it could go ugly quickly. The solution I found was to "resolve" the inheritance just after parsing every style elements (so before parsing almost everything else).
The way I did it might not be the best way, the `IStyleObject` interface now contains an `extendsStyles` property that becomes unnecessary in most of the …

text/ttml: handle styles inheritance of other styles

---

package-lock.json
package.json
src/core/api/public_api.ts
src/manifest/manifest.ts
src/manifest/representation.ts
src/utils/are_arrays_of_numbers_equal.ts
src/utils/byte_parsing.ts

Let's just remove deep-equal as a dependency:
1. it was overkill most of the time
2. it had weird edge case, such as considering `null` and `undefined` as the same thing in a lot of situations
3. Triggering multiple times an event with the same payload was sometimes needed but even when not, it is rarely a real problem
4. Its package size exploded recently and we care about that
5. One less direct dependency needed :-)
I still replaced its usage by some comparisons for very simple cases.

misc: remove deep-equal dependency

---

src/compat/__tests__/should_append_buffer_after_padding.test.ts
src/compat/should_append_buffer_after_padding.ts
src/config.ts
src/core/api/public_api.ts
src/core/buffers/representation/get_needed_segments.ts
src/core/buffers/representation/representation_buffer.ts
tslint.json

When the player decides to load another quality and replace currently buffered one, it may append buffer on current playback time.
On Safari, with HSS contents, this provoques green macro-block screens during the transition. To avoid this situation, we decide not to load a segment if it may be pushed during playback time. We should not buffer under a certain padding from the current time.

Use padding when fast switching on Safari

---

src/parsers/manifest/dash/infer_adaptation_type.ts
src/parsers/manifest/dash/parse_adaptation_sets.ts
src/parsers/manifest/smooth/create_parser.ts
src/parsers/manifest/types.ts
src/parsers/manifest/utils/check_manifest_ids.ts

An `IParsedAdaptation` can now only have one of those four types:
- audio
- video
- text
- image
This was already the case but the property's type was still set to `string`.

parsers/manifest: set a stricter adaptation type

---

src/utils/__tests__/resolve_url.test.ts
src/utils/resolve_url.ts

We had an issue open (#616) on that subject.
When either the URL of the Manifest or some of the BaseURL in it contain query parameters, which themselves contain slash(es) characters, we included a sub-part of the query parameters in the segments URL.
This is not what we want. We want to only truncate until the last slash coming BEFORE the first question mark.
This PR fix that issue. 
I don't know yet what we should do when a "#" is encountered.

dash/smooth: fix base url resolution logic when query parameters contain "/" characters

---

src/parsers/manifest/smooth/create_parser.ts
src/parsers/manifest/smooth/get_codecs.ts
src/transports/smooth/isobmff/create_video_init_segment.ts
src/transports/smooth/segment_loader.ts

Most of Smooth contents video tracks are in H264/AVC.
The RxPlayer can detect it through some properties (e.g. FourCC, codecPrivateData).
If the player can't detect it, it considers it to be avc1 (while there are high chances that it is something else). So it will ask for the browser to decode avc1, and try to create an init segment with an unsupported codec private data. So, the player crashed at this step.
Now, it filters out the tracks were the FourCC is not known, or the codec private data is undefined.
The current bug can be reproduced by trying to play http://playready.directtaps.net/smoothstreaming/TTLSS720VC1/To_The_Limit_720.ism/Manifest.
On this content, the video track is in VC1. This codec is not supported by web browser (but was supported in Microsoft Silverlight).

Filter unsupported quality levels when parsing Smooth manifest

---

src/parsers/containers/isobmff/get_box.ts
src/transports/dash/image_pipelines.ts
src/transports/dash/init_segment_loader.ts
src/transports/dash/low_latency_segment_loader.ts
src/transports/dash/manifest_parser.ts
src/transports/dash/segment_loader.ts
src/transports/dash/text_loader.ts
src/transports/dash/text_parser.ts
src/transports/metaplaylist/manifest_loader.ts
src/transports/metaplaylist/pipelines.ts
src/transports/smooth/extract_timings_infos.ts
src/transports/smooth/isobmff/create_audio_init_segment.ts
src/transports/smooth/isobmff/create_video_init_segment.ts
src/transports/smooth/isobmff/parse_tfxd.ts
src/transports/smooth/isobmff/patch_segment.ts
src/transports/smooth/isobmff/replace_moof.ts
src/transports/smooth/pipelines.ts
src/transports/smooth/segment_loader.ts
src/transports/utils/call_custom_manifest_loader.ts
src/transports/utils/document_manifest_loader.ts
src/transports/utils/get_isobmff_timing_infos.ts
src/transports/utils/parse_text_track.ts

I think that being more explicit in our conditions helps code readability and reduce the chance that a bug is introduced (whether it is because we forgot a case or because the code will evolve in some way which will make a new case possible).
As the task is pretty big, I just did it in `src/transports` for now.

transports: avoid using double equality, even for null/undefined checks

---

src/parsers/manifest/local/parse_local_manifest.ts

Add the `maxiumTime` property on **local** parser based on the total duration of the content.
If not specified, the duration was set to `Infinity`.

maximumTime-LocalTransport-parsers

---

src/config.ts
src/parsers/manifest/dash/parse_mpd.ts

dash/parsers: when a minimumUpdatePeriod is set to 0, set a refresh interval of 3s as a default.
DASH Manifest based on a SegmentTimeline should normally have an
MPD@minimumUpdatePeriod attribute which should be sufficient to
know when to refresh it.
However, there is a specific case, for when it is equal to 0.
As of DASH-IF IOP (valid in v4.3), when a DASH's MPD set a
MPD@minimumUpdatePeriod to `0`, a client should not refresh the MPD
unless told to do so through inband events, in the stream.
In reality however, we found it to not always be the case (even with
DASH-IF own streams) and moreover to not always be the best thing to do.
We prefer to refresh in average at a regular interval when we do not have
this information.
/!\ This value is expressed in seconds.

MPD@minimumUpdatePeriod set to 0: solution 2 - config

---

CONTRIBUTORS
MAINTAINERS.md

The old `CONTRIBUTORS` file, which was kept mostly to not erase the names of the people at the source of the project, was becoming an incomprehensible file.
It mixed old with new contributors, contained only the name of contributors working at Canal+ Group, contained old - now invalid - email addresses.
This is why I've chosen to replace it by a file named `MAINTAINERS.md` instead.
The name is directly taken from [GCC](https://github.com/gcc-mirror/gcc/blob/master/MAINTAINERS) (even if many other projects have one, such as [linux](https://github.com/torvalds/linux/blob/master/MAINTAINERS)).
I found the name better than the previous `CONTRIBUTORS` as this file:
1. does not contain the name of external contributors.
I understand that we might not want to update that file each time a new …

replace CONTRIBUTORS file by MAINTAINERS.md

---

src/core/init/get_initial_time.ts
src/core/init/manifest_update_scheduler.ts
src/manifest/__tests__/manifest.test.ts
src/manifest/manifest.ts
src/parsers/manifest/dash/parse_mpd.ts
src/parsers/manifest/local/parse_local_manifest.ts
src/parsers/manifest/metaplaylist/metaplaylist_parser.ts
src/parsers/manifest/smooth/create_parser.ts
src/parsers/manifest/types.ts
src/utils/__tests__/id_generator.test.ts
src/utils/id_generator.ts

Yet another isolation or related commits that were part of a bigger refacto.
This PR contains multiple improvements related to the Manifest structure:
- the `getClockOffset` method is removed, in profit of just a `clockOffset` property. Most Manifest information is accessible through properties so that difference for the clock offset was a little weird. Even more when we consider that that method just relied on a private `_clockOffset` property
- We didn't do an empty array check after a Manifest update before getting the adaptations for the first period. This could lead to incomprehensible errors when updating a Manifest when the new updated manifest has no period (which should never happen anyway).
- When doing a partial Manifest update (with the optimization of the last release), we …

code: Manifest structure improvements

---

src/core/buffers/orchestrator/active_period_emitter.ts
src/core/buffers/orchestrator/are_buffers_complete.ts
src/core/buffers/orchestrator/buffer_orchestrator.ts
src/core/buffers/orchestrator/get_blacklisted_ranges.ts
src/core/buffers/orchestrator/index.ts

To help with code readability, I moved every BufferOrchestrator-related files to its own directory and no more just at the root of `src/core/buffers`.
This is because those files have the potential to be much more complex if we decide to implement partial periods (btw, let's call them maybe lazy periods, a better informal name).

Move every BufferOrchestrator files to src/core/buffers/orchestrator

---

src/core/api/clock.ts
src/core/api/get_player_state.ts
src/core/api/media_element_track_choice_manager.ts
src/core/api/option_parsers.ts
src/core/api/public_api.ts
src/core/api/track_choice_manager.ts
src/core/init/get_initial_time.ts
src/core/init/manifest_update_scheduler.ts
src/core/pipelines/manifest/create_manifest_pipeline.ts
src/manifest/__tests__/manifest.test.ts
src/manifest/adaptation.ts
src/manifest/are_same_content.ts
src/manifest/manifest.ts
src/manifest/period.ts
src/manifest/representation.ts
src/manifest/representation_index/static.ts
src/manifest/representation_index/types.ts
src/manifest/types.ts
src/parsers/manifest/types.ts
src/transports/types.ts

While doing some refactoring, I noticed that JSDoc-type comments (`/** like this one with two stars characters at the beginning */`) for types, values and functions were automatically picked by my TypeScript language server to do things like auto-completion with added documentation.
I thus updated most `src/api` and `src/manifest` comments to switch to JSDoc-type comments when it made sense. Other directories can follow but this is not high priority.
This was tested on both Vim (with the [coc.nvim extension](https://github.com/neoclide/coc.nvim) that I use now) and VSCode.

doc: generalize the use of JSDoc for type, variable and functions doc

---

doc/api/index.md
doc/api/player_options.md
src/core/api/track_choice_manager.ts

This PR allows to add codec constraints to the  "preferredAudioTracks API" (the `preferredAudioTracks` constructor option, the `setPreferredAudioTracks` method and the `getPreferredAudioTracks` method).
This was mainly motivated by the need in some encountered cases to be able to select tracks in Dolby Digital Plus when those are supported.
This is still portable enough for any future use cases where we can filter on the codec.
Because the codec is not defined on the `Adaptation` (track) in the RxPlayer but on the `Representation`, we had to choose between:
- only take tracks for which every Representation are in the codec wanted
- take all tracks which have at least one Representation in the codec wanted
As we could not find which of those two solutions is the best one, we let the user …

Add "codec" property to preferredAudioTracks APIs

---

src/core/api/public_api.ts
src/core/buffers/orchestrator/buffer_orchestrator.ts
src/core/buffers/period/period_buffer.ts
src/core/init/load_on_media_source.ts
src/core/source_buffers/source_buffers_store.ts

Until now, we create both the audio and video SourceBuffers in advance in the `loadOnMediaSource` function. The information used to create those is based on the containers and codecs information of the first representation from the first adaptation from the first period we will play (!).
This ugly behavior was done because:
1. we need to make sure both SourceBuffers are created before pushing segments to them. If we didn't - and I quote the W3C MSE specification - `a user agent may throw a QuotaExceededError`.
2. The audio and video logic (which choose the Adaptation and Representation of the corresponding type) do not communicate between one another. Updating the code so they can do so is not straightforward nor is it something that we want to do
Moreover, this behavior is incompatible …

Remove the initial creation of SourceBuffers from init

---

src/core/buffers/adaptation/adaptation_buffer.ts
src/core/buffers/orchestrator/buffer_orchestrator.ts
src/core/init/initialize_directfile.ts
src/core/init/initialize_media_source.ts
src/utils/__tests__/defer_subscriptions.test.ts
src/utils/defer_initial_subscriptions.ts
src/utils/defer_subscriptions.ts

Add `deferSubscriptions` operator:
At subscription, instead of "running" the Observable right away, it will wait until the current script has finished executing before actually running this Observable.
This can be important for example when you want in a given function to exploit the same shared Observable which may send synchronous events directly after subscription.
Calling `deferSubscriptions` in those cases will make sure that all such subscriptions in the same function are registered before the Observable start emitting events (as long as such Subscriptions are done synchronously).
Example:
```js
const myObservable = rxjs.timer(100).pipe(mapTo("ASYNC MSG"),
startWith("SYNCHRONOUS MSG"),
share());
myObservable.subscribe(x => console.log("Sub1:", x));
myObservable.subscribe(x => …
```

utils: add `deferSubscriptions` operator

---

src/core/api/track_choice_manager.ts
src/manifest/adaptation.ts
src/parsers/manifest/dash/parse_adaptation_sets.ts
src/parsers/manifest/metaplaylist/metaplaylist_parser.ts
src/parsers/manifest/types.ts

We would like to incorporate the ability to switch between accessibility variants of the video in the player. In order to do so, our thought is to add another video adaptation set with the following role, following the dash-if specification:
```
<AdaptationSet id="1" contentType="video" ...>
<Role schemeIdUri="urn:mpeg:dash:role:2011" value="sign"/>
...
```
So what this change does is to add this information to the concerned video tracks following the same flow as the dub, audio description and etc.
I couldn't find anything related to sign interpretation variants in the dvb-specification tough, which I see you have based the other accessibility roles on. To be honest, I'm not very familiar with dash specifications, so I don't know whether it would be reasonable or not to add changes like …

manifest: Parse information about sign interpretation

---

doc/api/index.md
doc/api/player_options.md
doc/terms.md

This new version of the API documentation landing page brings some improvements:
1. Method documentation is now grouped by role (e.g. volume control, track selection etc.)
2. I added precision about multi-period contents in the track selection and bitrate selections
3. several typos have been fixed.
This is still not a huge change, I hesitated making those "method groups" "collapse-able" but decided against for now. 
That new version can be seen in action here: https://developers.canal-plus.com/rx-player/new-api-doc/pages/api/index.html

Doc: better api documentation landing page

---

doc/api/deprecated.md
doc/api/index.md
src/core/api/public_api.ts

This PR deprecate the following 3 APIs:
-  `getManifest`
- `getCurrentAdaptations`
- `getCurrentRepresentations`
This is because they expose our internal representation of the manifest, which may be something that we want to change without breaking the API.
We could also add a translation layer to be sure we didn't broke it while still being able to update it, but they seem to not be really used, so there would be no point.
Also, not having the word `Adaptation` in any of our method's names (there's still a property given to a custom `segmentLoader` though) opens the way for renaming that concept into the more universal "Track" in a future version.

Deprecate `getManifest`, `getCurrentAdaptations` and `getCurrentRepresentations`

---

src/core/buffers/adaptation/adaptation_buffer.ts
src/core/buffers/events_generators.ts
src/core/buffers/orchestrator/buffer_orchestrator.ts
src/core/buffers/period/period_buffer.ts
src/core/buffers/types.ts

The previous behavior could lead in an infinite loop with multiple Periods.
For example, let's take two consecutive Periods: the currently playing Period `A` and `B` the next Period we are preloading. Because the current user wants to disable the current video track (without changing his/her video track preferences, so no impact on other Periods) we will be in a case where A needs to have no video SourceBuffer and B needs one.
So A will ask for a reload, obtain it, and then we will have no video SourceBuffer. Here, B won't be happy so it will also ask for a reload, also obtain it and we will have a video sourcebuffer, and so on. We will be in an infinite buffering loop.
The current solution I found is that everything can continue how it was but the 'parent' of both - the …

Only reload the MediaSource when the most immediately needed PeriodBuffer is asking for it.

---

src/core/buffers/orchestrator/buffer_orchestrator.ts
src/core/eme/eme_manager.ts
src/core/fetchers/utils/create_request_scheduler.ts
src/utils/__tests__/filter_map.test.ts
src/utils/filter_map.ts

Add `filterMap` utils when we both want to map and filter out some values.
The previous way for doing that was through the `mergeMap` operator, by returning the EMPTY observable when we wanted to ignore a value. However doing that and needing to always wrap values in an Observable was both less readable and, it turns out, much less performant than we originally thought.
After doing some tests, both by creating a simple [node.js script](https://gist.github.com/peaBerberian/221800d218730fcf86c6bef4705e129d) (notes: it needs rxjs as a dependency, also the first set of tests takes a lot of time and can be ignored, this is probably due to the JIT compiler warming up) and by running benchmarking tools (like [hyperfine](https://github.com/sharkdp/hyperfine)) we found that even for a very small …

utils: add filterMap utils

---

src/parsers/manifest/local/parse_local_manifest.ts

The `language` property on adaptation was omitted for a local manifest.
I don't know if it was intentional or just a miss but I think it would be very useful to have it back.

Add language property to adapation for local manifest

---

package-lock.json
package.json
webpack.config.js

To polyfill async / await, babel uses generator functions. Then, it polyfills generator function using a "regenerator" function. The latter can be used in code with either:
- Babel polyfill
or,
- Babel transform runtime plugin
As we do not use Babel polyfill, because we implement our owns polyfill or import independently unique polyfill for some special cases, we shall use regeneration runtime with the plugin.

Fixed babel not handling well async / await.

---

src/parsers/manifest/dash/indexes/timeline/timeline_representation_index.ts

When loading a content with a `manifestUpdateUrl` (what we call the "short Manifest", where a shorter Manifest is used for Manifest updates to improve update performances), we noticed a bug where we wouldn't be able to seek behind the boundary of the sorter Manifest (thus making the point of that technique moot!).
During debugging, I noticed that updates perform the right modification.
Timelines, which contain information about every segments, were properly updated with segments older than what is in the short Manifest still available.
It was actually the ManifestBoundsCalculator's fault. The ManifestBoundsCalculator is a class allowing "to easily calculate the first and last available positions" of the whole Manifest at any time.
It works today by calculating the minimum position of the …

dash: do not update the ManifestBoundsCalculator when updating with a shorter Manifest

---

demo/full/scripts/index.js
package-lock.json
package.json

As seen in another PR (#729) the @babel/polyfill was only a shortcut to both core-js and the regenerator-runtime, which are also two different things.
Understandably, @babel/polyfill is now deprecated in profit of importing both directly.
Despite the appearance I add no dependency to the RxPlayer here, as what I added was already a dependency of @babel/polyfill.
Consequently, I even removed one (which is... @babel/polyfill!).
This seems to lead toward a less readable code when importing both in the demo but it actually kind of make much more sense when the time comes where you have to understand what all this does.
I would still have preferred not have to do with a regenerator runtime all together (still don't know why it's not added directly by babel during transpilation).

demo: don't depend on babel/polyfill for the demo anymore

---

src/core/eme/media_keys_infos_store.ts
src/core/eme/session_events_listener.ts
src/core/eme/set_server_certificate.ts
src/utils/rx-retry_with_backoff.ts

Minor cosmetic changes on the EME code:
1. `IMediaElementMediaKeysInfos` is a "regular" interface now, which means it does not include `null` anymore. Previously it was an union between its value and `null`. This did not conform to how we write our types in other part of the code, so I fixed it
2. The `SessionEventsListener` where most of the license fetching logic happens has been "factorized" a little. What I mean by that is that some sub-parts have been moved to top-level functions. I hope it's easier to read that way.
3. minor change in the `trySettingServerCertificate` function where I inverted the two branch too make it more readable.
I hesitated to push directly to master, but it might need to be re-read with more attention before merging it.

eme: minor cosmetic code change

---

src/core/fetchers/manifest/create_manifest_fetcher.ts
src/experimental/tools/createMetaplaylist/get_duration_from_manifest.ts
src/parsers/manifest/dash/get_http_utc-timing_url.ts
src/parsers/manifest/dash/node_parsers/AdaptationSet.ts
src/parsers/manifest/dash/node_parsers/BaseURL.ts
src/parsers/manifest/dash/node_parsers/ContentComponent.ts
src/parsers/manifest/dash/node_parsers/ContentProtection.ts
src/parsers/manifest/dash/node_parsers/Initialization.ts
src/parsers/manifest/dash/node_parsers/MPD.ts
src/parsers/manifest/dash/node_parsers/Period.ts
src/parsers/manifest/dash/node_parsers/Representation.ts
src/parsers/manifest/dash/node_parsers/SegmentBase.ts
src/parsers/manifest/dash/node_parsers/SegmentList.ts
src/parsers/manifest/dash/node_parsers/SegmentTemplate.ts
src/parsers/manifest/dash/node_parsers/SegmentURL.ts
src/parsers/manifest/dash/node_parsers/__tests__/AdaptationSet.test.ts
src/parsers/manifest/dash/node_parsers/__tests__/Initialization.test.ts
src/parsers/manifest/dash/node_parsers/__tests__/SegmentURL.test.ts
src/parsers/manifest/dash/node_parsers/__tests__/utils.test.ts
src/parsers/manifest/dash/node_parsers/utils.ts
src/parsers/manifest/dash/parse_mpd.ts
src/transports/dash/manifest_parser.ts
src/transports/local/pipelines.ts
src/transports/metaplaylist/pipelines.ts
src/transports/smooth/pipelines.ts
src/transports/types.ts
src/transports/utils/return_parsed_manifest.ts

Until now, minor MPD parsing errors (which is mostly when an attribute in the parsed XML is not in the expected format) only resulted in the RxPlayer calling its `log.warn` function (which itself call `console.warn` under certain conditions).
I thought that it may benefit applications to also send `warning` events on those cases, as sending JavaScript objects seems a much more flexible solution than just calling `console.warn` or not depending on the current logger level. For example, this will allow an application to register those through their own logging solution.
To stay in line with our API, such warnings events will have the `PIPELINE_PARSE_ERROR` error code and the `OTHER_ERROR` type.
Users will know which MPD attribute caused a problem by inspecting the human-readable `message` …

misc/emit warning events after parsing an invalid MPD

---

src/core/buffers/orchestrator/buffer_orchestrator.ts
src/core/source_buffers/index.ts
src/core/source_buffers/source_buffers_store.ts

The RxPlayer can be bound to any HTMLMediaElement (for now this just means audio and video elements). Previously the RxPlayer downloaded all types of buffers ("video", "audio" and depending on the build "text" and "image") regardless of what element was used.
However it's mainly a waste of network resources to download video on an
audio element, as those cannot render the video we will push to its
SourceBuffer.
This PR does a special treatment when encountering an HTMLAudioElement.
Only on this case, no video will be downloaded.
I did that by updating the place where `getBufferTypes` - which returns the complete list of supported buffer types - is defined.
Previously at top-level, it is now a method of the SourceBufferStore (which makes sense as it already contained similar methods such …

source-buffers: Do not create a video SourceBuffer on an audio element

---

src/core/eme/find_key_system.ts

We have a logic which avoids to create a new MediaKeySystemAccess each time a new content is loaded by looking at the new `keySystems` configuration and seeing if it is still "compatible" with the one created previously.
This then allow to re-use a given MediaKeys, then to even allow to re-use a previously created MediaKeySession.
However our logic was too "tolerant". Setting the `persistentStateRequired` `keySystems` option to `true` would not ensure that the previously used MediaKeySystemAccess had a `persistentState`
set to `required`.  A `persistentState` set to `optional` or even worse, `not-allowed` would have been accepted.
We now check that if `persistentStateRequired` is set to `true`, the previous MediaKeySystemAccess used has a `persistentState` equal to`required`. If that is …

eme: fetch a new MediaKeySystemAccess if persistentState changes to "required"

---

src/core/api/clock.ts
src/core/buffers/representation/representation_buffer.ts
src/core/eme/eme_manager.ts
src/core/fetchers/segment/create_segment_loader.ts
src/core/source_buffers/queued_source_buffer.ts
src/utils/assert_unreachable.ts

I added multiple `assertUnreachable` checks to branch-heavy places in our code.
Basically, this is mostly to ensure at compile-time that every possible cases have been handled. Here, I'm most-of-all thinking about our event-type discriminated unions which rely on big switch statement where different events correspond to different actions taken in response.
Not doing this assertion could lead to bugs. For example, we could decide to add an event but forget to update a switch elsewhere, which might receive that event and perform a default action on it we do not want it to do.
I actually found an example of that in our code. There is a minor bug where the new (v3.20.1) `cleaning-old-session"` and `"cleaned-old-session"` events were not properly ignored in `eme_manager.ts`.
Here we could be …

Make much more use of the assertUnreachable function, to check branch exhaustiveness

---

README.md
doc/api/index.md
doc/tutorials/index.md
doc/tutorials/quick_start.md
doc/tutorials/stream_events.md
src/core/api/__tests__/media_element_track_choice_manager.test.ts
src/core/api/media_element_track_choice_manager.ts
src/core/api/track_choice_manager.ts
src/parsers/texttracks/webvtt/html/__tests__/create_style_attribute.test.ts
src/parsers/texttracks/webvtt/html/create_style_attribute.ts
src/parsers/texttracks/webvtt/html/to_html.ts

This new tutorial will explain how to listen to stream events in the RxPlayer.
It also acts as a draft here to help define a stream event API that is:
- featureful
- future-proof (for example, `emsg` box will surely go through the same API)
- understandable and usable by a library user.
Any change @grenault73 ?

doc: add stream events tutorial

---

src/core/eme/utils/loaded_sessions_store.ts
src/core/eme/utils/persistent_sessions_store.ts

We had an unfortunate issue when calling the `closeAllSessions` method of a LoadedSessionsStore, where no MediaKeySessions would actually be removed (and we would just be leaving them dangling on the MediaKeys).
Thankfully the impact of that issue was rather limited.
From what I can see, only applications using the `closeSessionsOnStop` `keySystems` option should have been impacted as the other path calling that method also remove the corresponding MediaKeys instance from the HTMLMediaElement (which should - I'm guessing here - correctly garbage collect its associated MediaKeySessions).
The issue in itself was tricky:
1. We're defining multiple Observables which will remove one by one the current MediaKeySessions.
2. We re-initialize the `_storage` private property. This is I guess so …

eme: fix `closeAllSessions` call to REALLY close all MediaKeySessions

---

src/core/init/manifest_update_scheduler.ts

Under the previous code, we aborted any Manifest refresh operation if we did not find an URL associated to the Manifest. This might seem logical at first, but we may also have a custom `manifestLoader` defined through the corresponding loadVideo option, which make the presence of the URL completely optional.
The real use cases are for when the Manifest is available locally, most of all under the `local` transport to be able to play content offline. In such contents, we never have an URL, only a custo `manifestLoader` which will retrieve the stored contents directly from memory or whatever browser storage API is available (IndexedDB, custom APIs...).

Refresh the Manifest even if we dont have a Manifest URL

---

doc/api/index.md
src/core/api/__tests__/media_element_track_choice_manager.test.ts
src/core/api/media_element_track_choice_manager.ts
src/core/api/public_api.ts
src/core/api/track_choice_manager.ts
tests/integration/scenarios/dash_multi-track.js

This PR allows the RxPlayer to fill what I would call a hole in our APIs related to track management.
We have `set{Audio,Video,Text}Track` which allow to select a specific track but those only set the track for the current Period and have no influence on the potential other ones. This was done because you might not find the exact same tracks in other Periods.
`disable{Video,Text}Track` work the same way. Here we could just choose to disable that track for every Periods but we chose to stay coherent with the setters APIs.
When you want to influence the tracks from other Periods, you have to use the track preference APIs (like `setPreferred{Audio,Video,Text}Tracks`). However here we have the reverse problem.
Those APIs won't update the choices for Periods that have either been already …

api: allow applying track preferences to already loaded Periods

---

CHANGELOG.md
doc/api/exported_types.md
src/core/api/index.ts
src/core/api/public_api.ts
src/core/init/stream_events_emitter/index.ts
src/public_types.ts

This is to allow TypeScript codebases to use it

export IStreamEvent and IStreamEventData types through the exported types APIs 

---

src/utils/__tests__/ranges.test.ts
src/utils/ranges.ts

Found by code inspection, not by hitting any user-visible problem.
Keeping the post-decrement for consistency with the rest of this file.
Fixes #750

utils: Fix removeEmptyRanges() with multiple consecutive empty ranges

---

demo/full/scripts/lib/url_hash.js

Fixes #758.
We used a backslash ("\") character as a key separator in generated link but I found out those needed to be percent-encoded to be in a valid URL.
We had no problem when directly linking to that URL but I found out, after sharing that link on outlook, that the link didn't work as expected anymore. This is because outlook percent-encoded it (this seems to be a side effect of their "safelink" protection scheme).
When getting links that where percent-encoded, the demo page didn't know what to do and thus acted as if no content was set through the URL (as a resilience measure).
By using now "!", a perfectly valid character in the fragment of an URL, we can now avoid that issue.
Note that the demo page is still compatible with URL with "\" characters, so links created with older …

demo: now use "!" as a key separator in generated links

---

src/parsers/manifest/smooth/representation_index.ts

There was a strange condition in smooth content handling that made it impossible to skip stream discontinuities when the user seeked at the middle of one.
Basically, the player needed to still be in the segment preceding the discontinuity to be able to skip it. This condition made no much sense, and it isn't something that does exist in the related DASH SegmentTimeline's code.
I'm consequently unsure if this was done on purpose, in which case we would bring a regression here. In anyway, I find this not very probable and if that was the case, that code should have been commented.
---
Note: I also changed some variable's names. The real meat is just one line being deleted.

smooth: skip discontinuity even when we're in the middle of it

---

src/manifest/manifest.ts

Fixes #775.
A "partial update" (that is an update with a shorter version of the Manifest to allow parsing optimizations) of a Manifest wrongly updated the `uris` property of the Manifest.
This is not what we want to do because it means that for the RxPlayer the new "true" URL of the Manifest is the one taken from the shorter version.
This has no effect right away, but after some time we might be in a situation where the RxPlayer want to re-perform a "full update" with what it thinks is the URL of the "normal" Manifest (which is in reality still the URL of the shorter version). This usually happens when the RxPlayer wants to make sure its local version of the Manifest is still synchronized to the true version from the server.
When doing so, it resets the current content as if we were …

manifest: do not update manifest uris on partial updates

---

doc/architecture/files.md
jest.config.js
src/compat/eme/custom_media_keys/old_webkit_media_keys.ts
src/compat/eme/custom_media_keys/types.ts
src/compat/eme/custom_media_keys/webkit_media_keys.ts
src/compat/eme/index.ts
src/compat/event_listeners.ts
src/compat/index.ts
src/core/eme/__tests__/__global__/get_license.test.ts
src/core/eme/__tests__/__global__/init_data.test.ts
src/core/eme/__tests__/__global__/media_key_system_access.test.ts
src/core/eme/__tests__/__global__/media_keys.test.ts
src/core/eme/__tests__/__global__/server_certificate.test.ts
src/core/eme/__tests__/__global__/utils.ts
src/core/eme/find_key_system.ts
src/core/eme/get_media_keys.ts
src/core/eme/session_events_listener.ts
src/core/eme/set_server_certificate.ts
src/core/eme/types.ts
src/core/eme/utils/loaded_sessions_store.ts

The EME part of our code has very few tests despite having the highest density of [spotted] issues in  our last releases.
We actually completely skip that part in our integration tests. This is because the time investment to add them is important:
- first we have to provide encrypted contents to our tests (and not our "real" production ones as we are open-source)
- we would need to test clearkey + playready + widevine (+ nagra?) contents and run tests on devices that support those. Doing this is planned but it's not yet the case.
- it would take a lot of time to write tests for every small EME features (such as our session caching logic)
- some tests would not run in an acceptable time limit (like reaching our maximum 1000 simultaneous persistent MediaKeySessions)
In our last release, the …

Global EME unit tests 

---

src/config.ts
src/core/buffers/representation/representation_buffer.ts
src/core/fetchers/index.ts
src/core/fetchers/segment/__tests__/prioritizer.test.ts
src/core/fetchers/segment/index.ts
src/core/fetchers/segment/prioritized_segment_fetcher.ts
src/core/fetchers/segment/prioritizer.ts
src/core/fetchers/segment/segment_fetcher.ts
src/core/fetchers/segment/segment_fetcher_creator.ts

Fixes #752 .
In our segment request scheduling logic, we have a notion of priority.
Each new segment request has an associated priority number. The lowest is that number (starting at 0), the highest is that request's priority over other segment requests.
When multiple segment requests are needed (generally we are talking about segment of different types here - like audio, video... - which are downloaded concurrently), the "segment fetchers" (the part of the RxPlayer scheduling and asking for segment requests) will first start the request with the highest priority. Once done, it will start the request with the next highest priority and so on.
Because the player is playing at the same time that the requests are performed, it is possible that the priority of different segment
requests evolve …

fetchers: add the concept of "high priority" segment requests

---

src/config.ts
src/core/buffers/adaptation/adaptation_buffer.ts
src/core/buffers/representation/index.ts
src/core/buffers/representation/representation_buffer.ts

There was a sort of race condition in the code which could lead to downloaded segments being immediately replaced once the adaptative logic decided to urgently switch the current quality.
That problem is a little hard to explain as it necessitates a lot of context.
I will try to be as descriptive as possible in the next lines.
Since we added low-latency content support, we updated the behavior of a module called the `SegmentInventory` (which stores information about the currently loaded segments). This module allows to let the rest of the code know which segments has currently been pushed to a SourceBuffer.
Low-latency contents often rely on segment being subdivided intomultiple chunks.
For this reason, most of the RxPlayer's code now consider that one segment may contain multiple chunks …

buffers: urgent quality switch now do not interrupt segment pushing operations

---

src/core/buffers/representation/get_needed_segments.ts
src/core/buffers/representation/representation_buffer.ts
src/core/source_buffers/index.ts
src/core/source_buffers/queued_source_buffer.ts

Previously a RepresentationBuffer had a special variable named `loadedSegmentPendingPush` which registered every segments for which the request was ended but which were still being pushed to the SourceBuffer.
It is a necessary information to avoid re-download a segment that is neither being downloaded nor being already in the Buffer. Without it, the `RepresentationBuffer` - with enough luck - might decide to re-load the corresponding segment (as it will think that it has been garbage collected by the browser).
I moved that "registration" role to the QueuedSourceBuffer, which already maintains a queue of pending operations. I then added a `getPendingOperations` method to it so a `RepresentationBuffer` can directly look at it to see which downloaded segments are being pushed.
This has the …

buffers: Rely directly on the QueuedSourceBuffer for pending operations

---

src/config.ts
src/core/abr/network_analyzer.ts
src/core/abr/pending_requests_store.ts
src/core/abr/representation_estimator.ts

This commit tries to improve our ABR performance through three main code updates:
1. The "factor" used to pick a "safe" Representation from a calculated bandwidth (when not in starvation mode) has been lowered: from 0.9 to 0.8.
For example, when the calculated bandwidth is 10Mbps and when we're choosing the Representation based on the network bandwidth, only the Representations having a bitrate lower or equal to 8Mbps will be considered.
This can appear drastic but it is counter balanced by the fact that:
- more rebuffering situations can be avoided, which is much more important that playing at the best bitrate possible
- the RxPlayer also has a buffer-based ABR logic, which is not constrained by that factor
2. When we're in starvation mode, the previous logic checking for sudden fall in …

abr: limit oscillation in ABR estimates

---

src/parsers/manifest/dash/indexes/base.ts
src/parsers/manifest/dash/indexes/list.ts
src/parsers/manifest/dash/indexes/template.ts
src/parsers/manifest/dash/indexes/timeline/timeline_representation_index.ts
src/parsers/manifest/dash/node_parsers/AdaptationSet.ts
src/parsers/manifest/dash/node_parsers/Period.ts
src/parsers/manifest/dash/node_parsers/Representation.ts
src/parsers/manifest/dash/node_parsers/SegmentBase.ts
src/parsers/manifest/dash/node_parsers/SegmentTemplate.ts
src/parsers/manifest/dash/parse_adaptation_sets.ts
src/parsers/manifest/dash/parse_mpd.ts
src/parsers/manifest/dash/parse_periods.ts
src/parsers/manifest/dash/parse_representation_index.ts
src/parsers/manifest/dash/parse_representations.ts
tests/contents/DASH_static_SegmentTimeline/index.js
tests/contents/DASH_static_SegmentTimeline/media/segment_template_inheritance_as_rep.mpd
tests/contents/DASH_static_SegmentTimeline/media/segment_template_inheritance_period_as.mpd
tests/contents/DASH_static_SegmentTimeline/segment_template_inheritance_as_rep.js
tests/contents/DASH_static_SegmentTimeline/segment_template_inheritance_period_as.js
tests/contents/DASH_static_SegmentTimeline/urls.js
tests/integration/scenarios/dash_static.js

Fixes #767 
This PR implements a new DASH behavior when parsing a MPD:
SegmentTemplate at different levels (for example at the `Period`, `AdaptationSet` _AND_ `Representation` levels) are all merged into one once converted into our internal `Manifest` structure.
This follows multiple MPDs we have seen recently that present this particularity. This should not break any other use-case.
The way I implemented it is by making the node_parsers part of our DASH parser (which has the task to take the MPD from its original `document` form and transform it to a JS object, very close to the original but with attributes in the right type - called the "intermediate representation") even dumber than before by removing the previous explicit distinction between a "SegmentTemplate" and a …

DASH: MPD SegmentTemplate inheritance

---

src/compat/browser_detection.ts
src/compat/eme/get_uuid_kid_from_keystatus_kid.ts
src/core/eme/check_key_statuses.ts
src/core/eme/eme_manager.ts
src/core/eme/session_events_listener.ts
src/parsers/containers/isobmff/drm/playready.ts
src/utils/__tests__/string_parsing.test.ts
src/utils/string_parsing.ts

Media data can be cyphered in a stream. A media content is cyphered with a key, who is identifiable with a public KeyID. A content may not be playable depending on the playback device / client authorizations.
In the RxPlayer, we use manifest content protection data to associate a a media quality to a CENC formatted KeyID. Then, when the MediaKeySession informs us about key statuses, we can deduct the decipherability status of a quality.
For this reason, we need the KeyIDs in our caches to be the same format. PlayReady KeyID's are little-endian GUID, whether it be on PSSHs or in EDGE and IE11 keyStatuses map from MediaKeySession. Standard CENC KeyID are big-endian UUID (cenc, widevine). Hence, our decipherability record logic can't work because those are two different formats.
This PR …

Convert GUID Playready KID when necessary

---

src/core/stream/adaptation/adaptation_stream.ts
src/core/stream/adaptation/create_representation_estimator.ts
src/core/stream/events_generators.ts
src/core/stream/representation/get_needed_segments.ts
src/core/stream/representation/representation_stream.ts
src/core/stream/types.ts

This is an improvement over #781 and builds on top of it.
It tries to fix the last problem with that PR, which is that we might have a short time (maximum 20 milliseconds on my PC) where no segment is loaded when we perform a transition between qualities.
That issue arised lately because #781 added a behavior where we are now waiting until a `RepresentationBuffer` pushed all the segments it has loaded before going to the next `RepresentationBuffer`. We have reasons for doing that, I invite you to read that previous PR to get some context if you want to know more.
This solution is basically the one brought in #781 in "The problem with that solution" chapter.
Here a `RepresentationBuffer` emits a new event - for now called `"buffer-terminating"` - to indicate that it has finished loading …

Faster safer quality switch

---

src/core/fetchers/utils/try_urls_with_backoff.ts

This fix concerns segment requests for segment with multiple associated URLs.
Due to a misunderstanding of how the `Array.prototype.slice` API worked, multiple URLs were ignored as soon as one of them failed on an error indicating that we should not retry.
Basically, we wrote:
```ts
urlsToTry.splice(index);
```
Which means that we should remove every URLs in `urlsoTry` from the `index` index.
Where I think we meant:
```ts
urlsToTry.splice(index. 1);
```
Which just does remove the element at `index`.

Still retry all other segment's URLs when a non-retryable error happen on the request for one of them

---

src/manifest/manifest.ts
src/manifest/update_periods.ts

This fix concerns a bug that arised when playing multi-periods live contents when a `manifestUpdateUrl` is set.
When playing those, the player could appear to be rebuffering indefinitely after some time.
The `manifestUpdateUrl` option allows to speed-up the process of parsing giant Manifest files.
As only information about new segments is most of the time needed when doing updates, it permits to use another version of that Manifest with a lower depth for updates.
Because we only know about new segments, we have to perform clean-up of older segments and Periods manually. And that's where the error was: in the clean-up of Periods.
The logic is relatively simple: after updating the Manifest through a so-called "partial" update (done with a shorter version of the
Manifest), we manually remove …

manifest: when doing partial updates avoid removing too much Periods when one is too old

---

src/compat/eme/custom_media_keys/old_webkit_media_keys.ts
src/parsers/containers/isobmff/drm/playready.ts
src/parsers/manifest/smooth/parse_protection_node.ts

This is a fix of a bug introduced very recently (not yet released) while refactoring our code handling string encoding (#791, corresponding to the merge commit ca11ab9f8fb4dcf0d48fc55cc112e57db0287195).
In those modifications, I replaced most (all?) usages of the`strToBytes` function by the new `strToUtf8` function.
This is because `strToBytes` took an UTF-16 string 2 bytes at a time and considered only the lower 8 bit half to construct another byte array: this suspiciously looks like a naive way to translate UTF-16 encoded ASCII characters to UTF-8.
And it was used most of the time just for that. But not always, and that's where the bug was.
There are multiple places (I counted 3, all fixed in this commit) where it was used for a different use case: to transform base64 to an array of …

Fix wrong usage of strToUtf8 when what was really wanted was Base64 decoding

---

.gitignore
doc/api/index.md
scripts/generate_builds
src/compat/eme/get_webkit_fairplay_initdata.ts
src/parsers/containers/isobmff/drm/playready.ts
src/tools/index.ts
src/tools/string_utils.ts
src/utils/__tests__/string_parsing.test.ts
src/utils/string_parsing.ts

This commit allows to export util functions related to string to byte parsing and vice-versa.
Considering that an application might have to put its hands into things like challenges or licenses parsing, which depending on the key system might contain text in some form (at least for fairplay and playready) this might be a good idea to let them use our corresponding functions.
I chose to export the following functions for now:
- `strToUtf8`
- `utf8ToStr`
- `strToUtf16LE`: this is `strToLeUtf16` that I renamed by putting the endianness all caps after. This seems to be a more common form for that encoding.
- `utf16LEToStr`: likewise for `leUtf16ToStr`
- `strToUtf16BE`: Same thing than strToUtf16LE but for big endian UTF-16.
We don't need it in the RxPlayer but considering:
1. We already have …

api: export StringUtils from "rx-player/tools"

---

doc/api/TextTrackRenderer.md
doc/api/index.md
scripts/generate_builds
src/experimental/tools/index.ts
src/tools/TextTrackRenderer/index.ts
src/tools/TextTrackRenderer/text_track_renderer.ts
src/tools/index.ts

Considering the small API of the TextTrackRenderer, and considering it has already been seen to work reliably with multiple formats, we can begin to remove its `experimental` status.
This means that we ensure API compatibility at least until a future `v4.x.x`.

tools: Make the TextTrackRenderer not experimental anymore

---

src/core/eme/attach_media_keys.ts
src/core/eme/clear_eme_session.ts
src/core/eme/create_session.ts
src/core/eme/dispose_media_keys.ts
src/core/eme/find_key_system.ts
src/core/eme/get_media_keys.ts
src/core/eme/get_session.ts
src/core/eme/init_media_keys.ts
src/core/eme/session_events_listener.ts
src/core/eme/set_server_certificate.ts
src/core/eme/utils/persistent_sessions_store.ts

During recent debugging sessions related to DRM, we found out that important steps, such as the communication of a licence, were only logged when the `LOGGER_LEVEL` is set to DEBUG. As this is a very important step, it seems that log could be displayed even when the level is set to INFO.
In that commit, I chose to display the important EME steps (creating the MediaKeySystemAccess, creating the MediaKeys, attaching the MediaKeys, creating the session, receiving and sending data from the CDM and the possible clean-up on stop) in the INFO logger level (which might raise up the verbosity on that level, but mostly at initialization).
Because the return of some of those steps is almost as important as the action, I chose to also log when those succeed.
This commit also add logs for the DEBUG …

eme: add more EME-related logs and raise-up verbositiy for INFO level

---

src/core/stream/representation/representation_stream.ts

This is a fix for a rare new bug we seem to encounter starting from our `v3.21.1` release.
Note that I did not succeed to reproduce it, so this is mostly an hypothesis.
The error might appear when updating the priority of a previously non-pending segment request. If it's priority is high enough for it to be launched right away and if this segment request ends synchronously after being started (which is a relatively rare occurence, but it can be the case for smooth initialization segments - as they are locally-generated - or any cached in-JS initialization segments), it is theorically possible that the `currentSegmentRequest` variable we use in the `RepresentationStream` to refer to the... current segment request is set to `null` directly (as it should because the request just ended).
The …

stream: avoid error when updating the priority of a synchronous request

---

src/core/eme/init_media_keys.ts
src/core/init/initialize_directfile.ts

This MR is related to the opened issue #827 
This is was a bug encountered in **directfile** mode on trying to play HLS encrypted content.
Basically, the player went in a **LOADING** infinite-state until a media error is thrown after a long period.
From what I understood, the problem came from the fact that we don't have to wait for the Media source to be open to attach the media keys in **directfile**, but for some reasons, the media keys didn't get attached because of the condition was always false and the statement was not present.
I also got rid of `disableMediaKeysAttachmentLock`, from what I understood it's to prevent deadlock on peculiar devices where it might be needed in order to play encrypted content.
I don't know if we still need it in **directfile**, and I think, he was miss …

fix(directfile-eme): Fix a bug where the CDM will never know when the media key will be attached in directfile

---

src/features/__tests__/add_features.test.ts
src/features/__tests__/initialize_features.test.ts
src/features/add_features.ts
src/features/features_object.ts
src/features/index.ts
src/features/initialize_features.ts

This is a small fix to avoir a circular dependency in the `src/features` directory.
Basically, the `features` object, which, was declared in `src/features/index.ts`, was imported by `src/features/add_features.ts`.
This is problematic because `src/features/index.ts` also imports `src/features/add_features.ts`.
There was no real reason to declare the `features` object in `index.ts` other than convenience. In this commit, I move it to its own
`features_object.ts` file.
This issue led to no build error that I know of, but it is still an ugly avoidable situation.

features: avoid circular dependency in `src/features`

---

src/core/eme/utils/is_session_usable.ts

Previously, when loading a persistent session with keys deemed as not
usable, we just logged that the loaded MediaKeySession was "not usable".
To help debugging, this commit now clearly enounce which of the three
reasons are to blame:
1. There are no keys
2. At least one key has the "expired" status*
3. At least one key has the "internal-error" status*
*On this subject, we might want to change that rule in the future.
Persisted licences might contain multiple keys, and we might only care
about some of them. The more sensible thing to do might be to check that
at least one can be used (even if it can also get more complicated, e.g.
we might want to re-request expired ones anyway).

eme: better log why a session is not considered as "usable"

---

src/core/init/create_eme_manager.ts
src/core/init/events_generators.ts
src/core/init/index.ts
src/core/init/initialize_directfile.ts
src/core/init/initialize_media_source.ts
src/core/init/load_on_media_source.ts
src/core/init/stream_events_emitter/index.ts
src/core/init/stream_events_emitter/types.ts
src/core/init/types.ts
src/core/stream/orchestrator/stream_orchestrator.ts
src/core/stream/types.ts

Most modules internal to the RxPlayer emit some kind of events.
Due to its architecture, modules are sometimes contained in bigger modules (the most impressive example would be the `StreamOrchestrator`, which "orchestrates" multiple `PeriodStreams`, which switch between `AdaptationStreams` which switch between `RepresentationStreams`).
Those outer-facing "super-modules" most often simply combine the events of all contained sub-modules so they can be handled at a higher level as if they were all coming from the same place (the `StreamOrchestrator` in our example).
This way of doing things for a player has been shown to be relatively maintainable and easy to update.
But it still in my opinion has some drawbacks:
- first, the way those events were typed was hard to read. The types of those …

Be more explicit with RxPlayer's event types

---

demo/full/index.html
demo/full/scripts/controllers/Main.jsx
demo/full/scripts/modules/player/index.js
scripts/deploy_new_demo
scripts/generate_full_demo.js
scripts/update_gh-pages_demo
sonar-project.properties
webpack-demo.config.js

This commit tries to simplify the building phase of the demo, especially now that we'll be more and more dependant on using external RxPlayer tools in it.
Previously, the demo code was separated into two big files:
- the RxPlayer "lib" file as `lib.js`
- the demo file as `bundle.js`
Both of them were then included in the demo's `index.html` and `bundle.js` relied on the RxPlayer being accessible through `window.RxPlayer`.
This worked perfectly but there are multiple drawbacks here:
- Going through `window.RxPlayer` corresponds to the legacy way of depending on the RxPlayer. We advise people to rely on usual ES6 `import` statements everywhere else.
- In this mode, we cannot rely on features such as tree-shaking.
- In this mode, we cannot access to the RxPlayer's tools as they are not …

demo: integrate RxPlayer directly in the demo bundle

---

src/compat/eme/custom_media_keys/webkit_media_keys.ts

Until now, when using WebKitMediaKeys for deciphering content, we did not authorize to create a ponyfill media keys session without any server certificate. In that case, the RxPlayer was throwing an error.
We realized that we only need the server certificate when using fairplay CDM.
Now, the ponyfill session can be created without server certificate. The RxPlayer will throw an error if trying to create a native webkit session without a server certificate with fairplay drm.

No need for server certificate when not using fairplay on WebKitMediaKeys

---

demo/full/scripts/controllers/knobs/VideoTrack.jsx

Until now, on video track list on RxPlayer's demo, the selected choice was always the wrong one (one upper) when the selected track index was upper than 1.
For example, if you selected the first choice, it was the first one selected. But when if you selected the third, it will be the second one selected, etc.
The index assignment operation in the demo code was wrong because it didn't take into account the first index to be associated to "no track" for the user. And the minimal value was still 1.
Now, the bug does not exist anymore.

Fixed VideoTrack demo index being limited to 1 (first choice)

---

src/custom_source_buffers/text/html/html_text_source_buffer.ts
src/custom_source_buffers/text/html/text_track_cues_store.ts
src/parsers/texttracks/ttml/html/apply_origin.ts
src/parsers/texttracks/ttml/html/create_element.ts

Previously, the RxPlayer didn't consider cases where multiple cues, each with their own temporalities, could be displayed at overlapping times.
It only chose one single cue for a given time (which might contain multiple subtitles).
However, having multiple cues at overlapping times happen to be a frequent occurence when dealing with closed captions.
The gist of this commit is not very complicated: functions and methods that were previously given a single HTML element are now given an array of HTML elements.
However, just displaying the multiple elements as is on the screen led to positionning issues when mutiple cues were displayed at the same time: the first cue "pushed" the other cues below it.
Setting the corresponding cues' position to `absolute` instead of `relative` appears to fix …

text/ttml: allow multiple cues to be displayed at the same time

---

src/parsers/manifest/dash/parse_adaptation_sets.ts
tests/contents/DASH_static_SegmentBase/multi_codecs.js
tests/contents/DASH_static_SegmentTimeline/media/multi-AdaptationSets.mpd
tests/integration/scenarios/dash_multi-track.js

The previous code used several ways to settle between multiple AdaptationSets when there is a choice that need to be done.
In order:
1. One that is supported by the current device
2. One that corresponds to the user's preference
3. If we're talking about the video only, the one having a "Role" set to "main".
4. Based on the `selectionPriority` attribute
5. Based on the order they are in the MPD
This commit changes two things:
1. the Role" set to "main" (step 3), is now considered for any type of AdaptationSets not just for video.
The DASH-IF IOP were a little unclear to me on that point (and it was the reason why this was not done at first), but that seems to be both a sane default and what other players are doing.
2. between multiple AdaptationSets having a "main" Role, the order in the …

Use the main "Role" to decide between multiple AdaptationSets

---

src/parsers/texttracks/ttml/html/create_element.ts
src/parsers/texttracks/ttml/html/parse_ttml_to_div.ts

No ttml default style seems to be defined in the ttml spec. We choose then that the cue may display in the clearer and cleaner possible way. We now consider that, if no style is declared into the file, we should apply a default region style :
centred text
bottom-fixed text
/!\ If no styles are defined for regions, but other styles are, we decide not to apply the default region style. Indeed, we consider the style to have been defined on purpose, and we may interfere with the overall look of the cue if we apply a different style.
As no default style seems to be defined in the ttml spec, we choose to apply the default one if there are no declared style in the final cue, as it may not interfere with any declared one.
Moreover, we now set a white text color by default.

Apply default style to TTML if not encountered

---

doc/api/local_manifest_v0.1.md
src/parsers/manifest/local/parse_local_manifest.ts
src/parsers/manifest/local/representation_index.ts
src/parsers/manifest/local/types.ts
src/parsers/manifest/types.ts

Note: this PR is based on the #818 PR
This PR creates a new version of the LocalManifest format (which allows to play downloaded contents with the RxPlayer).
This new version has the following main goals:
- the maximum position and duration advertised by the RxPlayer is now the maximum reachable position in the fully-loaded content.
Same thing for the minimum position (the minimum reachable position).
Previously, the duration and maximum position were the maximum position of the first contiguous range of the currently loaded
content.
The reason for the change is that has now been decided that it is the role of the downloading tool, not of the player, to advertise
which segments have effectively been downloaded.
To allow for this new behavior:
1. Two properties have been added to a …

 local-manifest: create v0.2 of the local-manifest 

---

src/config.ts
src/core/abr/network_analyzer.ts
src/core/abr/representation_estimator.ts
src/core/api/clock.ts
src/core/api/public_api.ts
src/core/init/create_stream_clock.ts
src/core/init/get_discontinuities.ts
src/core/init/initialize_media_source.ts
src/core/init/types.ts
src/core/stream/events_generators.ts
src/core/stream/orchestrator/stream_orchestrator.ts
src/core/stream/period/create_empty_adaptation_stream.ts
src/core/stream/period/get_adaptation_switch_strategy.ts
src/core/stream/period/period_stream.ts
src/core/stream/representation/append_segment_to_source_buffer.ts
src/core/stream/representation/force_garbage_collection.ts
src/core/stream/representation/get_segment_priority.ts
src/core/stream/representation/get_wanted_range.ts
src/core/stream/representation/push_init_segment.ts
src/core/stream/representation/push_media_segment.ts
src/core/stream/representation/representation_stream.ts
src/core/stream/types.ts

This PR fix multiple things around the clock and Adaptation switching.
The need for it came to me while doing a review for #806. It also seems to fix issues we had with some ad-switching streams.
Basically, three different things are done here:
1. rename `currentTime` to `position`
I renamed the `currentTime` property from a clock tick to `position`, as the old name made believe that this time was always up-to-date (current) whereas it is very linked to the time the tick was started at (which can be different from the time when it is used)
2. add `getCurrentTime` to a clock tick to obtain a more precize position
I added the `getCurrentTime` function to the clock's ticks, which allows to ask for the real current position at any time
3. Refacto Adaptation switch strategy
We now uses the new …

Adaptation Switch Changes

---

doc/architecture/files.md
tests/conformance/hdcp_policy_check.html
tests/conformance/media_key_system_access.html

This is a first try at the implementation of "conformance tests" which allows to quickly test browser API support in various environments (devices and browser).
I added the `conformance` sub-directory in `tests`, which for now contains two HTML files:
- `media_key_system_access.html`: to quickly check which CDM is available on the platform and which configuration is accepted.
- `hdcp_policy_check.html`: to quickly check if the `MediaKeys.getStatusForPolicy` is defined and to check if it can be used to detect in advance which minimum HDCP version is supported under the current conditions.
The goal for now with those files is that they can be used as templates we can quickly update to check the support of various features without the need to run and deploy a whole RxPlayer build.
I chose to …

[Proposal] Add "conformance tests"

---

doc/api/loadVideo_options.md
src/config.ts
src/core/api/__tests__/option_parsers.test.ts
src/core/api/option_parsers.ts
src/core/api/public_api.ts
src/core/init/initialize_media_source.ts
src/core/segment_buffers/implementations/audio_video/audio_video_segment_buffer.ts
src/core/segment_buffers/implementations/types.ts
src/core/stream/adaptation/adaptation_stream.ts
src/core/stream/period/get_adaptation_switch_strategy.ts
src/core/stream/period/period_stream.ts
src/core/stream/types.ts
src/utils/__tests__/are_codecs_compatible.test.ts
src/utils/are_codecs_compatible.ts

This merge request refer to [#801 ](https://github.com/canalplus/rx-player/issues/801)
Basically, it allows you through an entry on the  `loadVideo` method API,  inside `transportOptions` to specify a `string` (for now) on `audioTrackSwitchingMode` property to specify a special strategy concerning the push of audio segment inside the source buffer in order to whether adopt a smooth transition or whether to specify a more direct transition by flushing the current buffer in order to let the new segment take place quicker.
- `smooth`: This is the default behavior, it allows you to switch "smoothly" to the wanted audio adaptation, in some cases the switch can take up to 2 sec.
- `flush`: By using `flush`, we will take care of flushing the audio source buffer by performing a very small seek in …

audioTrackSwitchingMode api on loadVideo

---

src/core/init/create_eme_manager.ts

Since extracting PSSH to emit them without going through the usual
"encrypted" events, we do not send the `MEDIA_IS_ENCRYPTED_ERROR` error
when an encrypted content is played without a `keySystems` `loadVideo`
option.
This commit fixes that.

init: re-throw `MEDIA_IS_ENCRYPTED_ERROR` when a pssh is found

---

src/core/init/initialize_media_source.ts

EME-related events (only EME-related `warning` events and possibly `decipherabilityUpdate` events) were sent two times in a row because we forgot to ignore the items emitted by one of the Observable subscribed in `initialize_media_source.ts`.
As another Observable in that file already emitted EME-related events to the API, each of those would be sent twice.
Thankfully that's the only bug here. The EMEManager being properly shared, the real EME APIs are only called once and only the resulting events emitted to the API (which is only used to trigger events for the application) is sent twice.

eme/api: stop sending eme-related events twice

---

src/core/eme/eme_manager.ts
src/core/eme/types.ts

The documentation for the `keySystems[].serverCertificate` option clearly states that it can only be set to some binary data or `undefined` (or just... not be defined, which is not exactly the same thing as `undefined` :p).
But we found out that some applications preferred to set it to `null` instead!
When setting it to `null`, we still call the `setServerCertificate` API but with `null`, which can have various behaviors.
In the tested cases, it fails.
This is not very problematic as this API is only here as an optimization measure anyway. When it fails, we just ignore it and go on.
But since the `v3.22.0`, an error at the `setServerCertificate` step means that we will most likely re-create a MediaKeys instance on the next `loadVideo` with a `keySystems` option set, because we cannot know …

eme: do not set any server certificate if the option is set to `null`

---

src/core/init/types.ts
src/core/stream/adaptation/adaptation_stream.ts
src/core/stream/events_generators.ts
src/core/stream/orchestrator/are_streams_complete.ts
src/core/stream/orchestrator/stream_orchestrator.ts
src/core/stream/period/create_empty_adaptation_stream.ts
src/core/stream/representation/representation_stream.ts
src/core/stream/types.ts

The `RepresentationStream` previously sent ambiguous events such as `"active-stream"` and `"full-stream"` which in effect were used to know if the `RepresentationStream` was still downloading segments, to for example allow a clever pre-loading of the next Period when the previous one did not rely on network resources anymore.
The notion of an "active" and "full" Stream is ambiguous as even a "full" stream could still be pushing already-loaded segments.
I thus chose to rename the "active-stream" event to a "downloading-segments" event and the "full-stream" event to a `"download-finished"` event.

stream: change wording of events about "active" and "full" stream

---

src/manifest/__tests__/period.test.ts
src/manifest/period.ts

Previously, when a Manifest contained audio and video tracks but none for a given type were supported (e.g. no supported audio tracks but supported video tracks), we failed with a `MANIFEST_PARSE_ERROR` error.
Today in the same situation, the player goes on and just play the other type of media (the one that is supported!).
This new behavior was not really wanted but was a side-effect of how we now treat Representations in unsupported codecs. Where before we filtered them out, now we keep them, but anounce that their codec is not supported currently. This broke the logic throwing the `MANIFEST_PARSE_ERROR` error.
Wanting one of the other behavior both make sense to me, but I think the previous one may be the right default one: If a content contains both audio and video, we generally want …

manifest: throw MANIFEST_PARSE_ERROR again on no supported codec

---

tests/conformance/initial_seek_after_loaded_metadata.html
tests/conformance/initial_seek_after_segment_push.html

While debugging the rx-player on a video game console (it has the number 4 in its name, no, no 6 before it, though that would be nice to also support those) we noticed that the rx-player did not play any live content.
But hey, it just works on PC, so we can just say that this is the console fault and we're good, right?
Sadly no, they checkmated us by putting us in front of dash.js which does play live contents on it.
After some investigations, we noticed that the main difference between our player and dash.js here was the moment at which the seek to the initial position is performed:
1. The RxPlayer does it as soon as it can: when the "loadedmetadata" event is received.
2. dash.js does it late but still soon enough: just after the first media segments have been pushed.
---
We noticed that …

tests: add conformance tests relative to the initial seek

---

doc/api/player_options.md
src/compat/__tests__/browser_version.test.ts
src/compat/__tests__/can_rely_on_video_visibility_and_size.test.ts
src/compat/browser_version.ts
src/compat/can_rely_on_video_visibility_and_size.ts
src/core/api/public_api.ts

On Firefox (version >= 67) :
- The PIP feature exists but can be disabled by default according to the OS and the channel used for updating / getting Firefox binaries.
- There is no API to know if the Picture-in-picture (PIP) is enabled
- There is no API to get the width of the PIP window
If we want to know the video window size, we can't rely on video element size attributes, that may not reflect the real video size when PIP is enabled. Also, when we want to know if the video window is visible, we can't rely on document hiddenness attributes, as the video may be visible, through the PIP window.
--------------
Thus, using `throttleVideoBitrateWhenHidden`, `throttleVideoBitrate` options may cause video bandwidth falls when the PIP is enabled. It means that even if the video window is …

No video bitrate throttling when video is hidden or video size changes, on Firefox (version >= 67)

---

src/compat/eme/index.ts
src/compat/eme/load_session.ts
src/compat/index.ts
src/core/eme/create_session.ts

During our test on some set-top boxes, we found out a race condition in some old versions of Chromium/Chrome/CEF where the `keyStatuses` property was not properly populated right after we get the answer from a `mediaKeySession.load` call.
This made us believe that the MediaKeySession that was persisted did not yet have any key stored, which is today a legitimate case, and consequently the RxPlayer would close that MediaKeySession and re-create a new one instead.
We found out that waiting a small delay, even 0 millisecond (through the `setTimeout` native function), was enough to have the `keyStatuses` property right in that case (Note: scheduling a microtask was not enough however).
The resolution proposed in this commit is that, everytime the `keyStatuses` property is empty, we should …

compat/eme: wait a small delay after loading session in some conditions

---

src/utils/string_parsing.ts

use TextEncoder and TextDecoder when available

---

src/compat/eme/generate_key_request.ts
src/core/eme/__tests__/__global__/get_license.test.ts
src/core/eme/__tests__/__global__/init_data.test.ts
src/core/eme/__tests__/__global__/utils.ts
src/core/eme/__tests__/clean_old_loaded_sessions.test.ts
src/core/eme/__tests__/init_media_keys.test.ts
src/core/eme/attach_media_keys.ts
src/core/eme/check_key_statuses.ts
src/core/eme/clean_old_loaded_sessions.ts
src/core/eme/create_session.ts
src/core/eme/eme_manager.ts
src/core/eme/get_media_keys.ts
src/core/eme/get_session.ts
src/core/eme/init_media_keys.ts
src/core/eme/session_events_listener.ts
src/core/eme/types.ts
src/core/eme/utils/init_data_store.ts
src/core/eme/utils/loaded_sessions_store.ts
src/core/eme/utils/persistent_sessions_store.ts
src/core/init/initialize_media_source.ts

While working on several big modifications of the `EMEManager` code, I saw several issues which made the code difficult to update:
1. Most of all, a good chunk of the functions there wanted the whole world in argument.
For example, `getSession` (which either create or retrieve an existing `MediaKeySession`) was given in argument an object containing the `MediaKeySystemAccess`, the `MediaKeys` and every `keySystems` options despite not needing any of those.
The reason why we communicated all that is because it was easier to just define and pass around an object respecting the `IMediaKeysInfo` interface than to declare specific arguments for each function.
This didn't create any real problem until now, but I recently encountered a relatively big downside of that strategy: 
In my case, I …

EME: small EMEManager adjustements

---

src/core/api/clock.ts

At each clock tick, log media timings (various infos extracted from media element).
This can be needed for debugging purposes.

Log media timings at each clock tick

---

src/core/segment_buffers/implementations/text/html/html_text_segment_buffer.ts
src/core/segment_buffers/implementations/text/html/index.ts
src/core/segment_buffers/implementations/text/native/index.ts
src/core/segment_buffers/implementations/text/native/native_text_segment_buffer.ts

This PR fixes a regression brought in v3.22.0 where text track segments would be loaded in a loop when in the native `textTrackMode` (they would still be displayed at the right time, the issue just being a lot of segment requests).
_Thankfully most (if not all) applications use the HTML textTrackMode.
As we do not test the native mode before release normally, this issue was not spotted sooner._
The issue is due to a discrepancy between the format of the text track data parsed by `transports` and the one accepted by the
`NativeTextSegmentBuffer`: the latter expected a `timescale` property which was not communicated by the former (as the `timescale` is always assumed to be equal to `1` since the last release).
This was not catched by TypeScript because there's some `any` type between the …

Avoid loading segments in a loop when in "native" textTrackMode

---

doc/api/loadVideo_options.md
src/config.ts
src/core/api/__tests__/option_utils.test.ts
src/core/api/option_utils.ts
src/core/api/public_api.ts
src/core/init/initialize_media_source.ts
src/core/segment_buffers/implementations/types.ts
src/core/stream/adaptation/adaptation_stream.ts
src/core/stream/period/get_adaptation_switch_strategy.ts
src/core/stream/period/period_stream.ts

At the time of v3.0.0, proper multi-codec handling was not integrated and as such we never really asked ourselves the question of what to do when we go from an audio and/or video in a codec A to an audio and/or video in a _incompatible_ codec B.
Thankfully, the non-standard yet `SourceBuffer.changeType` API got implemented at least in Chrome and Firefox, allowing to seamlessly switch between codecs on the same SourceBuffer.
But this API is not implemented everywhere and even on targets where it is, its effectiveness seems to vary.
As such, we still have to find a solution for those other targets so they can play multi-codecs content reliably without hacks.
The obvious solution would be to just create a new SourceBuffer on those targets, which requires to open a new MediaSource (what is …

api: add `onCodecSwitch` option to loadVideo to reload on codec switch

---

src/config.ts
src/core/init/initialize_media_source.ts
src/core/stream/adaptation/adaptation_stream.ts
src/core/stream/events_generators.ts
src/core/stream/orchestrator/stream_orchestrator.ts
src/core/stream/period/period_stream.ts
src/core/stream/types.ts
src/core/stream/utils.ts

In some cases after switching the current track or bitrate, the RxPlayer could be led to go into the `"RELOADING"` state, which corresponds to visually a black screen (with nothing audible) before restarting playback.
We could want to seek back some milliseconds when doing that.
For example, when switching the current audio track, it might make sense to restart some time before, so the beginning of the sentence can be heard again with the new track - which might be in another language.
Before, we were seeking back at the last position emitted by the clock, which can be anywhere between the current position and 1 second before.
This commit allows to seek back some hundreds of milliseconds configured in `src/config.ts`. That delay depends on whether the track or the bitrate is switched:
- …

Seek back a consistent amount of time when switching track/bitrate

---

src/core/stream/representation/check_for_discontinuity.ts

This PR regroups 3 fixes related to discontinuity management (fixes on a future releases).
---
1. `Skip discontinuities at the end of Periods even when we are in it`
This commit adds a condition to skip discontinuities we previously ignored.
Let's consider the following situation:
```
= segment
| Period boundary
^ current position
- current checked range for segment download
|=======   --|====            |
Period 1  ^   Period 2
```
Here we're at a position inside a "hole" at the end of the given Period. Now let's consider that we found out that there's no segment to load there.
In that situation, we previously just checked if there was a discontinuity anounced in the Manifest. If not, we did nothing.
But we can also reliably seek to the next Period in any case, when the Period is known …

Skip discontinuities at the end of Periods even when we are in it

---

src/core/eme/check_key_statuses.ts
src/core/eme/types.ts
src/manifest/manifest.ts

Since at least the v3.21.1 release, we had an issue that appeared when blacklisting Representation based on the keyID (e.g. when a `keystatuseschange` event indicates us that we are "output-restricted and when fallbacking is enabled through the related `keySystems` options).
This issue prevented from fallbacking, it just threw an Error message along the lines of:
`TypeError: DataView: expected ArrayBuffer, got Uint8Array`
The root cause was linked to typing issues (we will consequently cleverly redirect all wrong-doing to typescript, not our fault at all here :p) where an Uint8Array was considered to be a valid ArrayBuffer.
At some point, a `new DataView(whatIThoughtToBeAnArrayBufferWhichIsInRealityAUint8Array)` was done, leading to the aforementioned error.
The fix here is to now …

Fix Uint8Array believed to be an ArrayBuffer when blacklisting based on key-id

---

src/compat/eme/custom_media_keys/index.ts

While testing playback of encrypted contents in an HTTP page on Edge (on Edge and Chrome, EME APIs are only available on an HTTPS page), I noticed that the error message was not explicit at all:
`"No isTypeSupported on MediaKeys"`.
This is because we were in a specific case, where the RxPlayer tried to ponyfill the `requestMediaKeySystemAccess` API with another since-deprecated API, `MediaKeys.isTypeSupported`.
This commit now checks if the `MediaKeys.isTypeSupported` API exists before fallbacking to that ponyfill, and no longer throw that error.
Now when neither the `requestMediaKeySystemAccess` nor the `MediaKeys.isTypeSupported` API exist, the following error is thrown instead when wanting to play encrypted contents:
`"This browser seems to be unable to play encrypted contents …

compat: throw a better error when no EME API is found

---

src/core/api/clock.ts

The clock, an internal RxPlayer mechanism running the main player logic on different playback events (seek, loading, playback rate change, or at a regular interval if none of those happen) was listening to the `"progress"` event from the HTMLMediaElement.
This appears to be unnecessary, as `progress` doesn't seem to be an important milestone enough to justify re-checking everything.
What this event is for on contents with a MediaSource is a little blurry but it seems to be linked to when a new chunk is added.
On some CPU-constrained devices, each tick have been observed to take between 5 and 30 ms. Progress events being one of the events the most often emitted, this could consume in the hundred of milliseconds before the content loads on those devices.

Remove "progress" event from being listened by the clock

---

src/core/eme/__tests__/__global__/server_certificate.test.ts
src/core/eme/eme_manager.ts

This is both a performance-related improvement and a fix of a small issue (which may have had no possible impact).
___
For the performance improvement:
Previously we awaited for the first encrypted event before calling the `setServerCertificate` API. This may have been to avoid calling unnecessary APIs when the content is not really encrypted (or perhaps even not YET encrypted at this point).
Doing this may have been a nice improvement for when a `setServerCertificate` was done each time a `serverCertificate` was given as an option, but we now have an optimization which avoid re-doing a `setServerCertificate` when we KNOW that we're already using that server certificate.
Now, it can also be looked the other way: it penalizes the charging time by waiting for the initialization data first. …

drm: perform setServerCertificate before init data has been received

---

src/core/stream/orchestrator/stream_orchestrator.ts

The `BufferGarbageCollector` is an observable which regularly clean the media buffers based on the distance between the current position and the media data.
Consequently, it needs to be given the current playing position to work properly.
To that effect the `position` property of each clock tick was given to it. This is good, but we forgot to add the `wantedTimeOffest` to it if it exists.
The `wantedTimeOffest` property was added as a workaround for cases where the media element's position (what is actually reflected by the `position` property) is different from the wanted position.
This only happens for now when first loading the content, as there the seek to the initial position cannot be performed until the `loadedmetadata` event has been received.
The true impact of this error is …

Add the clock's wantedTimeOffest to the BufferGarbageCollector's

---

src/core/stream/representation/downloading_queue.ts
src/core/stream/representation/representation_stream.ts
tests/integration/scenarios/initial_playback.js
tests/integration/scenarios/loadVideo_options.js
tests/integration/utils/launch_tests_for_content.js
tests/utils/waitForPlayerState.js

In the previous logic, we always awaited the initialization segment request before loading any media segment.
There was two main reasons why:
1. It was difficult to write the code running them in parallel, due to some edge cases
2. It may not save any time in most real use-cases, as most contents we play are encrypted and we rely on the initialization segment to take the encryption initialization data.
Running their requests in parallel of other requests would only postpone their responses, which might in the end lead to a slower loading time.
For 1/, nothing changed much but the second inconvenient may disappear now that we're considering relying only on the encryption initialization data found in a Manifest file if found there (and if not, which would arguably be the minority case, we …

Download Init segment in parralel of the first media segment

---

src/core/api/public_api.ts
src/core/init/initialize_media_source.ts
src/core/init/manifest_update_scheduler.ts

The previous RxPlayer logic waited for a possible previous content to be "cleaned-up" (its buffers removed, previous encryption sessions closed if the right options are set etc.) before considering a new content.
We found that in some target, that clean-up can take time.
Depending on the options set and the content previously played (e.g. with multiple keys and options to close all sessions) we noticed up to 500ms only to clean-up the previous content.
This PR attempts to optimize that time by fetching the Manifest early on, even before stopping the previous content.
Sadly this implies to move the `ManifestFetcher` from the `Init` to the `API`. It is kind of odd to see it there.
Because there was no reason to now let the `SegmentFetcherCreator` in the `Init` I moved it to the `API` as …

improve content switching performance by loading the Manifest ASAP

---

src/config.ts
src/parsers/manifest/dash/indexes/is_period_fulfilled.ts
src/parsers/manifest/dash/indexes/template.ts
src/parsers/manifest/dash/indexes/timeline/timeline_representation_index.ts

Numbers in JavaScript are encoded as double-precision floating-point numbers (64-bit encoding) specified by the IEEE 754 standard. One of the effects of this encoding is that these numbers are prone to rounding errors
The result of such unprecise representations is that some JS calculations may give bad results. As math operations are done frequently in the RxPlayer, on decimal numbers, there are various places in the code where the logic could go wrong. We've already introduced rounding error safeguards for some operations, but it seems that it may not be sufficient everywhere...
For example :
The isFinished function of the Timeline index checks if the last chunk of the timeline ends before the end of the period.
We've encountered a case in a DASH stream where the computed period end was …

Take into account rounding errors for indexes computing and comparisons

---

src/core/stream/representation/downloading_queue.ts
src/core/stream/representation/representation_stream.ts

This commit fixes memory leaks present in the RepresentationStream since a6b6f64f39f5a4fcb4509177ee3172415520ce85.
Note that this commit is not yet part of a release (thankfully!).
The reasons for those leaks are linked to how we implemented parallel download of the initialization and media segments while still pushing the former before the latter.
We basically created `ReplaySubjects` containing data related to the initialization segment and listened to that ReplaySubject before parsing or pushing any media segment (to be sure this was done only once the corresponding init segment data was known).
However, we didn't stop listening to either of those `ReplaySubject`s after they emitted once, thus leaking memory each time a new media segment is loaded/parsed (the returned observable will …

fix memory leak in RepresentationStream

---

src/parsers/manifest/dash/node_parsers/AdaptationSet.ts
src/parsers/manifest/dash/parse_adaptation_sets.ts

Hello,
We have manifests where multiple accessibility tags are defined to signal the same accessibility feature (in this case audio description) in order to support a wider range of players.
```
<Accessibility schemeIdUri="urn:tva:metadata:cs:AudioPurposeCS:2007" value="1"/>
<Accessibility schemeIdUri="urn:mpeg:dash:role:2011" value="description"/>
```
As you only consider a singe `Accessibility` descriptor, this change opens up for the possibility to use multiple ones. It also extends the definition of `isVisuallyImpaired` to consider also the DASH-IF 4.3 specification of audio description. One could also easily extend the other `is{Accessibility}` functions to consider both specs, but I started with just one.
Let me know what you think!

Consider multiple accessibility descriptors

---

src/core/init/initial_seek_and_play.ts

The RxPlayer autoPlay option determines the way the player will handle the playback just after it has started loading content.
If it is enabled, the playback will start after the JS has called the media element play function. If not, the player is supposed to stay paused. However, the HTML media element has an autoplay attribute that, if enabled, will start playback ASAP. It means that if the autoPlay is set to false in the RxPlayer, playback may start anyway if the autoplay is enabled on the video tag.
This PR proposes to warn the user about the fact that media may play, even if the autoPlay is set to false, if the autoplay is enabled on the media element.

[Proposal] Warn user when autoplay is enabled on the media element but not on RxPlayer

---

src/core/init/create_media_source.ts
src/core/init/load_on_media_source.ts

Tizen seems to have issues with setting a very high value as a duration due to that value overflowing when they perform time conversions.
As a compromise, it's not that much to sacrifice the maximum position we can seek to in a live content at 2^32 (which is much lower than what we could actually put it at, but might save us from other compatibility issues and is what the shaka-player is doing).
With an exception for those rare cases where the maximum position goes close to or over 2^32 (which should not normally happen, at least not until 2096, but we never know, some weird contents should exist somewhere).
In this last scenario, we set it to the current maximum position + 1 year, which should still be pretty safe (still, we never know what future usages will bring us)!
Also, I decided …

set a much lower duration by default for live contents

---

src/config.ts
src/core/eme/utils/close_session.ts
src/core/eme/utils/loaded_sessions_store.ts

This PR fixes a leak we only observed for now on some set-top-boxes where the call to `generateRequest` is very long (around 1 second).
This leak concerned MediaKeySessions, which were all closed when stopping a content due to the `closeSessionsOnStop` `keySystems` property being set to `true`.
Here, when loading then stopping multiple contents rapidly, we could observe some MediaKeySessions failing to be closed and thus can be kept "alive" by the user-agent despite being completely removed from the RxPlayer's point of view.
After investigation, it seems that we encountered the following case in the [EME spec for the `close` method](https://www.w3.org/TR/encrypted-media/#dom-mediakeysession-close):
`If this object's callable value is false, return a promise rejected with an …

EME: Fix possible leaks of MediaKeySessions if closed at the wrong time

---

src/experimental/tools/mediaCapabilitiesProber/api/probeMediaConfiguration.ts

For some reasons on Safari desktop environment this following line can break because the `error` variable is set to `undefined`.
```js
log.debug(error.message === undefined ? error : error.message);
```
This is an outcast behaviour cause on Webkit browser it did not happens.

DetectionHDCP can break cause of a miss interpreted error handling

---

doc/api/index.md
package.json

Try to make the Doc API more practical to use by adding a small anchor to be able to access pages that are highly used by adding a category "Quick links" inside the RxPlayer API page.

add quick links inside the RxPlayer API Page

---

src/compat/eme/load_session.ts
src/config.ts

After loading a persistent MediaKeySession, the RxPlayer needs to ensure that its keys still allow to decrypt a content.
To do so, we check on its `keyStatuses` property.
However, on some browsers (detected on set-top-boxes for example), the `keyStatuses` property is empty for some time after the loading operation is done, and is only filled after an impossible to predict delay.
This PR will now allow to wait up to 100ms after a session is loaded (if its `keyStatuses` property is empty) before that session is actually used.
Sadly, this also mean that that delay is incurred for when the session legitimately has no key linked to it. This last problem can be attenuated by only adding session that we know have at least one key attached to them to the `PersistentSessionsStore`.
This second …

eme: wait at most 100ms after a session is loaded to check on its keyStatuses

---

src/compat/__tests__/is_seeking_approximate.test.ts
src/compat/browser_detection.ts
src/compat/is_seeking_approximate.ts
src/config.ts
src/core/init/stall_avoider.ts

This commit fixes a problematic behavior on Tizen (mostly Samsung TVs) where we could have an infinite seeking loop.
This issue is due to the fact that after seeking to a specific position Tizen may actually seek to the closest intra video frame as a performance tweak.
This is an unexpected behavior (I would argue that it goes against the HTML5 specification) which may actually lead to a huge problem that is difficult to work-around.
---
Let's say that the RxPlayer seek at at a position `T1`.
After loading the first video media segment, samsung sees that the first intra frame is actually at a position `T2`, which is inferior to `T1`.
```
segment
video |--------------------|====|======|
T2   T1
current position => T1
```
In that condition, the browser seeks back to T2.
Now let's imagine we …

Avoid seeking over discontinuities when the browser seeks back

---

src/core/eme/__tests__/init_media_keys.test.ts
src/core/eme/get_drm_system_id.ts
src/core/eme/init_media_keys.ts
src/core/eme/types.ts
src/core/init/initialize_media_source.ts
src/core/stream/adaptation/adaptation_stream.ts
src/core/stream/representation/representation_stream.ts

This PR is based on #911 and allows a performance optimization where the license request for encrypted contents can be performed sooner.
The idea is to:
- determine, from the key system currently used, which encryption initialization data is needed based on this data's "systemId"
- if the Manifest contains that data directly embedded within it, send only that data as soon as the content in question is considered for download (instead of waiting for the initialization segment to be loaded and parsed as we did before) and do not send other encryption data for that same content
- if the Manifest does not contain that data - or if we couldn't determine the system data - just send all encryption data like before (from both the Manifest and the initialization segment, implying that both …

Only use concerned encryption systemId when found in the Manifest

---

src/core/eme/__tests__/__global__/utils.ts
src/core/eme/check_key_statuses.ts
src/core/eme/eme_manager.ts
src/core/eme/session_events_listener.ts
src/core/eme/types.ts
src/core/eme/utils/init_data_store.ts
src/core/eme/utils/loaded_sessions_store.ts
src/core/init/initialize_media_source.ts
src/core/init/types.ts
src/manifest/index.ts
src/manifest/representation.ts

resolves #863 
This PR implements a `singleLicensePer` option, which allows an application to tell the RxPlayer that the current content only has a single license for the whole content, even when it has multiple keys associated to different tracks or qualities.
The RxPlayer will then be able to perform a single license request and, if the right options are set, to fallback from non-decryptable contents, which will be both:
1. keys which have the wrong key-status ("output-restricted" if `fallbackOn.keyOutputRestricted` is set and "internal-error" if `fallbackOn.keyInternalError` is set).
2. keys which were not included in that license. Those will be fallbacked from, without needing to set any API.
The idea is also to be able to make evolutions to that API to implement for example a single …

Single license per content implementation

---

src/core/init/initialize_media_source.ts
src/core/stream/adaptation/adaptation_stream.ts
src/core/stream/adaptation/create_representation_estimator.ts
src/core/stream/orchestrator/get_blacklisted_ranges.ts
src/core/stream/orchestrator/stream_orchestrator.ts
src/manifest/adaptation.ts
src/manifest/manifest.ts
src/manifest/period.ts

This PR is based on the multiple-keys-per-license commits (in #904) and add on top of it a new behavior.
Representations which have their key-id added to one of the `MediaKeyStatusMap` linked to the current content and which are not fallbacked from, will now have their `decipherable` property updated to `true` - even if it was set to `false` before (and thus even if we had fallbacked from it in the past).
This development was made a lot easier by the work done to support the `singleLicensePer` option (#904) with now the concept of "whitelisted key ids", in opposition of the "blacklisted key ids" we fallback from.
When a key id is found to be whitelisted (technically this means currently that its `MediaKeyStatus` is not either: `"internal-error"`, `"output-restricted"` or `"expired"`, the …

Mark decipherable Representations as decipherable even if they were undecipherable before

---

src/core/eme/eme_manager.ts
src/core/stream/adaptation/create_representation_estimator.ts
src/core/stream/orchestrator/stream_orchestrator.ts

We had a bug in our implementation of the `singleLicensePer` API (not yet released, hopefully), where we would not fallback from a quality linked to a key id not found in the licence, only if that key id was the first encountered.
This is because the check we (I) added to do that only did it on subsequent key ids, not the first one that triggered the license-fetching process.
I tried to add a fix but it is not as simple as it looks, because if we're doing that in a `singleLicensePer`: "content"` mode, why not
always (as it would make sense to always fallback when the wanted key id is not found in the corresponding license).
However I prefer not to do that due to both not break the API and the possible compatibilities issues as explained in the code.
So I was left doing it only if …

DRM: In a singleLicensePer content mode, blacklist the first kid if not encountered

---

src/parsers/containers/isobmff/utils.ts

The "emsg" boxes are declined in two versions: 0 and 1.
We support version 0 in the RxPlayer.
This PR fixes the fact that we considered every box to be version 0. It skips parsing and warns when the version is different.

Skip parsing EMSG when version is different from 0

---

src/core/api/track_choice_manager.ts
src/manifest/period.ts

This method was only called by the `TrackChoiceManager` and a recent fix
ultimately led to the `NO_PLAYABLE_REPRESENTATIONS` not being thrown
anymore, as the `TrackChoiceManager` would just ignore tracks for which
all Representations are marked as not decipherable.
This could make sense, but I prefer to postpone such behavior change for
a future release.
This commit re-set the old behavior by just checking the codec support
through the `isSupported` property.

manifest: Rename Period.getPlayableAdaptations to getSupportedAdaptations

---

demo/full/scripts/controllers/ContentList.jsx

A small warning in dev mode from React was appearing on the demo cause of forgotten key props passed to a couple of components.
Added props key when needed!

Add key props when needed.

---

src/transports/utils/parse_text_track.ts

Fixes #945
This fix adds start and end information for plain-text segments of the "dash" and "local" transport types by taking it from the corresponding `segment` object (itself taken from the Manifest).
This information was actually removed in 50768ae094935fabba868c4a50ceaa849cafcc87, and I believed that is was not done on purpose (it may be an oversight).
The absence of that information was provoking an issue where text segments could be loaded in the loop.
---
I copy here the analysis I already wrote in #945:
When parsing those text segments (in src/transports/dash etc.), we omitted to add information about the start and end times at which those segments apply.
When those segments were then pushed to the buffer (in src/core/segment_buffers), it didn't find any start and end time and …

Add segment's time information on parsed plain-text segments

---

src/manifest/update_period_in_place.ts

We've noticed that some stream events from manifests were never emitted, although they are present in the original manifest file.
The reason is that, when the manifest is updated, the stream events in the periods where never replaced.
Typically, even if Event were added in the manifest for a Period, we parsed them but never replaced the old ones.
Now, the stream events are replaced. I don't consider usefull to code a more complex implementation were we would just add the new ones, and "patch" the old ones.

Update stream events when updating the manifest

---

CONTRIBUTING.md
src/core/api/public_api.ts
src/core/fetchers/segment/create_segment_loader.ts
src/core/fetchers/segment/prioritized_segment_fetcher.ts
src/core/fetchers/segment/segment_fetcher.ts
src/core/fetchers/segment/segment_fetcher_creator.ts
src/core/init/initialize_media_source.ts
src/core/init/load_on_media_source.ts
src/core/stream/adaptation/adaptation_stream.ts
src/core/stream/orchestrator/stream_orchestrator.ts
src/core/stream/period/period_stream.ts
src/core/stream/representation/representation_stream.ts
src/transports/dash/add_segment_integrity_checks_to_loader.ts
src/transports/dash/image_pipelines.ts
src/transports/dash/text_parser.ts
src/transports/local/text_parser.ts
src/transports/metaplaylist/pipelines.ts
src/transports/smooth/pipelines.ts
src/transports/types.ts
src/utils/assert.ts

Based on #950
This PR proposes a simplification of types used by the segment parsers by defining a unique segment data type instead of two: one for the init segment and the other for media segments.
As `SegmentBuffers` - on which those segment data will be pushed - are only generic based on a single segment data type, this is not really necessary anyway.
The real reason behind creating two types was to better indicate that text and image Representation had no initialization segment (by setting their type to `null`) but considering that a parsed media segment could theoretically be `null` as well, nothing is lost by using the same type for both.
Being generic over a single type simplify the way we approach segment parsers in my opinion. Now we're thinking: "which type is the parsed segment …

[Proposal] Simplify segment parsers types

---

doc/api/hdr.md
doc/api/index.md
doc/api/manifest.md
doc/api/player_events.md
src/core/api/track_choice_manager.ts
src/manifest/representation.ts
src/manifest/types.ts
src/parsers/manifest/dash/get_hdr_information.ts
src/parsers/manifest/dash/parse_adaptation_sets.ts
src/parsers/manifest/dash/parse_mpd.ts
src/parsers/manifest/dash/parse_periods.ts
src/parsers/manifest/dash/parse_representations.ts
src/parsers/manifest/types.ts

This PR adds two features : 
- HDR track signaling in RxPlayer's manifest : 
If a track is recognized as HDR, a boolean is now present on the representation. For so, the RxPlayer should be aware that the track has characteristics that mean that it is an HDR track:
- high color depth: SDR video codecs uses 8 bits by color for encoding it. HDR allows using 10 or more.
- wide color gamut (facultative): The color gamut is a range of colors. HDR implies that a wider gamut should be used for video.
- HDR gamma (EOTF): it is the transfer function that has the video signal as input and converts it into the linear light output of the display.
- HDR display support :
If a track is recognized as HDR, we may be able to tell to the user that HDR features may be exploited on the current output device. …

HDR Support

---

src/parsers/manifest/dash/indexes/list.ts

`RepresentationIndex`es, which are basically interfaces to get information about segment regardless of the current streaming protocol, have a function called `shouldRefresh`.
This function takes in argument the time range currently considered for download by the player and returns `true` if the `RepresentationIndex` estimates that a new Manifest has more information on the wanted segments and therefore that it should be refreshed.
Used for both DASH and Smooth at first (years ago?), it finally was considered only useful for Smooth contents, as DASH also provide other mechanisms for recurrent MPD updates that we now prefer (most notably the `minimumUpdatePeriod` attribute) over this.
However a logic was still present for `ListRepresentationIndex` - used when a `<SegmentList>` element is …

dash: do not trigger refresh from a ListRepresentationIndex

---

src/core/fetchers/segment/segment_fetcher.ts
src/core/stream/representation/representation_stream.ts
src/manifest/representation.ts
src/manifest/representation_index/types.ts
src/parsers/manifest/dash/parse_representation_index.ts
src/transports/dash/image_pipelines.ts
src/transports/dash/segment_parser.ts
src/transports/dash/text_parser.ts
src/transports/local/segment_parser.ts
src/transports/local/text_parser.ts
src/transports/smooth/pipelines.ts
src/transports/types.ts
tests/contents/DASH_static_SegmentBase/multi_codecs.js

This commit fixes an issue I encoutered while investigating #945 where I noticed that the player loaded two times in a row the same text segment anounced in the tested MPD.
---
The reason is that the RxPlayer has a peculiar behavior when no `SegmentBase`, `SegmentList` nor `SegmentTemplate` element are found to be linked to a given Representation.
In that situation, it creates a `TemplateRepresentationIndex` with both an initialization segment and a media segment linked to that Representation's URL.
For example, let's consider the following AdaptationSet:
```
<AdaptationSet id="2" contentType="text" mimeType="text/vtt"
lang="tlh">
<Role schemeIdUri="urn:mpeg:dash:role:2011" value="caption"/>
<Representation id="nuqneh" bandwidth="0">
<BaseURL>https://retservilo.eo/qapla.vtt</BaseURL> …
```

Do not consider that there is an init segment when only a BaseURL is available

---

doc/api/loadVideo_options.md
src/config.ts
src/core/eme/eme_manager.ts
src/core/eme/get_session.ts
src/core/eme/types.ts

This PR adds a `keySystems[].maxSessionCacheSize` option to configure the maximum number of `MediaKeySession` that can be kept in our cache (the `LoadedSessionStore`) in parallel.
This seems necessary because some platforms do not support more than a very few `MediaKeySession` being kept alive at the same time (e.g. less than 10) whereas other have a much higher limit.
We prefer right now to set a higher limit by default to improve content loading performance (when re-loading an already-loaded content) on PCs.
We initially wanted to add that feature in an earlier release but we postponed it because it was unclear which form that option should take in cases where there were multiple keys per sessions: should we make the number of keys configurable or still keep track of the number of …

DRM: add maxSessionCacheSize option to limit maximum number of stored EME sessions

---

src/manifest/representation_index/types.ts
src/parsers/containers/isobmff/utils.ts
src/parsers/containers/matroska/utils.ts
src/parsers/manifest/dash/indexes/base.ts
src/parsers/manifest/smooth/create_parser.ts
src/parsers/manifest/smooth/representation_index.ts
src/transports/dash/segment_parser.ts
src/transports/dash/text_parser.ts
src/transports/smooth/pipelines.ts

This commit was initially just to rename the BaseRepresentationIndex's `_addSegments` methods to a more clear `initializeIndex` method but I also profited to clean-up comments and improve the logic behind Smooth constructor arguments.

Clean-up BaseRepresentationIndex and SmoothRepresentationIndex code

---

src/core/init/manifest_update_scheduler.ts

Manifest files, in particular for live contents, may need to be refreshed at a regular interval.
The logic behind scheduling Manifest refresh is actually complex.
This is because even if a "normal" refreshing delay is indicated in the Manifest, the RxPlayer might prefer to postpone its update instead because it judges that it is too frequent when compared with the time it takes to parse it.
However, there were no higher limit to this postponment, which could theorically lead to a very high delay before an update\*, and as such to potential long buffering time (this could only happen if Manifest parsing takes a lot of time though, but we could imagine some exceptional conditions where this would be the case or even unrelated reasons, like someone adding a breakpoint when inside the parsing …

Limit the postponment of a Manifest refresh to an acceptable value (regular delay * 6)

---

src/core/stream/orchestrator/stream_orchestrator.ts
src/manifest/manifest.ts
src/parsers/manifest/dash/parse_mpd.ts
src/parsers/manifest/local/parse_local_manifest.ts
src/parsers/manifest/metaplaylist/metaplaylist_parser.ts
src/parsers/manifest/smooth/create_parser.ts
src/parsers/manifest/types.ts

It happens that some live contents have temporarely a last period whose end if defined, and whose manifest are dynamics and need to be updated.
In that case, if we buffer until the end of the period, we would trigger the end of stream. If the RxPlayer plays until the end, then its state will change to ENDED.
It is not what we want, as it should probably be BUFFERING, as the content may be updated with new content, we can't consider it to be ENDED.
Moreover, passing to the ENDED state, and then returning to the PAUSED state without any user action is not a behavior that we want.

Trigger the end of stream only when the last period of the content is known

---

src/config.ts
src/core/init/initialize_media_source.ts
src/core/init/types.ts
src/core/stream/events_generators.ts
src/core/stream/period/get_adaptation_switch_strategy.ts
src/core/stream/period/period_stream.ts
src/core/stream/types.ts

We introduced in a previous release the option [`audioTrackSwitchingMode`](https://github.com/canalplus/rx-player/pull/806/commits/006c0539a19a74b26e768e15da57e80a4d662327) that let the application side decide the kind of behaviour when it comes to switching from an audio track to another.
We decided to allow the end application to decide on this, cause we integrated few devices like PS5, where they experience a long effective switch between audio adaptation (6-7sec).
Previously, the behaviour was either 
- a `seamless` option, this means that we let the browser switch smoothly but could not be immediate.
- a `direct` behaviour, that was more `agressive`, because we decided to perform a complete `reload` that consist of recreating from scratch a MediaSource and pushing the new data on it. …

[audioTrackSwitchingMode] Perform a small seek to flush buffer instead of a reload

---

demo/full/scripts/components/VideoThumbnail.jsx
demo/full/scripts/modules/player/index.js

This is a small demo update based on the `feat/vtl` branch (#647).
In this update, I only ask for a thumbnail after 40 milliseconds, if no other thumbnail was requested since.
Without that timer, I saw too many thumbnail requests when hovering the progress bar with my trackpoint (the red pointer thingie on thinkpads). The previous behavior may even result in more latency before a thumbnail is shown as a lot of requests could be run/aborted in a row, which has its own cost (both in bandwidth and in CPU).
To avoid subtle race conditions I had also to add some more state in the VideoThumbnail component.

VideoThumbnailLoader demo improvements

---

doc/api/plugins.md
src/core/fetchers/utils/try_urls_with_backoff.ts
src/errors/__tests__/network_error.test.ts
src/errors/assertion_error.ts
src/errors/custom_loader_error.ts
src/errors/index.ts
src/errors/network_error.ts
src/transports/dash/segment_loader.ts
src/transports/local/segment_loader.ts
src/transports/smooth/segment_loader.ts
src/transports/utils/call_custom_manifest_loader.ts

Before this commit, it was not possible to indicate that a Manifest or segment request could be retried when using a custom `manifestLoader` or `segmentLoader` (respectively for Manifest requests and segment requests performed through a separate logic).
Consequently, the RxPlayer would always throw on the first error encountered in either two of these APIs.
This was not too bad, as custom loaders could "fallback" to our implementation when it couldn't perform the request, and our implementation does have a more advanced retry management.
Still, those APIs could be more powerful for specific cases where a request can/should be retried through the custom logic.
Consequently, I added two optional properties that can be set on a rejected error (kind of like the `keySystems[].getLicense` API): …

api: add retry configuration to `segmentLoader`/`manifestLoader` APIs

---

README.md

[Codesandbox](codesandbox.io) is nice to create an easy and quick work environment to test and play with a project.
So I've made 3 separates "code sandboxes" that allow the user to play with the player more interactively without the overhead of setting a project from scratch locally and looking for content to play.
- [Playing a clear dash content](https://codesandbox.io/s/rx-player-classic-wc38j)
- [Playing an encrypted dash content](https://codesandbox.io/s/rx-player-drm-g51hb)
- [Playing a metaplaylist content](https://codesandbox.io/s/rx-player-metaplaylist-l0t0d)
More boxes could be added and for now, they are only inside the readme file but I'm open to discussion whether or not to add them elsewhere or just got rid of it.

Adding codesandboxes to play with the api and the project

---

doc/api/loadVideo_options.md

There is a minor typo in the documentation about representationFilter which can lead to some confusion.

doc: fix typo about representationFilter

---

CONTRIBUTING.md
src/core/api/public_api.ts
src/core/fetchers/segment/create_segment_loader.ts
src/core/fetchers/segment/prioritized_segment_fetcher.ts
src/core/fetchers/segment/segment_fetcher.ts
src/core/fetchers/segment/segment_fetcher_creator.ts
src/core/init/initialize_media_source.ts
src/core/init/load_on_media_source.ts
src/core/stream/adaptation/adaptation_stream.ts
src/core/stream/orchestrator/stream_orchestrator.ts
src/core/stream/period/period_stream.ts
src/core/stream/representation/push_media_segment.ts
src/core/stream/representation/representation_stream.ts
src/experimental/tools/VideoThumbnailLoader/get_initialized_source_buffer.ts
src/experimental/tools/VideoThumbnailLoader/push_data.ts
src/experimental/tools/VideoThumbnailLoader/types.ts
src/transports/README.md
src/transports/dash/add_segment_integrity_checks_to_loader.ts
src/transports/dash/image_pipelines.ts
src/transports/dash/segment_parser.ts
src/transports/dash/text_parser.ts
src/transports/local/segment_parser.ts
src/transports/local/text_parser.ts
src/transports/metaplaylist/pipelines.ts
src/transports/smooth/pipelines.ts
src/transports/types.ts
src/utils/assert.ts

Every segment parser in `src/transports`, which allows to parse things like data, encryption metadata and time information from loaded segments according to the current streaming protocol, do so synchronously.
However, those are typed as [possibly asynchronous] Observables.
My guess (this was before my time on the project) is that it was mainly for two reasons:
1. Manifest parsing can be asynchronous (for example to fetch MPD xlinks or the clock) and it follows the same pipeline architecture (a loader and a parser) than segments.
Letting segment parser be asynchronous thus allows to harmonize all resource-fetching code to a similar interface.
2. Theorically, segment parsing could be asynchronous. As far as I can see for now, this could be because of two reasons:
- We need to perform an …

[Proposal] segment parsers now return their result synchronously

---

src/core/api/public_api.ts
tests/contents/DASH_static_SegmentTimeline/index.js
tests/contents/DASH_static_SegmentTimeline/media/multi_period_different_choices.mpd
tests/contents/DASH_static_SegmentTimeline/media/multi_period_same_choices.mpd
tests/contents/DASH_static_SegmentTimeline/multi_period_different_choices.js
tests/contents/DASH_static_SegmentTimeline/multi_period_same_choices.js
tests/contents/DASH_static_SegmentTimeline/urls.js
tests/integration/scenarios/dash_multi_periods.js

While browsing the code for a totally unrelated matter, I noticed that a condition in the private `_priv_triggerAvailableBitratesChangeEvent` method in the API module didn't make much sense.
Basically, we were only sending an event linked to a change in bitrate choices if either:
1. There was no bitrate choice previously (for example, because we just started the content).
2. There was a bitrate choice previously, but it was the exact same choice that we have now.
The second choice doesn't make sense, but the reverse does (if the list of available bitrates changed emit the event, if not don't).
This, plus the fact that I have the bad habit of mixing-up my `if`s conditions sometimes (programing is hard!) led me to believe that this was an unfortunate typo.
Thankfully, this was not the only …

send available{Audio,Video}BitratesChange event for multi-Period contents

---

src/compat/eme/custom_media_keys/webkit_media_keys.ts

We noticed a bug inside the RxPlayer on the FairPlay DRM environment where the [`update()` EME method](https://developer.mozilla.org/en-US/docs/Web/API/MediaKeySession/update) was expecting a strict `Uint8Array` type but sometimes it happens that the application for some reasons provides an [`ArrayBuffer`](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer).
For most of the CDM, it's not a problem, but for FairPlay on Safari, it waits for a strict `UInt8Array`.
In this PR, we are still allowing the `ArrayBuffer` as the rx-player doc was explicit about it:
> In any case, if a license is provided by this function it should be under a BufferSource type (example: an Uint8Array or an ArrayBuffer). …

Cast License in Uint8Array

---

src/parsers/manifest/dash/common/parse_mpd.ts
src/parsers/manifest/dash/common/parse_periods.ts
src/parsers/manifest/dash/node_parser_types.ts
src/parsers/manifest/dash/wasm-parser/rs/events.rs
src/parsers/manifest/dash/wasm-parser/rs/processor/attributes.rs
src/parsers/manifest/dash/wasm-parser/rs/reportable.rs
src/parsers/manifest/dash/wasm-parser/rs/utils.rs
src/parsers/manifest/dash/wasm-parser/ts/generators/EventStream.ts
src/parsers/manifest/dash/wasm-parser/ts/generators/MPD.ts
src/parsers/manifest/dash/wasm-parser/ts/generators/Period.ts
src/parsers/manifest/dash/wasm-parser/ts/types.ts

There was a subtle issue with the WebAssembly DASH parser, which could lead to inexploitable `streamEvent` events (emit when an `<Event>` element encountered in the MPD begin to be "active").
As per the RxPlayer API documentation, `<Event>` elements are sent as an `Element` JavaScript type through the `streamEvent` event, meaning that we have to use the the DOM-related JavaScript APIs (to be able to create that `Element` type).
However, the main API we used, DOMParser, performed validity checks on the given XML.
We initially though that just feeding it the `<Event>` element was OK, it was valid XML after all, but we forgot about XML namespaces!
Namespaces are special attributes and Element names. They are recognized by the inclusion of the ":" character after them. They have to be …

wasm/dash: handle Event namespaces

---

src/config.ts
src/core/segment_buffers/implementations/audio_video/audio_video_segment_buffer.ts
src/core/segment_buffers/implementations/image/image_segment_buffer.ts
src/core/segment_buffers/implementations/text/html/html_text_segment_buffer.ts
src/core/segment_buffers/implementations/text/native/native_text_segment_buffer.ts
src/core/segment_buffers/implementations/types.ts
src/core/segment_buffers/index.ts
src/core/segment_buffers/inventory/buffered_history.ts
src/core/segment_buffers/inventory/index.ts
src/core/segment_buffers/inventory/segment_inventory.ts
src/core/segment_buffers/inventory/types.ts
src/core/stream/representation/get_buffer_status.ts
src/core/stream/representation/get_needed_segments.ts

This tries to fix #987.
In that issue, Safari advertised that the first pushed audio segment started at 0.450+ where the RxPlayer previously thought it started at exactly 0 second (based on MPD information and container metadata, such as the `tfdt` box of ISOBMFF segments).
The behavior of the player when encountering such a big difference, is to re-download the corresponding segment, because it thinks that the pushed segment has been partly garbage-collected by the browser.
In the Safari issue, re-pushing the same segments led to the same result and as such we end up requesting the same segment in a loop while rebuffering endlessly.
In that situation, it appears obvious that we should just ignore the issue and just seek over that gap and continue. However having agarbage-collected …

Avoid requesting in a loop segments the browser crops for some reasons

---

doc/api/exported_types.md
src/core/api/option_utils.ts
src/core/api/track_choice_manager.ts
src/manifest/adaptation.ts
src/manifest/index.ts
src/manifest/representation.ts
src/manifest/types.ts
src/parsers/manifest/types.ts
src/public_types.ts
src/transports/dash/segment_loader.ts
src/transports/metaplaylist/manifest_loader.ts
src/transports/smooth/segment_loader.ts
src/transports/types.ts
src/transports/utils/call_custom_manifest_loader.ts
src/transports/utils/generate_manifest_loader.ts
tests/integration/scenarios/dash_multi_periods.js

Fixes #972
Add the following TypeScript types to the `rx-player/types` path, and document them:
- `IPersistentSessionInfo`
- `IPersistentSessionStorage`
- `ICustomError` (as `IPlayerError`)
- `IRepresentationFilter`
- `IRepresentationInfos` (the second argument of the `representationFilter` function)
-  `ICustomSegmentLoader` as (`ISegmentLoader`)
-  `ICustomManifestLoader` as (`IManifestLoader`)
Those are all types that may be encountered in the API.
I also added those newly defined types:
- `IManifest`
- `IPeriod`
- `IAdaptation`
- `IRepresentation`
- `ISegment`
Which are sub-types of the corresponding RxPlayer's structure with only the properties and methods we defined in the API documentation.
I profited from this commit to do some clean-up:
- The `CustomManifestLoader` and …

add supplementary exported types to the API

---

src/core/stream/representation/downloading_queue.ts
src/core/stream/representation/representation_stream.ts
tests/integration/scenarios/initial_playback.js
tests/integration/scenarios/loadVideo_options.js
tests/integration/utils/launch_tests_for_content.js
tests/utils/waitForPlayerState.js

This is yet another retry of #918 and #898 of loading when possible the init segment parallelly to the first media segment(s).
We encountered a lot of issues when trying to implement that logic before.
To simplify this implementation, I rely on the work to de-asynchronize segment parsers done in #950, on which this PR is based.
The optimization should theoretically lead to lower loading time, as both initialization and media segments are needed to play a content.
In reality, the browser might sometimes attenuate this with its internal request re-scheduling and unrelated license fetching is most often the last step before being able to play, so loading time advantages are still to prove.
--
The implementation is done through a new class called the `DownloadingQueue`.
The …

implement (again) parallel init and media segment fetching

---

src/core/init/initialize_directfile.ts
src/core/init/load_on_media_source.ts
src/core/init/stall_avoider.ts
src/core/stream/adaptation/adaptation_stream.ts
src/core/stream/events_generators.ts
src/core/stream/orchestrator/active_period_emitter.ts
src/core/stream/orchestrator/are_streams_complete.ts
src/core/stream/orchestrator/stream_orchestrator.ts
src/core/stream/period/period_stream.ts
src/core/stream/reload_after_switch.ts
src/core/stream/types.ts

This commit fixes a rare infinite rebuffering issue occuring when playing close - but before - the next Period's start, when one of its associated audio and/or video PeriodStream or AdaptationStream requires a reloading of the MediaSource before having the chance to load any segment.
For example this can happen when disabling the video track of the next Period, before it had the chance to load any segment. In that case, when playing close to that Period, the clock will anounce that we should rebuffer because there is not enough data ahead in the video buffer to guarantee a smooth playback.
Yet the future video stream does not want to download any video segments - because video tracks have been disabled - yet the `StreamOrchestrator` refuses to ask for the removal of the video SourceBuffer …

stream: add the concept of a "locked" stream

---

demo/full/scripts/controllers/Main.jsx
demo/full/scripts/modules/player/index.js
package-lock.json
package.json
scripts/fast_demo_build.js
scripts/generate_full_demo.js
scripts/start_demo_web_server.js

This PR tries to improve demo building time by using the notoriously faster [esbuild](https://esbuild.github.io/) bundler instead of the Webpack bundler we use by default.
I also profited from this PR to improve on the current webpack config scripts by making them configurable through command line arguments instead of environment variables. This should be easier to understand and follow. That part can (and most probably should!) be added in a separate PR.
By switching from webpack to esbuild when starting a demo, we go on my laptop from 15s-16s to 100-200ms to build the demo page.
16 seconds was not much, but it was enough that it could lead me to switching to another task, waiting for the demo to be built - and thus usually costed much more than that. I would not be surprised if I was …

scripts: add `s` script (as a faster `start` option), allowing very fast demo building when developing

---

src/core/abr/index.ts
src/core/abr/representation_estimator.ts
src/core/fetchers/index.ts
src/core/fetchers/segment/index.ts
src/core/fetchers/segment/prioritized_segment_fetcher.ts
src/core/fetchers/segment/prioritizer.ts
src/core/fetchers/segment/segment_fetcher.ts
src/core/fetchers/segment/segment_fetcher_creator.ts
src/core/stream/adaptation/adaptation_stream.ts
src/core/stream/adaptation/create_representation_estimator.ts
src/core/stream/representation/downloading_queue.ts
src/core/stream/representation/representation_stream.ts
src/experimental/tools/VideoThumbnailLoader/thumbnail_loader.ts
src/transports/types.ts

This commit tries to reduce the strong implicit link between the `fetchers` (in `src/core/fetchers`) and the ABR logic (in `src/core/abr`).
Why
===
In the previous code, the `SegmentFetcher` (deep inside the fetchers code) directly used an RxJS Subject to send various network lifecycle events which was listened to by the `RepresentationEstimator` (deep inside the ABR code). The `stream` (in `src/core/stream`) was the one linking both by creating the Subject and passing it to both modules.
I wasn't happy with that link, even more considering that new cases (the `VideoThumbnailLoader` and the future `ContentDownloader`) may want to use the `fetchers` code to load and parse segments without needing any adaptive logic from the ABR. In that case, they needed to provide a mute Subject, which …

Reduce coupling between fetchers and ABR by using callbacks in the former

---

src/parsers/manifest/dash/common/get_http_utc-timing_url.ts

While both doing the inventory of what MPD attributes handle the RxPlayer and working on low-latency contents, I noted that the RxPlayer did not support `UTCTiming` element with the `urn:mpeg:dash:utc:http-xsdate:2014` scheme value
Yet it is very simple to implement - at least in JavaScript - as we already handle the `http-iso` format and that both are valid ISO8601 dates. As we use the `Date` builtin to transform such strings to a JS `Number`, we can thus use the exact same parsing logic for both.

Support UTCTiming element with the http-xsdate scheme

---

src/parsers/manifest/dash/common/indexes/get_segments_from_timeline.ts
src/parsers/manifest/dash/common/indexes/template.ts
tests/contents/DASH_static_number_based_SegmentTimeline/index.js
tests/contents/DASH_static_number_based_SegmentTimeline/infos.js
tests/contents/DASH_static_number_based_SegmentTimeline/media/manifest.mpd
tests/contents/DASH_static_number_based_SegmentTimeline/urls.js
tests/contents/urls.js
tests/integration/scenarios/dash_static.js

DASH indexes of segments which rely on a `<SegmentTemplate>` element can either declare segment URLs based on the corresponding segment's timestamp or on a number incrementing with each segment from a given base, the `startNumber`.
Usually, time-based SegmentTemplates contains a `<SegmentTimeline>` element, listing all segments and their corresponding timestamps whereas number-based don't.
But this is not always the case, for example a number-based indexing scheme can be linked to a `<SegmentTimeline>` in the MPD (we might even in many case prefer it because a SegmentTimeline facilitates live-edge detection on the player-side).
As per the DASH-IF IOP the `startNumber` attribute is totally optional and should be set to `1` by default.
This is something we considered when no SegmentTimeline …

dash: provide default startNumber for number-based SegmentTimeline

---

src/parsers/manifest/dash/common/get_clock_offset.ts
src/parsers/manifest/dash/common/parse_mpd.ts
src/parsers/manifest/dash/js-parser/parse_from_document.ts
src/parsers/manifest/dash/parsers_types.ts
src/parsers/manifest/dash/wasm-parser/ts/dash-wasm-parser.ts
src/transports/dash/manifest_parser.ts
src/utils/assert.ts

The low latency manifests are generally filled with a tag `<UTCTiming/>`, this allows the player to download external resources to be able to synchronize the clock with real date.
However, sometimes in those manifests, the resources are using the non-encrypted protocol HTTP instead of HTTPS, the browser is preventing to doing that to not break the security, so the player crashed.
We now are more resilient to that kind of behavior by using a default behavior.

Resilience when retrieving external ressources related clock

---

src/core/eme/check_key_statuses.ts

I recently noticed that the `KEY_STATUS_CHANGE` error or warning was very useful when debugging DRM-related issues.
Thanks to it, we can know for example if some key in a multi-key contents is not considered as usable, which in turn can lead to all sort of issues.
However, when just browsing player logs (which is the first step most of the time), we missed a crucial information: which key we're talking about.
This commit adds the key-id, represented as an hex value, to the message of KEY_STATUS_CHANGE errors.

eme: add key id to KEY_STATUS_CHANGE error messages

---

src/compat/__tests__/set_element_src.test.ts
src/compat/set_element_src.ts
src/core/abr/representation_estimator.ts
src/core/abr/representation_score_calculator.ts
src/core/api/track_choice_manager.ts
src/core/eme/eme_manager.ts
src/core/eme/find_key_system.ts
src/core/eme/get_media_keys.ts
src/core/eme/session_events_listener.ts
src/core/eme/utils/close_session.ts
src/core/eme/utils/is_session_usable.ts
src/core/eme/utils/loaded_sessions_store.ts
src/core/eme/utils/persistent_sessions_store.ts
src/core/fetchers/segment/segment_fetcher.ts
src/core/init/create_media_source.ts
src/core/segment_buffers/implementations/audio_video/audio_video_segment_buffer.ts
src/core/stream/adaptation/adaptation_stream.ts
src/core/stream/orchestrator/stream_orchestrator.ts
src/core/stream/period/period_stream.ts
src/experimental/tools/VideoThumbnailLoader/thumbnail_loader.ts
src/manifest/index.ts
src/manifest/utils.ts
src/parsers/manifest/dash/common/__tests__/flatten_overlapping_period.test.ts
src/parsers/manifest/dash/common/flatten_overlapping_periods.ts

This is a smallish yet global log update so they are easily exploitable, that is:
- there are less heavy objects logged. They are both difficult to exploit and take resources when there are lot of logs displayed (and there is a lot of them in DEBUG mode).
Instead, key identifying properties of those objects are logged (e.g. A Period's `start`, A Reprentation's `id` or `bitrate` etc..).
I didn't change anything however for some smallish objects (like segments, array of ranges) and objects containing parsed subtitles, as it may still be very useful
This task was already begun by Guillaume Renault some time  (year?) ago, but I didn't merge it at the time because I didn't felt it was that much of an issue. I've now changed my mind!
- add logs for when segment requests begin, end, fail and are …

update most log so they are more easily exploitable

---

src/parsers/containers/isobmff/get_box.ts
src/parsers/containers/isobmff/read.ts
src/parsers/containers/isobmff/utils.ts

This is a commit with a smallish improvement to better estimate the duration of segments with multiple "moof" boxes (for example, low-latency segments loaded as a whole instead of per-chunk).
Previously, only the first "trun" box of the first "traf" box of the first "moof" box encountered in an ISOBMFF segment was parsed to obtain the segment's duration.
In most cases, this works. However in some rare situations, media segments might actually contain several subsegments, in which case we would only calculate the first of those subsegments' duration.
Now, we always check if multiple moof boxes are there and, if it is the case, we addition the duration calculated from all found trun boxes.
The previously miscalculted duration never provoked any sensible issue because we have a safeguard …

Better estimate the duration of ISOBMFF segments with multiple moof boxes

---

src/compat/__tests__/clear_element_src.test.ts
src/compat/clear_element_src.ts

This commit works around an issue seen recently with Chrome 96 where native text tracks would not be visually removed after stopping a content / reloading another.
First thought to be an RxPlayer issue, we noticed that the corresponding `<track>` element was actually properly removed from the DOM and that the issue only appeared in Chrome, even on Edge Chromium things worked as intented.
After investigation, the issue seems to be linked to Chrome: when the `<track>` element is removed from the DOM synchronously after (or in a microtask after) emptying the src attribute of the linked media element, the `<track>` element disappears from the DOM, but its content stays on it.
Funnily enough, it seems (I forgot about it) that the same issue was present in FireFox some years ago, judging by …

Fix native track elements' content not removed in Chrome 96

---

package.json

The `check` script, runnable through `npm run check`, previously ran:
1. TypeScript to check types in the src directory
2. eslint to lint the src directory
3. All unit tests
The goal of that script was that it could be used before all commits / push, so we can avoid pushing mistakes when in the review phase.
However, I suspect that the fact that it runs all unit tests, which can be a long operation (43 seconds for me on the current master), reduce its attractiveness enough that we often skip that step.
As unit tests are run by our CI (and often manually) anyway, I'm removing it from the `npm run check` script which will now only type check and lint, which are both the most useful and the faster operations of the three.

scripts: `check` script does not run unit tests anymore

---

src/core/abr/pending_requests_store.ts
src/core/fetchers/segment/segment_fetcher.ts

A small oversight led to the RxPlayer potentially logging a warning each time a segment is either created directly from the Manifest's information - which as far as I remember - only happens in Smooth contents or when no initialization segment exist (such as for subtitles).
Aside from this unnecessary warning, there should be no other real issue.
This warning was due to the fact that we're announcing the end of those segment's "requests" (between quotes as there there is in fact no request happening) two times in a row, breaking an assertion later in the code that ended request should be pending in the first place.
It's annoying that I saw that just after finalizing the release, but thankfully this is a very minor issue that will probably not bother
anyone, and should appear relatively …

 Avoid warning logs when "creating" segments

---

src/parsers/manifest/dash/common/indexes/timeline/construct_timeline_from_elements.ts
src/parsers/manifest/dash/common/indexes/timeline/timeline_representation_index.ts
src/parsers/manifest/utils/__tests__/update_segment_timeline.test.ts
src/parsers/manifest/utils/clear_timeline_from_position.ts
src/parsers/manifest/utils/update_segment_timeline.ts

Fixes #1052.
We had an issue with our logic which automatically removes references to outdated segments the RxPlayer found in DASH' s SegmentTimeline.
After removing segments behind the current DVR window (a.k.a. timeshift buffer depth), it wasn't updating the
potentially-linked `startNumber` attribute, which is useful in case a `$Number$` URL scheme is used (thankfully this is rare with DASH SegmentTimeline, where `$Time$` is usually preferred in that case).
Due to this a bug could be encountered when the beginning of that `$Number$`-based SegmentTimeline was before the DVR window. In that case, the wrong segment's number would be calculated and thus, the wrong segment would be loaded.
This commit fixes the issue by making all functions that may remove elements from a referenced …

DASH: properly update `startNumber` on SegmentTimeline GC

---

src/core/stream/representation/force_garbage_collection.ts

This is a very minor fix on what appeared to be an inefective strategy when receiving a QuotaExceededError, which is an error which may appear when a pushed segment overloads the memory.
The previous strategy was to try to clean-up ranges of data - that are far away from the current position - from the buffer (a strategy generally already performed by the browser).
However, and at least to me, the condition appeared to be the reverse of what we should check for. We were not clearing far away ranges, but ranges that were close (yet thankfully not the one containing the current position).
Still, I welcome any reviewer to re-check, as this type of range-related logic is notoriously hard to reason about.
We did not observe any bug or weird behavior linked to this problem and this logic should …

stream: fix logic for range eviction on QuotaExceededError

---

src/core/segment_buffers/implementations/text/html/text_track_cues_store.ts

We discovered an issue where subtitles could be skipped in rare situations.
To obtain that issue, the subtitles cues pushed should have overlapping time boundaries in a specific way:
```
previous segment: |AAAAA|
new segment:         |BBBBBB|
```
Here the wanted result should have been:
```
Result:           |AAABBBBB|
```
But effectively became:
```
Result:              |BBBBB|
```
This was due to a mistake related to finding the index that new segment should be pushed to in the corresponding segment array.
---
Real overlapping segments are very rare but this situation here happened due to a very low rounding error when calculating a segment's end.
In the encountered case, the ending time of a segment N was offseted by a fraction of a millisecond and was for this reason superior to the …

Fix subtitles skipping issue on overlapping cues

---

.github/workflows/perfs.yml
.gitignore
tests/contents/server.js
tests/performance/index1.html
tests/performance/index2.html
tests/performance/run.js
tests/performance/src/main.js

This is a first implementation for #1053, or the ability to run performance tests, principally to detect performance regressions.
The idea is to perform multiple scenarios both with the last published RxPlayer version and with the current branch and to compare the time it took to perform those.
To know when performance differences are significant, both the scenarios and the browser are launched multiple times for each tests (100 times * 10 browser run for both the last RxPlayer version and the current branch for now).
Also the Mann–Whitney U test is used to check for the null hypothesis and to ensure a difference in the mean time is significant. 
If that check indicates that the difference is significant AND if the mean value (corresponding to a delay) for any test grows, tests fail. …

Add performance tests

---

src/transports/types.ts

An application developper recently let me know that the type definitions for the RxPlayer's `transportOptions.segmentLoader` and `transportOptions.manifestLoader` loadVideo option were missing some attributes/arguments:
- the `url` property that a manifest loader can communicate to the RxPlayer in case of a redirection is not defined (even if setting it worked).
- the `progress` callback provided to the segment loader to notify about the request was not defined (even if using it worked)
I also noticed a third issue, the `fallback` callback allowing to fallback on the RxPlayer's default loader implementation could be
undefined. I guess it could make sense in some cases, such as cases where the RxPlayer is not able to do requests (for example: a "local-manifest" content) but in that case we …

Add forgotten TypeScript types in the exposed segment and manifest loader APIs

---

src/parsers/manifest/dash/common/indexes/timeline/timeline_representation_index.ts
src/parsers/manifest/dash/common/parse_adaptation_sets.ts
src/parsers/manifest/dash/common/parse_periods.ts
src/parsers/manifest/dash/common/parse_representation_index.ts
src/parsers/manifest/dash/common/parse_representations.ts

This PR fixes an issue we recently had at Canal+ linked to ambiguous DASH Period boundaries:
An infinite rebuffering issue could arise when playing a live multi-Period DASH content where the audio and video tracks had different ending timestamp (even in the order of some milliseconds) AND the duration of the Period (either taken from the `Period@duration` attribute or inferred from the `Period@start` of the next Period if one) was set to be the maximum time between them (which very oddly is the DASH-IF recommendation).
In that condition, the RxPlayer could be waiting indefinitely at the end of the corresponding Period for what it thinks to be the last - but is actually inexistent - audio or video segment (respectively depending on if the audio track or the video track is shorter)  to be …

DASH: always consider that the non-last Period is finished in SegmentTimeline contexts

---

src/core/fetchers/manifest/manifest_fetcher.ts
src/core/fetchers/utils/try_urls_with_backoff.ts
src/experimental/tools/VideoThumbnailLoader/thumbnail_loader.ts
src/parsers/manifest/dash/wasm-parser/ts/dash-wasm-parser.ts
src/transports/dash/add_segment_integrity_checks_to_loader.ts
src/transports/dash/image_pipelines.ts
src/transports/dash/init_segment_loader.ts
src/transports/dash/manifest_parser.ts
src/transports/dash/segment_loader.ts
src/transports/dash/text_loader.ts
src/transports/local/segment_loader.ts
src/transports/metaplaylist/pipelines.ts
src/transports/smooth/pipelines.ts
src/transports/smooth/segment_loader.ts
src/transports/utils/call_custom_manifest_loader.ts
src/utils/cancellable_sleep.ts
src/utils/cast_to_observable.ts
src/utils/request/fetch.ts
src/utils/request/xhr.ts
src/utils/rx-from_cancellable_promise.ts

While debugging an unrelated issue, I noticed that pinkie's Promise implementation was being used even on a recent browser with a native Promise implementation.
This is due to mix-ups in the code, where we're including directly this implementation (`import PPromise from "pinkie";`) instead of importing the file selecting one or the other depending on browser support (`import PPromise from "../../utils/promise"`).
This is not a big issue at all, and I would guess most places still relied on the native implementation, but it's probably better for performance reason to use the native one when available.
I was also wondering if it made sense to use pinkie at all. Originally, it was just imported so the player can be used on IE11.
Yet it seems that RxJS, one of our other dependencies, does not …

Only rely on pinkie's Promise when necessary

---

src/core/api/media_element_track_choice_manager.ts

We recently observed an issue on Safari where enabling an audio track in directfile mode without disabling the others led to the new audio track not being audible (but the previous one still being audible).
To our knowledge, Safari had no problem with this previously but by checking the HTML5 living standard recently, we saw that at least now, enabling an audio track does not mean that the others are disabled and could even mean hearing multiple audio tracks at once.
This PR thus disables all other audio tracks when enabling a new one, which should not be problematic in any case.
It has been tested on Safari with success.

directfile: disable all audio tracks before enabling one to work-around Safari issue on MacOS Monterey

---

src/compat/__tests__/should_favour_custom_safari_EME.test.ts
src/compat/browser_detection.ts
src/compat/should_favour_custom_safari_EME.ts

After a lot of tests today, we noticed that Safari mobile's standard EME implementation worked in mysterious ways. Despite multiple retries, we never could pass the `generateRequest` step, presumably due to a non-satisfactory `initDataType` argument.
We ended up trying to use the webkit-prefixed APIs in its place, which work differently than the standard but whose behavior is known.
And it worked! We could at last play encrypted directfile contents (including HLS) on Safari IOS.
Note that we already did that for Safari Desktop due to similar issues months (years?) ago, but we might not have tested properly on Safari iOS (in directfile mode) at the time.
---
Because the `isSafari` constant was only `true` for Safari desktop, and because I though making a difference between it and mobile …

drm: Use WebkitMediaKeys implementation on Safari Mobile

---

src/core/api/public_api.ts

Fixes #1055
This PR add the usage of the `HTMLMediaElement.prototype.getStartDate` method when available (for now just seen on Safari when playing HLS contents) to provide a real "wall-clock time" (which is in our case, the offseted position to correspond to the air time) when playing directfile contents.
Previously, all directfile contents just returned the real non-offseted position when calling `getWallClockTime`.
More information [on the corresponding issue](https://github.com/canalplus/rx-player/issues/1055)

directfile: use getStartDate in getWallClockTime when available

---

src/parsers/manifest/smooth/create_parser.ts

Some Smooth manifest comes with `FourCC="DFXP"` and subtitles are not shown.
Adding `DFXP` to mime types map solve the issue.

Fix: add dfxp mime type

---

doc/api/Typescript_Types.md
src/core/api/index.ts
src/core/api/public_api.ts
src/public_types.ts

This commit adds to the `rx-player/types` path the following types:
- IBitrateEstimate (payload of a `bitrateEstimationChange` event)
- IPositionUpdate (payload of the `positionUpdate` event)
- IPlayerState (return value of the `getPlayerState` method and payload of the `playerStateChange` event).
Those were missing and an issue was open (#1076) to ask us to add them.
I also profited from this commit to move type definitions in `src/core/api/public_api.ts` at the end of the file as we do now to improve code readability when first reading it).
There's however a remaining problem in that VSCode (and I suppose every other editors relying on tsserver's auto-import feature) seems to prefer the real source file of the type definition on some auto-imports and not the re-export done in the …

Add IBitrateEstimate, IPositionUpdate and IPlayerState types to the API

---

src/core/api/public_api.ts

There was an issue in the RxPlayer where a RELOADING state triggered synchronously after a LOADED state (the only case I can see now is when an application provokes an action in the event listener of a `playerStateChange` event with a `LOADED` payload which lead to a reload - typically a video track change) would not be advertised through either the `playerStateChange` event nor the `getPlayerState` method.
This is because those state updates were based on Observables, and the Observable triggering the RELOADING state was only started/subscribed [synchronously] after the LOADED state was sent.
So we could be left in a state where:
1. The RxPlayer switches to the `LOADED` state
2. An application reacts to that state change by calling an API which triggers a reload
3. A reloading signal is …

api: allow switching to RELOADING state synchronously after LOADED

---

src/parsers/manifest/dash/common/parse_adaptation_sets.ts
tests/contents/DASH_static_SegmentTimeline/media/multi-AdaptationSets.mpd
tests/contents/DASH_static_SegmentTimeline/media/multi_period_different_choices.mpd
tests/contents/DASH_static_SegmentTimeline/media/multi_period_same_choices.mpd
tests/integration/scenarios/dash_multi-track.js

A new platform (from italia) using the RxPlayer recently noticed us that the default audio track chosen on some DASH contents was wrong according to them.
For example, on some American film with two audio tracks, one in english (the original language) and the other in italian (which is dubbed) the RxPlayer would select the english one if no preference was given.
For the application developers, it was an error as the italian audio `AdaptationSet` had both a `selectionPriority` higher than the english one and was higher in the MPD.
However, it turned out that the english AdaptationSet had a `<Role>` element set to "main" - indicating that it was the "main" audio track - and the itialian one also had a `<Role>` element but set to "dub" this time - indicating that this track is dubbed.
And …

DASH: Prioritize `selectionPriority` attribute over a "main" Role when ordering AdaptationSets

---

src/config.ts
src/core/stream/representation/get_needed_segments.ts
src/default_config.ts

This PR fixes two minor issues both seen while working on a future 4.0.0 version:
1. I noticed an issue where discontinuities created by either browser garbage collection or due to the `SourceBuffer.remove` API would not be re-filled when re-encountered but directly skipped instead.
This is because the current logic had a typo which led the RxPlayer to ignore some segments GCed at their end.
Thankfully, instead of staying in rebuffering when that hole is encountered, another module of the RxPlayer, the `StallAvoider` understood that this hole won't be filled by any segment and directly seeked over it when encountered.
By fixing the typo, this gap is now filled as expected.
2. I noticed that the previous paddings used for video adaptation switches were sometimes insufficient.
Removing data …

Fix minor buffer-related problems

---

src/core/decrypt/content_decryptor.ts
src/core/decrypt/set_server_certificate.ts

Amazingly, the `setServerCertificate` method seems to return a `Promise<undefined>` instead of the usual `Promise<boolean>` at least on my Firefox windows.
This commit rewrites that logic a little so it becomes more resilient to those kind of cases.

decrypt: be more resilient when calling setServerCertificate

---

doc/api/Loading_a_Content.md
src/core/api/__tests__/option_utils.test.ts
src/core/api/option_utils.ts
src/core/init/initialize_media_source.ts
src/core/stream/index.ts
src/core/stream/period/get_adaptation_switch_strategy.ts
src/core/stream/period/index.ts
src/core/stream/period/period_stream.ts
src/public_types.ts

I was considering adding the "reload" `audioTrackSwitchingMode` as we noticed that a specific Canal+ application (one linked to Media Asset Management) experienced issues with the `"direct"` `audioTrackSwitchingMode`, a mode allowing to switch between audio tracks directly at the cost of a brief rebuffering period while the new audio track is loaded - instead of the  smoother default `"seamless"` we use for example on the canalplus.com website, which still plays the old audio track for a few seconds before switching.
Though I could not yet reproduce this issue on my side (due to security mechanisms preventing me from testing it for now - though we're working on it), I'm wondering if adding a `"reload"` mode in any case - which would completely reload the `MediaSource` - would not make …

[Proposal] Add "reload" `audioTrackSwitchingMode`

---

src/compat/eme/generate_key_request.ts
src/core/decrypt/content_decryptor.ts
src/core/decrypt/create_or_load_session.ts
src/core/decrypt/create_session.ts
src/core/decrypt/utils/loaded_sessions_store.ts
src/default_config.ts

In the [EME specification](https://www.w3.org/TR/encrypted-media) it is implicitely indicated that closing a `MediaKeySession` cannot be done until `generateRequest` or `load` has been called on it.
Because we don't always trust platforms to perfectly implement the EME specification (I would say that those are the APIs with which we encounter the most issues), we had a less than ideal yet general solution which just retried closing a MediaKeySession (with an exponential backoff) when it couldn't be done due to an `InvalidStateError` - the error rejected when the MediaKeySession is not yet ready to be closed.
However, there was multiple issues, especially on low-end devices, that made me reconsider this solution:
1. The exponential backoff could lead to large waiting time in some cases. …

DRM: await potential pending `generateRequest` and `load` call before closing a MediaKeySession

---

src/parsers/texttracks/ttml/html/generate_css_test_outline.ts

We mock the `textOutline` property in TTML Subtitles through the CSS `textShadow` property.
We try to preserve as many values as possible but the issue arise when we set a thickness based on percent ( which is allowed in TTML ) for the `textOutline`, but percent based values are not allowed in the t`extShadow `property
The solution is to convert the percent into `em` which are basically equivalent as both are relative to the current element's font size

Add support for percent based thickness for textOutline in TTML Subtitles

---

src/parsers/manifest/dash/common/flatten_overlapping_periods.ts

Fixes #1110.
This PR fixes an infinite loop that could occur on multi-Period MPDs due to a rounding error linked to floating-point operations.
This issue was very easy to work-around because one of the two inner branches of that loop actually always led to a loop exit (because it would always break the loop's condition - though here it didn't due to that damned rounding error).
Explicitly writing a `break` instruction when that branch is taken is thus here a quick and easy fix, though it may not be the most elegant way of dealing with it (if you have more simple and idiomatic ways, I'll change to it).
I also added comments and inverted the inner conditions, in the hope I made what that function is doing clearer.

Avoid infinite loop due to rounding errors while parsing multi-Periods MPDs

---

src/core/decrypt/content_decryptor.ts
src/core/decrypt/utils/key_session_record.ts
src/manifest/representation.ts
src/parsers/manifest/dash/common/parse_representations.ts
src/parsers/manifest/types.ts

We introduced a regression in the v3.27.0 which can lead to infinite rebuffering/loading when playing MPD which do not anounce the key ids in a `@cenc:default_KID` attribute (which seems to be required by the DASH-IF IOP? That's why I understand from Chapter 7.6.2.1 of the v4.3, though I'm unsure and we chose to be resilient anyway).
Basically the source of the error is a difference in semantics between what our MPD parser parses and what the `ContentDecryptor` takes in input to trigger the whole decryption logic.
Especially, the difference is how the `keyIds` property, defined in both places is defined:
- for the parser, it is the array of just the "key IDs associated with that content" and is always set as long as the content is encrypted.
- for the `ContentDecryptor`, it's much more …

DASH: Fix potential infinite rebuffering when a KID is not anounced in the MPD

---

src/manifest/representation_index/types.ts
src/parsers/manifest/dash/common/indexes/base.ts
src/parsers/manifest/dash/common/indexes/list.ts
src/parsers/manifest/dash/common/indexes/template.ts
src/parsers/manifest/dash/common/indexes/timeline/timeline_representation_index.ts

Based on #1098
The `getLastPosition` method of `RepresentationIndex`es was previously ambiguous in that it returned the "end of the last segment in a given Representation" but without precizing what happens if the parent `Period` is shorter (in which case the segment will be cropped to not go further than this last value before being played).
This PR sets a new - more precize - definition that changes a little the behavior but should not break anything: it returns now the theoretical last playable position in the Representation.
As such it is now always bounded by the Period's end.
I did this to raise its usefulness: the last reachable position (the new value) should be much more useful than the maximum position the last segment contains media data for (the old value).
Moreover, we never …

DASH: RepresentationIndex' `getLastPosition` is now limited by the Period's end

---

src/parsers/manifest/dash/common/indexes/timeline/timeline_representation_index.ts

This commit fixes a dumb typo which could lead to multiple issues related to miscalculating the maximum position reachable by segments within a Period.
Thankfully, the conditions for the RxPlayer to rely on the problematic code were rare: we needed to have a `SegmentTimeline` with the last segment having a `S@r` attribute set to `-1` and a Period with a set `Period@end` attribute. In that condition, the wrong ending position would be calculated for the last segment in the Period, which would lead to difficult-to-predict issues.
Because `S@r` attributes set to `-1` are rare in the wild, we didn't hear of any application having the issue for now - it is thus for now only a theoretical problem.

DASH: fix awkward typo which would calculate wrong segment estimates

---

src/core/stream/representation/get_buffer_status.ts
src/core/stream/representation/representation_stream.ts
src/manifest/period.ts

This PR fixes a theoretical issue that could arise if an user seeked after the last possible position.
Doing this is difficult to reproduce but is for example possible when multiple audio or video AdaptationSets have different durations, with at least one inferior to the corresponding Period and/or Manifest's duration.
In that situation, the media element's duration may be set higher than the maximum time on the shorter AdaptationSet and it will thus be possible to seek further than the latter.
After the seek is done, the RxPlayer would notice that we are after the last position, call the `endOfStream` API to notify that playback is done, and switch the `ended` state.
Without putting much thoughts into it, this could seem like the right thing to do. However, `endOfStream` will have the …

If seeking after the last potential position, load last segments before ending

---

src/core/stream/period/period_stream.ts

The previous logic used the codec of the first (lowest quality?) Representation of the first AdaptationSet chosen when creating initially the SourceBuffer.
This can fail if the lowest quality is not supported.
This PR uses the first "compatible" (supported and not non-decipherable) Representation instead.

Use the first compatible codec of the current AdaptationSet when creating a SourceBuffer

---

src/parsers/manifest/dash/common/indexes/timeline/construct_timeline_from_elements.ts
src/parsers/manifest/dash/common/indexes/timeline/construct_timeline_from_previous_timeline.ts
src/parsers/manifest/dash/common/indexes/timeline/convert_element_to_index_segment.ts
src/parsers/manifest/dash/common/indexes/timeline/timeline_representation_index.ts

This is another attempt, after 161157a350de53debce09f3465834e3176d2b918, to calculate a default `t` attribute for the first `<S>` element of a DASH's `<SegmentTimeline>` when the first one omitted it (which happens quite rarely).
The initial logic basically made as if the first segment had a time of `Period@start - SegmentTemplate@presentationTimeOffset`. However, we did have issues with it with some of those rare streams.
The 161157a350de53debce09f3465834e3176d2b918 fix tried to only consider `Period@start` here to work-around those issues, this was mainly done this way because it seemed to fix the encountered cases, as I found the DASH specification unclear on that situation.
However, after doing one of our "beta-like" release (`dev` and `canal` releases), we saw that this broke other …

DASH: initial S elements without a `t` attribute implicitely begin at `0`

---

src/parsers/manifest/dash/common/indexes/get_segments_from_timeline.ts
src/transports/utils/get_isobmff_timing_infos.ts

After doing some experimentation with the `@presentationTimeOffset` attribute of a DASH MPD to omit certain parts in the beginning of various contents, we noticed that the RxPlayer had a poor handling of segments starting at a negative time.
As media data before `0` will be ignored anyway, the easy solution is just to make as if the media data before the `0` position did not exist.
This is what this PR does.

Fix issues that could arise when handling segments starting at a negative position

---

src/core/stream/orchestrator/active_period_emitter.ts
src/parsers/manifest/dash/common/indexes/base.ts
src/parsers/manifest/dash/common/indexes/timeline/timeline_representation_index.ts

The previous RxPlayer's behavior could lead to consider that the first playable media data in a Period starts before the Period's start, or even before a `0` position which should not be possible.
In turn, this could lead to strange behaviors, like producing a negative initial time (which seems to just lead to infinite rebuffering).
This commit ensure that an index never communicates it has media data before the related Period's start.

DASH: set a minimum for the first available position of an index

---

src/index.ts
src/minimal.ts
src/typings/globals.d.ts

This change allows to simplify debugging sessions when either done through [RxPaired](https://github.com/peaBerberian/RxPaired) (once https://github.com/peaBerberian/RxPaired/pull/1 is merged) or any other tool by just setting `window.__RX_PLAYER_DEBUG_MODE__` to `true` before the RxPlayer is evaluated.
The only influence this boolean has for now is to set the highest log verbosity, a necessity to unlock all RxPaired features.
But we may add other features in the future.
This is not only restricted to the RxPaired tool by the way, any other log-redirecting script could make use of that boolean.
The only risk I can think of is to have conflicting variables into window but the name chosen seems rare enough to me for it being a real problem.

[Proposal] Consider __RX_PLAYER_DEBUG_MODE__ boolean if declared in window

---

demo/full/mpd-parser.wasm
demo/full/scripts/controllers/Main.jsx
demo/full/scripts/modules/player/index.js
package.json
scripts/fast_demo_build.js
scripts/generate_full_demo.js
scripts/start_demo_web_server.js

This PR is a proposal to use the Minimal RxPlayer (the one with feature switching) instead of awkwardly modifying a `__FEATURES__` global to chose which feature to include while using the "main" RxPlayer exported.
As importing the minimal RxPlayer instead of the legacy default one is something we advise to all applications, I felt it wasn't coherent to not follow our own advice here!
In the future, I think that we may want to get rid of the `__FEATURES__` object altogether (we still need it now to define the wanted default feature included in our legacy builds and for tests) to simplify the code.
---
But mostly those modifications were just a [nice] side-effect of the real improvement of this PR: I added to npm scripts, `npm run start:wasm` and `npm run s:wasm` which are like respectively …

[Proposal] The demo page now uses the Minimal RxPlayer (and optionally the WASM MPD parser)

---

src/core/stream/representation/get_needed_segments.ts

There was a small typo in how we calculate memory estimates internaly, to avoid further mistakes and rounding errors, we decided to change every internal computation to be done using bits.

fix/ Changed how we calculate memory estimate

---

src/compat/event_listeners.ts
src/core/adaptive/adaptive_representation_selector.ts
src/core/adaptive/network_analyzer.ts
src/core/api/__tests__/get_player_state.test.ts
src/core/api/get_player_state.ts
src/core/api/playback_observer.ts
src/core/api/public_api.ts
src/core/init/content_time_boundaries_observer.ts
src/core/init/create_stream_playback_observer.ts
src/core/stream/adaptation/adaptation_stream.ts
src/core/stream/adaptation/index.ts
src/core/stream/orchestrator/stream_orchestrator.ts
src/core/stream/period/create_empty_adaptation_stream.ts
src/core/stream/period/period_stream.ts
src/core/stream/reload_after_switch.ts
src/core/stream/representation/append_segment_to_buffer.ts
src/core/stream/representation/index.ts
src/core/stream/representation/push_init_segment.ts
src/core/stream/representation/push_media_segment.ts
src/core/stream/representation/representation_stream.ts
src/utils/rx-next-tick.ts

While working on integration tests (of a closed-source nature, not the ones in the RxPlayer project :/), I noticed a strange issue:
If a user triggered an action which led to a `RELOADING` state synchronously after the player's state updated to the `PAUSED` state (for example switching the video track when `PAUSED` is received), the RxPlayer might reload in a playing state instead of a paused state.
Arguably the situation is rare and the problem is not a big one either. Yet that issue was a real huge pain to fix, as it is linked to subtle race conditions between event listeners, the RxPlayer's API and the internal RxPlayer's code. Consequently it needed multiple fixes for that specific case not to be an issue anymore:
- First I added more events that may trigger a playback observation, on …

Prevent subtle race conditions linked to `paused` attribute when reloading the content

---

src/compat/eme/load_session.ts
src/core/decrypt/create_session.ts
src/core/decrypt/utils/loaded_sessions_store.ts

We noticed of an issue which led to the impossibility of playing an encrypted content in a "persistent-license" mode if its license had already been persisted in the past but it could not be retrieved by the browser through the `MediaKeySession.load` API.
This problematic situation only arises if the RxPlayer's persistent session storage, generally stored in `localStorage` by the application, is de-synchronized with the browser/CDM internal one, with the former having more items than the latter.
Arguably that situation is not frequent:
- we reproduced it at a large scale when updating the browser of some devices on which the RxPlayer runs.
That update was not a small step (the two versions were released years apart), leading us to believe that that browser internal representation of …

DRM: Create new persistent MediaKeySession when load fails

---

tests/integration/scenarios/dash_live_utc_timings.js
tests/integration/scenarios/discontinuities.js
tests/integration/utils/launch_tests_for_content.js

It's that time again where an integration test seems to randomly fail -
only in our CI - presumingly due to poor performance from the instance
doing the testing.
I'll do the usual fix of raising the time awaited, first in a Pull
Request to see if it has any effect.

tests: Raise timer awaiting discontinuity seek in integration tests

---

src/core/api/public_api.ts

We had an issue on LG TV which presumably was linked to a race condition on this device.
On some LG TVs only, and only when playing two consecutive unencrypted directfile contents, the second one would never play if:
- the `stopAtEnd` constructor option was set to `true`
- the second content was loaded immediately once the RxPlayer switched to the `"ENDED"` state.
This was because of a weird race condition, where:
1. An initial unencrypted directfile content is played until its end.
2. The browser set the media element's `ended` attribute to `true`
3. Some event (e.g. "timeupdate" or "pause") is then triggered through that media element.
That's when the RxPlayer first notices that the `ended` attribute is set to `true`, switches its state to `"ENDED"`, and trigger the corresponding …

For stopAtEnd option, rely directly on RxPlayer state changes

---

src/core/api/playback_observer.ts
src/core/init/stall_avoider.ts
src/default_config.ts

Some devices relying on the Tizen OS, like Samsung TVs, have a peculiar behavior - initially created on their side as an optimization - which breaks many of the RxPlayer's own and sometimes create playback issues:
When seeking on these devices, it is possible that the device itself re-seek at a different time instead, because for example it judges that playback may restart faster when starting from a position with a video I-frame instead of the position actually seeked to.
We understand that point of view (even if I personally don't think it should be done - the WHATWG HTML spec does seem to agrees with me here when it comes to seeking by mutating the `currentTime` attribute, for IMO good reasons).
Anyway, issues may be created when no audio data has been loaded - or even is present - for …

Try to work-around yet another case of Tizen seeking back

---

doc/api/Loading_a_Content.md
doc/api/Miscellaneous/plugins.md
doc/reference/API_Reference.md
src/core/api/option_utils.ts
src/core/api/public_api.ts
src/core/fetchers/manifest/manifest_fetcher.ts
src/core/fetchers/segment/segment_fetcher.ts
src/core/fetchers/segment/segment_fetcher_creator.ts
src/errors/custom_loader_error.ts
src/experimental/tools/VideoThumbnailLoader/thumbnail_loader.ts
src/experimental/tools/createMetaplaylist/get_duration_from_manifest.ts
src/public_types.ts
src/transports/dash/add_segment_integrity_checks_to_loader.ts
src/transports/dash/image_pipelines.ts
src/transports/dash/init_segment_loader.ts
src/transports/dash/low_latency_segment_loader.ts
src/transports/dash/manifest_parser.ts
src/transports/dash/segment_loader.ts
src/transports/dash/text_loader.ts
src/transports/local/pipelines.ts
src/transports/local/segment_loader.ts
src/transports/metaplaylist/manifest_loader.ts
src/transports/metaplaylist/pipelines.ts
src/transports/smooth/pipelines.ts
src/transports/smooth/segment_loader.ts
src/transports/types.ts
src/transports/utils/call_custom_manifest_loader.ts
src/transports/utils/generate_manifest_loader.ts
src/utils/request/fetch.ts
src/utils/request/xhr.ts

I noticed that we still hadn't any way to let an application configures request timeouts for either the Manifest or the segments.
By default, both of those timeouts are for now set at 30 seconds, which is a lot. On platforms seen recently where frequent timeouts are occuring (presumably due to CDN issues), this may easily lead to a rebuffering, both for live and VoD contents (though sensibly more chance to have one when playing a live content, as there is less preloaded buffer).
Those high timeouts were set as a safe high value. They could make sense for large 10+ seconds segments for example.
But on most real encountered cases with 2 to 4 seconds segments, it is too high and may lead to poor user experience in case of network issues.
---
I though we already allowed its configuration, but …

Implement `segmentRequestTimeout` and `manifestRequestTimeout`

---

src/compat/event_listeners.ts
src/compat/on_height_width_change.ts
src/core/segment_buffers/garbage_collector.ts
src/core/segment_buffers/implementations/audio_video/audio_video_segment_buffer.ts
src/core/segment_buffers/implementations/image/image_segment_buffer.ts
src/core/segment_buffers/implementations/text/html/html_text_segment_buffer.ts
src/core/segment_buffers/implementations/text/native/native_text_segment_buffer.ts
src/core/segment_buffers/implementations/types.ts
src/core/segment_buffers/segment_buffers_store.ts
src/core/stream/orchestrator/stream_orchestrator.ts
src/core/stream/period/period_stream.ts
src/core/stream/representation/append_segment_to_buffer.ts
src/core/stream/representation/force_garbage_collection.ts
src/core/stream/representation/push_init_segment.ts
src/core/stream/representation/push_media_segment.ts
src/core/stream/representation/representation_stream.ts
src/experimental/tools/VideoThumbnailLoader/get_initialized_source_buffer.ts
src/experimental/tools/VideoThumbnailLoader/push_data.ts
src/experimental/tools/VideoThumbnailLoader/remove_buffer_around_time.ts
src/utils/task_canceller.ts

This is yet another PR to remove RxJS from parts of the code to raise the RxPlayer's "approachability", after #962 (for the transports code), #1042 (the content decryption code) and #1091 (from the adaptive code).
This time, this is the turn of a relatively smaller part of the code: the "SegmentBuffers (in `src/core/segment_buffers`) which is the code wrapping browser's buffers (or even implementing them in the case of subtitles and image buffers).
Like the other PR before it, this one makes heavy usage of:
- `ISharedReference` objects, which are very similar to RXJS BehaviorSubjects (always-set Observable values which are not lazy and can be `get`ted at any time) to easily share values between blocks while allowing to trigger a callback when its inner state changes.
- `TaskCanceller` and …

Remove RxJS from the SegmentBuffer and related code

---

demo/full/scripts/modules/player/catchUp.js
demo/full/scripts/modules/player/events.js
doc/api/Basic_Methods/getPlayerState.md
doc/api/Basic_Methods/pause.md
doc/api/Player_States.md
src/core/api/__tests__/get_player_state.test.ts
src/core/api/get_player_state.ts
src/public_types.ts
tests/integration/scenarios/dash_multi-track.js
tests/integration/scenarios/dash_multi_periods.js

As already discussed internally at Canal+, this PR adds the `"FREEZING"` player state to the RxPlayer, for specific cases where enough data has been buffered but playback is still not advancing due to an unknown reason.
Previously, that state was either reported as `"BUFFERING"` or as `"PLAYING"` depending on other HTMLMediaElement's attributes.
We decided to add this new state (only in V4 as this is a breaking change), for the following reasons:
- this is a situation where an interface might want to display what it does for regular `"BUFFERING"`, like a spinner (this is for the case that was previously categorized as `"PLAYING"`)
- an application might want to report when that state is happening - and differentiate it from a `"BUFFERING"` - to help investigate issues in production
- …

[V4] Add FREEZING state

---

doc/Getting_Started/Tutorials/Content_with_DRM.md
doc/api/Loading_a_Content.md
doc/api/Miscellaneous/Initial_Position.md
doc/api/Miscellaneous/Local_Contents.md
doc/api/Miscellaneous/Local_Manifest_v0.1.md
doc/api/Miscellaneous/Low_Latency.md
doc/api/Miscellaneous/MetaPlaylist.md
doc/api/Miscellaneous/plugins.md
doc/api/Player_Errors.md
doc/api/Typescript_Types.md
doc/reference/API_Reference.md
src/core/api/__tests__/option_utils.test.ts
src/core/api/option_utils.ts
src/core/api/public_api.ts
src/public_types.ts
tests/integration/scenarios/dash_live_utc_timings.js
tests/integration/scenarios/dash_static.js
tests/integration/scenarios/loadVideo_options.js
tests/integration/utils/launch_tests_for_content.js

Proposal update for the future V4 where we "flatten" the `transportOptions` `loadVideo` option, i.e. all options that were before properties of the `transportOptions` are now directly property of the `loadVideo` API.
This was done because the `transportOptions` was more of an implementation detail that a real API concept and what or what should not be in it was unclear. Sometimes even us had troubles knowing if an option was part of the `transportOptions` object.

[V4] Flatten transportOptions loadVideo option

---

src/utils/request/xhr.ts

We noticed today that on some LG TVs, setting a timeout through a `XMLHttpRequest`'s `timeout` property didn't have any effect.
The browser version was recent enough, so it seems more of an issue either due to a bug in the specific browser version integrated there or linked to an issue brought during the integration of the browser on the TVs.
Anyway, I propose to add a manual timeout to support the "native" one in the case where it would fail, to completely avoid issues which can be problematic enough:
To give an example of such problematic situations, we were investigating a case where it appeared that some CDN just - relatively rarely - chose to hang requests forever.
Without any effective timeout solution, this could just lead to infinite rebuffering as the RxPlayer would just wait for …

Add timeout manually on XMLHttpRequests to take place of native one as a fallback

---

src/core/api/playback_observer.ts
src/core/init/initialize_directfile.ts
src/core/init/load_on_media_source.ts
src/core/init/stall_avoider.ts
src/core/segment_buffers/implementations/text/html/html_text_segment_buffer.ts
src/core/stream/representation/get_buffer_status.ts
src/default_config.ts
tests/integration/utils/launch_tests_for_content.js

__UPDATE: automatic gap-jumping has been re-established when the media element is paused, as not doing it may prevent discontinuities skip when the content is `LOADING` or `RELOADING`. In any case, only doing it when the application explicitely set the `playbackRate` at `0` or at a negative number seems logical and sufficient.__
An application using the RxPlayer to implement a frame-to-frame feature where it's possible to go forward or backward, and also a fake reverse playback, based on multiple very close seeks at a quick interval, is having issues when seeking a very small amount of time backward at the start boundary of a segment.
Once that boundary is reached, seeking back a very small amount of time (let's say 0.04 second), actually lead to the RxPlayer seeking back automatically to …

Better handle reverse playback by not skipping very small holes when paused

---

src/core/api/tracks_management/media_element_track_choice_manager.ts

We saw an issue when playing HLS through the RxPlayer by using the `"directfile"` mode - where audio-description audio tracks weren't advertised as such despite the HLS MultivariantPlaylist having the corresponding information.
After a brief investigation, it seems that this is because Safari wrongly set (only sometimes? not sure) an `AudioTrack`'s kind to `"description"` [instead of the `"descriptions"` (with an s) that should probably be set in that
case](https://html.spec.whatwg.org/multipage/media.html#value-track-kind-descriptions).
Anyway, seeing `"description"` in singular form is not ambiguous, so it should not be breaking anything if we also support it.
Though in my opinion, Safari should probably just fix that thing (issue to open?) and a player should generally [not try to be …

Also consider an AudioTrack with a `kind` set to `"description"` as audio description

---

doc/Getting_Started/Tutorials/Content_with_DRM.md
doc/api/Decryption_Options.md
doc/api/Typescript_Types.md
doc/reference/API_Reference.md
src/core/decrypt/__tests__/__global__/media_key_system_access.test.ts
src/core/decrypt/content_decryptor.ts
src/core/decrypt/find_key_system.ts
src/core/decrypt/get_media_keys.ts
src/core/decrypt/utils/persistent_sessions_store.ts
src/public_types.ts

This PR simplifies and gives a better name to API relative to persistent licenses.
Previously, an application needed to set both a `persistentLicense` property to `true` and a `licenseStorage` object - which in reality does not store any license but identifiers allowing to retrieve MediaKeySessions persisted by the browser/CDM - to profit from persistent licenses.
This PR removes the need of setting the former (as long as the latter is set) and rename the latter to `persistentLicenseConfig`, thus both correcting the "wrongness" of the previous API but also removing notion of "storage" to pave the way for potential supplementary options in it (like we already did with the `licenseConfig.disableRetroCompatibility` boolean).
Of course, this is a breaking chang and is thus planned for V4

[V4] DRM: Remove persistentLicense keySystems option and rename licenseStorage to persistentLicenseConfig

---

doc/api/Basic_Methods/reload.md
src/core/api/public_api.ts
tests/integration/utils/launch_tests_for_content.js

Fixes #1159
The `reload` method is a method allowing to load again - and generally more optimally - the last loaded content, even if the player was stopped before the `reload` call.
As we know it, this method is mainly used to restart loading a content even if an unusual and fatal error happened during playback.
By default, this method re-considered all options given to the initial `loadVideo` call, with the exception of the `startAt` API - where the last known position was considered instead. It was also possible to signal a wanted initial position on the `reload` call.
As #1159 suggested, we also should have put more considerations into the `autoPlay` setting. Whereas until now we only considered the `autoPlay` setting of the last `loadVideo` call, it seems to make more sense to respect …

Add autoPlay `reload` option and improve autoplay default logic in it

---

demo/full/scripts/components/Options/AudioAdaptiveSettings.jsx
demo/full/scripts/components/Options/VideoAdaptiveSettings.jsx
demo/full/scripts/controllers/Settings.jsx
doc/api/Creating_a_Player.md
doc/reference/API_Reference.md
src/core/api/__tests__/option_utils.test.ts
src/core/api/option_utils.ts
src/core/api/public_api.ts
src/default_config.ts
src/public_types.ts

This commit removes both `initialAudioBitrate` and `initialVideoBitrate` APIs, replacing it by just a `baseBandwidth` API.
`baseBandwidth` should be set to a global bandwidth estimate of the user.
If, for the upcoming v4, the other commits related to bitrate APIs are all merged, this would have been the last documented APIs forcing the RxPlayer to separate audio and video bandwidth calculations.
I propose removing it for the following reasons:
- Applications used it for the wrong reasons for the most part:
thinking the set value will correlate exactly to the first video or audio segments seen by the user.
In reality, things are much more complex. True bandwidth calculations could be performed before pushing the initially-played media segments, fast-switching could replace an …

[Proposal] [v4] Remove initialVideoBitrate and initialAudioBitrate, add baseBandwidth

---

src/compat/__tests__/enable_audio_track.test.ts
src/compat/enable_audio_track.ts
src/compat/index.ts
src/core/api/tracks_management/media_element_track_choice_manager.ts

We noticed an issue on some Samsung TVs where some (but not all) directfile contents were playing without sound.
After investigation, it seems that what breaks was the action of disabling __ALL__ of an `HTMLMediaElement`'s audio tracks before enabling the one wanted, which is something we did (instead of just disabling the unwanted tracks first) due to a playback issue on Safari which would happen without (Safari would just decide to not play).
So basically, an ugly-but-functional-and-still-logically-sound work-around fixed Safari but broke Tizen.
In the end, I chose to keep the ugly-but-functional-... solution by default and just perform the original not-ugly solution for Tizen, because it seems to me there's more chance to re-encounter the Safari issue (e.g. because another device rely …

Fix directfile audiotrack selection on Tizen

---

doc/api/Player_Events.md
src/core/api/public_api.ts
src/core/api/track_management/tracks_store.ts
src/public_types.ts

Until now, the RxPlayer v4.0.0 was scheduled to introduce the `autoTrackSwitch` event to signal that the track of any type (audio, video, text...) and Period had to be changed automatically by the RxPlayer (for now the only - improbable - case is when the corresponding track just disappears after a Manifest update - e.g. the corresponding `AdaptationSet` element is removed from a DASH MPD).
This event was needed to perfectly replace the track preferences and bitrate APIs - which are removed from the v4.0.0 for more powerful API - as the track and wanted Representations would without this event just silently be updated by the RxPlayer, without the application knowing about it and being able to react upon it.
But after some tests, it seems that adding a much more general `trackUpdate` …

[v4] Replace autoTrackSwitch event by a more useful trackUpdate event

---

src/compat/__tests__/can_reuse_media_keys.test.ts
src/compat/__tests__/should_renew_media_key_system_access.test.ts
src/compat/browser_detection.ts
src/compat/can_reuse_media_keys.ts
src/compat/index.ts
src/compat/should_renew_media_key_system_access.ts
src/core/decrypt/__tests__/__global__/media_keys.test.ts
src/core/decrypt/__tests__/__global__/utils.ts
src/core/decrypt/find_key_system.ts
src/core/decrypt/get_media_keys.ts

We noticed of an issue on WebOS (LG TV) 2021 and 2022 models where loading an already-loaded encrypted content would not succeed: it would load indefinitely.
After investigation, nothing in the JavaScript code seemed to go wrong, licences were loaded, but nothing was playing.
However, we found out that re-creating the `MediaKeys` instance at each zap completely fixed the issue, with the cost of potential longer loading time (not measured yet).
This seems to be an issue linked to LG's software and we will share to them what we found, but we still chose to preemptively do a work-around specifically for WebOS 2021 and 2022 models so it works even know.
If the issue become fixed in the future, we may remove that work-around.
The major part of this commit are added tests on the code handling …

Re-create MediaKeys at each loadVideo on WebOS

---

src/core/api/playback_observer.ts
src/core/api/public_api.ts
src/core/init/emit_loaded_event.ts
src/core/init/stall_avoider.ts

This commit fixes an issue we encountered sometimes with rare directfile
contents, especially on recent Chrome versions and also on the PlayStation
4's WebKit-based one where the RxPlayer would stay in the `LOADING` state
after loading a directfile content, despite the fact that the player is
actively playing the content.
This issue is due to the fact that when playing some directfile
contents, the `buffered` property of the video/audio element stay empty
even when data is obviously buffered as playback is going on.
The RxPlayer then uses that `buffered` property to check if enough data
is buffered to begin playback or go into a `BUFFERING` phase. When
empty, The RxPlayer considers that no data is buffered and that it
should wait until data around the wanted position is before …

 Avoid staying in LOADING/BUFFERING/SEEKING state in directfile when nothing is buffered

---

doc/api/Player_Events.md
doc/api/Track_Selection/getAvailableTextTracks.md
doc/api/Track_Selection/getPreferredTextTracks.md
doc/api/Track_Selection/getTextTrack.md
doc/api/Track_Selection/setPreferredTextTracks.md
src/core/api/tracks_management/track_choice_manager.ts
src/manifest/adaptation.ts
src/parsers/manifest/dash/common/parse_adaptation_sets.ts
src/parsers/manifest/types.ts
src/public_types.ts
tests/contents/DASH_static_SegmentTimeline/forced-subtitles.js
tests/contents/DASH_static_SegmentTimeline/index.js
tests/contents/DASH_static_SegmentTimeline/media/forced-subtitles.mpd
tests/contents/DASH_static_SegmentTimeline/urls.js
tests/integration/scenarios/dash_forced-subtitles.js

This PR implements DASH forced-subtitles that are subtitles defined for when no other subtitle track is selected.
The idea is often to implement "Forced Narrative Subtitles" which allows to provide clarifications on different element in the screen. You can read more information on it here for example: https://partnerhelp.netflixstudios.com/hc/en-us/articles/217558918-Understanding-Forced-Narrative-Subtitles
With this PR, those text tracks will now have a `forced` attribute set to `true` in the various APIs where it is inspectable (`getAvailableTextTracks`, `getTextTrack` and the events `textTrackChange` and `availableTextTracksChange`).
Moreover, they are used as default text tracks, instead of no text track, when no set preference match the current choice, following a specific rule:
- If …

DASH: implement forced-subtitles

---

src/core/decrypt/__tests__/__global__/media_key_system_access.test.ts
src/core/decrypt/__tests__/__global__/utils.ts
src/core/decrypt/find_key_system.ts
src/default_config.ts

Quick Pull Request as we were debugging PlayReady issues to by default use the now recommended `"com.microsoft.playready.recommendation"` key system when only "playready" is asked for through the `keySystems[].type` property.
A second improvement performed here is to by default ask for `"3000"` then `"2000"` audio and video robustnesses when the current keysystem wanted is `"com.microsoft.playready.recommendation"`.
This greatly simplify the usage of SL3000 for applications just asking for `"playready"`

DRM: Request PR recommendation when PlayReady is asked and try default recommendation robustnesses

---

src/parsers/manifest/dash/common/parse_representations.ts
src/parsers/manifest/types.ts
tests/integration/scenarios/loadVideo_options.js

Fixes #1190
We brought in the last v3.29.0 a regression which made it impossible to play a DASH content in very specific conditions.
Thankfully, the conditions to reproduce it are relatively rare and easy to work-around (as written in the issue). Basically it only happens when all following conditions are true:
1. You're playing a DASH content
2. You didn't communicate an `url` for the MPD (for now only works if you at least communicated either a `initialManifest` or a `manifestLoader`)
3. You didn't communicate about the MPD URL in the `manifestLoader` if you used one
4. The MPD does not contain any `<BaseURL>` element, or it does but only inside `<Representation>` elements (which means basically directly for each segments, e.g. in a `<SegmentList>` element).
When those conditions are …

Fix segment requesting error when playing a DASH content without an url and without BaseURL elements

---

doc/api/Content_Information/.docConfig.json
doc/api/Content_Information/updateContentUrls.md
doc/reference/API_Reference.md
src/core/api/public_api.ts
src/core/fetchers/manifest/manifest_fetcher.ts
src/core/init/directfile_content_initializer.ts
src/core/init/media_source_content_initializer.ts
src/core/init/types.ts

This commit adds the `updateContentUrls` API allowing to update at any time and during playback, the URL through which a content's Manifest is reached.
This may be used anytime an application prefer a new Manifest URLs to be used, whether it is because the previous URL will soon expire, because the new URL is seen as more qualitative or to rebalance load.
The first argument given to `updateContentUrls` is actually an array of strings, listing new URLs from the most prioritized to the least prioritized. This is not used for now, but should soon be used to define fallback URLs when former one fail to fetch the resource.
`updateContentUrls` can be given a second argument named `refreshNow` which can be used to ask the RxPlayer to refresh immediately the Manifest behind the given URL.
For …

Add `updateContentUrls` API

---

src/core/adaptive/adaptive_representation_selector.ts
src/core/stream/adaptation/adaptation_stream.ts

A `NO_PLAYABLE_REPRESENTATION` error is what happen if fallbacks are enabled for encrypted contents but all qualities have been fallbacked from.
We had a race conditions if that situation arised before setting the corresponding track (I'm not too sure when this does happen but it did) where a random JS error (along the lines of "cannot read the property bitrate of undefined") i would be sent as an error nstead of the expected `NO_PLAYABLE_REPRESENTATION` error.
This race condition was linked to our handling of RxJS, so I'm unsure if it's still reproducible on our current `dev` branch (as we've removed RxJS from the source code since then). Still, I added in this PR supplementary checks and resilience code that would handle this situation should it ever happen again.
I chose to write the …

Fix race condition leading to a JS error instead of a NO_PLAYABLE_REPRESENTATION

---

doc/api/Content_Information/getKeySystemConfiguration.md
doc/api/Deprecated/getCurrentKeySystem.md
doc/api/Miscellaneous/Deprecated_APIs.md
doc/reference/API_Reference.md
src/compat/__tests__/should_reload_media_source_on_decipherability_update.test.ts
src/compat/should_reload_media_source_on_decipherability_update.ts
src/core/api/public_api.ts
src/core/decrypt/get_key_system_configuration.ts
src/core/decrypt/index.ts
src/core/init/media_source_content_initializer.ts
src/public_types.ts

Encryption-related issues are the most frequent category of issues currently investigated by the RxPlayer team and its associated applications at least made by Canal+ and our partners.
In that context, we missed a crucial API allowing to facilitate encryption-related debugging on various platforms: One that would allow to indicate easily the current key system configuration relied on.
Particularly the robustness level: PlayReady SL3000 or SL2000? Widevine L1, L2 or L3? And so on.
The present PR adds the `getKeySystemConfiguration` API which returns both the **actual** key system string and the
[`MediaKeySystemConfiguration`](https://www.w3.org/TR/encrypted-media/#dom-mediakeysystemconfiguration) currently relied on.
I put there an emphasis on "actual" because, in opposition to the …

Add the `getKeySystemConfiguration` method to the RxPlayer

---

doc/api/Buffer_Information/.docConfig.json
doc/api/Creating_a_Player.md
doc/api/Decryption_Options.md
doc/api/Deprecated/.docConfig.json
doc/api/Deprecated/getVideoLoadedTime.md
doc/api/Deprecated/getVideoPlayedTime.md
doc/api/Deprecated/isFullscreen.md
doc/api/Loading_a_Content.md
doc/api/Miscellaneous/Deprecated_APIs.md
doc/reference/API_Reference.md
src/core/api/option_utils.ts
src/core/api/public_api.ts

To make sure that some API planned to be removed in the incoming v4 aren't still in use and/or haven't a use we didn't realize until now, I chose to deprecate some of them in the next v3.30.0 minor version.
The v4 is still planned to stay a long time in beta and we still plan to maintain the v3 as long as needed for our close partners, but deprecating options also in the v3 ensure we're not breaking use-cases for people with not enough resource to make the switch for the v4 beta by putting more visibility on those API (console.warn call, deprecation documentation etc.).
The following API are here deprecated:
- The `getVideoLoadedTime` method
- The `getVideoPlayedTime` method
- The `transportOptions.aggressiveMode` property of `loadVideo`
- The `keySystems[].onKeyStatusesChange` callback …

Deprecate methods and options removed in the future v4

---

src/parsers/manifest/dash/common/parse_representations.ts

This PR allows to signal HDR AdaptationSets through the API - thanks to the `hdrInfo` property added in v3.26.0 (june 2021) - when an `EssentialProperty` or `SupplementalProperty` element with its `schemeIdUri` attribute is set to `"urn:mpeg:mpegB:cicp:TransferCharacteristics"`.
This is as specified in both the `6.2.5.1` and `10.2.3.4` chapters of the DASH-IF IOP v4.3 the way that transfer function differences between AdaptationSets should be signaled when you have an MPD with both HDR and SDR Adaptation Sets.
For now, only the "eotf" (the transfer function) is parsed (though we could also technically parse the `ColourPrimary` and `MatrixCoefficients` parts of those chapters later).
The goal is to allow an application to detect when multiple AdaptationSets are present which corresponds to …

DASH: parse `transferCharacteristics` property to better detect hdr

---

src/core/decrypt/session_events_listener.ts
src/core/fetchers/segment/task_prioritizer.ts
src/core/fetchers/utils/schedule_request.ts
src/core/init/media_source_content_initializer.ts
src/core/init/utils/create_media_source.ts
src/core/segment_buffers/implementations/audio_video/audio_video_segment_buffer.ts
src/core/segment_buffers/segment_buffers_store.ts
src/experimental/tools/VideoThumbnailLoader/prepare_source_buffer.ts
src/transports/dash/add_segment_integrity_checks_to_loader.ts
src/transports/local/segment_loader.ts
src/utils/cancellable_sleep.ts
src/utils/create_cancellable_promise.ts

In #1213, I fixed a memory leak by making sure that cancellation logic was unregistered as soon as possible. Without that work, cancellation-linked callbacks were most of the time kept in-memory until the corresponding `CancellationSignal` actually emits, which was sometimes only after a very-long-lived task (for example when the corresponding `TaskCanceller` was linked to the playback of the whole content).
Turned out the most frequent case where we want to unregister cancellation logic was when using Promises (other cases are very often long-lived task which don't actually finish until cancellation - those do not need such clean-up).
When relying on Promises, the cancellation architecture is most of the time very similar: we generally want to reject if a `CancellationSignal` emits …

Add createCancellablePromise util

---

src/core/stream/orchestrator/stream_orchestrator.ts

There is no need to do that (there's nothing to fallback from for example) and it may lead to request being needlessly restarted.

DRM/Stream: do not needlessly restart Streams when Representations become known to be decipherable

---

src/core/init/utils/media_duration_updater.ts

I found out that the video element's `duration` property for live contents was sometimes very close to the maximum position, whereas it should be set to very high number for such types of contents.
The reason behind this issue was very clear: the `MediaDurationUpdater` only performed a live-specific logic when the current tracks' duration are initially not known whereas it should do it everytime the duration may need to be updated.

For dynamic contents, always set a very high duration

---

.eslintrc.js
package-lock.json
package.json
src/core/decrypt/session_events_listener.ts
src/core/fetchers/utils/schedule_request.ts
src/experimental/tools/VideoThumbnailLoader/video_thumbnail_loader.ts
src/transports/dash/add_segment_integrity_checks_to_loader.ts

Starting with the for-now-unreleased `v3.30.0` release, due to the fact that we completely removed RxJS from the code, we started relying much more on Promises and on its related methods.
After encountering a curious issue on Panasonic TVs while investigating #1219, we saw that the `finally` method on Promises was poorly supported on some devices, and to our surprise even if a Promise polyfill was added.
After evaluating what we could do, I decided to just ban the `finally` method from the RxPlayer code and replace it by duplicating its logic in Promises' resolve and failure handlers.
To ensure that those methods are not used on future developments, I also added an eslint rule (and plugin) to ban the `finally` method. Sadly, this plugin does not check if a `finally` method call is …

Avoid using Promise.prototype.finally to better support older devices

---

src/compat/browser_detection.ts
src/compat/can_reuse_media_keys.ts
src/core/decrypt/__tests__/__global__/utils.ts
src/core/decrypt/find_key_system.ts
src/default_config.ts

An issue, #1219, noticed several problems preventing from playing encrypted content on Panasonic 2019 TVs:
- Though it advertises for widevine L1 support, it does not support any {video,audio}Capabilities' robustness.
To fix this, I chose to re-bring the legacy work-around of adding a supplementary MediaKeySystemConfiguration without any {audio,video}Capabilities
- Playing multiple encrypted contents through the same RxPlayer instance causes playback issues.
This seems similar to issue we have on LG TVs. The work-around of re-doing EME negotiation from MediaKeys creation for each content also works here.
To implement the second work-around, I updated the browser detection code (using an IIFE). To detect Panasonic devices, I've been voluntarily large - only spotting a "panasonic" substring …

Support Panasonic 2019 TVs

---

src/compat/browser_detection.ts
src/compat/get_live_content_duration.ts
src/core/init/utils/media_duration_updater.ts

We recently noticed an issue on the PS5 which causes stuttering playback on live contents.
After exchanging with Sony, turns out the root cause is that their new WebKit version has performance troubles in its segment data eviction logic when the current `MediaSource`'s duration is set at a high value.
For live contents, we set in most cases (there are rare exceptions) the duration to 2^32, because higher values may cause issues on other platforms (most notably Tizen). To us, it didn't seem as a very high value but Sony actually advised us to use positive `Infinity` instead (a valid IEEE 754 value that can be set in JavaScript for a "Number"), as it seems to be handled specially by WebKit.
`Infinity` is also the actual value advised by the current HTML living standard for live contents, …

Set `Infinity` as duration when playing live contents on the PS5

---

src/parsers/manifest/dash/wasm-parser/ts/dash-wasm-parser.ts

I forgot to add a line on the implementation of the `DASH_WASM.initialize` API (which allows to "initialize", i.e. load and compile the linked WebAssembly file, the WASM-based DASH parser) which led to the Promise returned by this method still resolving even if the initialization failed.
The error was still logged and the internal status of the `DASH_WASM` feature was still updated to indicate failure, but that's not what the application is most likely listening to.

DASH/WASM: actually reject the DASH_WASM.initialize's Promise if it fails

---

src/core/stream/orchestrator/stream_orchestrator.ts

While doing some debugging on multi-Period contents, we saw some situations where at some Period's boundary, no segment would be loaded, since the `v3.30.0`.
Though we are still in the process of testing it, I relatedly found what seems like an issue where we could be in some kind of (slow) loop creating and destroying `PeriodStream`, which is the module allowing to load segment corresponding to a particular DASH period (or related in other `transport`s) when we approach from the end of the previous Period.
To try to fix this logic, I added a check to see if the next `PeriodStream` wanted was linked to the same `Period` than the next `PeriodStream` which was already created, in which case we won't be destroying it immediately, just to re-creating it like we did before.
For the source of …

Avoid destroying PeriodStream if one is re-created for the same period

---

src/core/api/tracks_management/media_element_track_choice_manager.ts
src/core/api/tracks_management/track_choice_manager.ts
src/public_types.ts

This update only concerns directfile contents, especially when playing HLS contents on safari.
---
As of now, no real standard exists to indicate through an HTML Text Track object whether that track represents "forced" subtitles.
There's been some proposal since 2013
(https://lists.whatwg.org/pipermail/whatwg-whatwg.org/2013-April/039374.html) to add the possibility to set the `kind` attribute of a `TextTrack` to `"forced"` but nothing has yet materialized in what is now the WHATWG HTML standard.
There's some very interesting discussion more "recently" in a whatwg Github issue here: https://github.com/whatwg/html/issues/4472 (note: I'm more aligned with Nigel Megitt opinions on those things) but again it did not really materialize into something yet.
Yet Webkit, and by extension Safari, …

Detect forced subtitles on Safari in directfile (and label)

---

src/compat/browser_detection.ts
src/compat/has_issues_with_high_media_source_duration.ts
src/core/init/media_source_content_initializer.ts
src/core/init/utils/media_source_duration_updater.ts

The Playstation 5 have issues when the `MediaSource`'s `duration` property is set to a very high value (playback freezes) but not when setting it to `Infinity`, which is what the HTML spec as of now recommends for live contents.
However setting the `MediaSource`'s `duration` property to `Infinity` seems more risky, considering all platforms we now support,  than setting it at a relatively high 2^32 value which is what we do generally.
Moreover, setting it to `Infinity` require us to use another MSE API, `setLiveSeekableRange` to properly allow seeking. We're used to MSE issues so I'm not too confident of using another MSE API for all platforms directly.
So I added a new method in `compat`, returning `true` based on a whitelist of platform for which
it has been detected that high …

On the PlayStation 5, set Infinity MediaSource duration for live contents

---

demo/full/index.html
demo/full/scripts/components/GitHubButton.tsx
demo/full/scripts/controllers/Main.tsx
demo/full/styles/style.css
package-lock.json
package.json

The demo page uses https://buttons.github.io/ for the `Star` and `Fork` buttons of the header, redirecting to the GitHub repo.
As the page is now built with React, the buttons are not present in the DOM when the script in the `<head/>` is executed, hence the buttons not being styled.
The issue is described [here](https://github.com/buttons/github-buttons/issues/66), and the recommendation is to use a React wrapper like the official [react-github-btn](https://github.com/buttons/react-github-btn). The component was working well but caused TSLint errors as it was probably incorrectly typed (Issue described [here](https://github.com/buttons/react-github-btn/issues/9)).
I implemented a similar wrapper as a React Functional Component, including our default values to lighten `Main.tsx`.
Its …

Demo Header: Add GitHubButton component to replace script in head

---

src/core/init/media_source_content_initializer.ts

Some RxPlayer users had an issue of unaudible audio after an audio track switch on Chrome when the `audioTrackSwitchingMode` option was set to `"direct"` (meaning that the track switch will happen - roughly - in place after a small rebuffering the time to load the new audio segments).
That issue seems to be at the browser-level (or may even be at a lower level), but as it can be prevented in the RxPlayer with no much disadvantage, it is still a win to work-around it at the RxPlayer-level.
---
Lately, while PoCing an HLS media player personal project, I tried a new technique which seems to fix this issue reliably.
When changing the audio track, here's the new behavior in my PoC:
1. The application switches the audio track through the player's API
2. The player stop loading the old audio …

Improve `"direct"` audioTrackSwitchingMode compatibility by re-seeking

---

doc/api/Player_Errors.md
package-lock.json
package.json
src/core/api/debug/render.ts
src/core/api/tracks_management/track_choice_manager.ts
src/core/segment_buffers/index.ts
src/core/stream/adaptation/utils/create_representation_estimator.ts
src/core/stream/period/period_stream.ts
src/core/stream/representation/utils/append_segment_to_buffer.ts
src/core/stream/representation/utils/push_init_segment.ts
src/errors/__tests__/media_error.test.ts
src/errors/index.ts
src/errors/media_error.ts
src/manifest/__tests__/period.test.ts
src/manifest/adaptation.ts
src/manifest/index.ts
src/manifest/manifest.ts
src/manifest/period.ts
src/manifest/representation.ts
src/public_types.ts
src/transports/smooth/isobmff/create_boxes.ts

This PR adds a `trackInfo` property to `MediaError` errors when its `code` property is set to either:
  - `"NO_PLAYABLE_REPRESENTATION"` (unplayable track based on DRM policy non-compliance),
  - `"MANIFEST_INCOMPATIBLE_CODECS_ERROR"` (track with unsupported codec),
  - `"BUFFER_APPEND_ERROR"` (error while pushing a segment)
  - `"BUFFER_FULL_ERROR"` (error while pushing a segment which seems specifically linked to that buffer not having enough memory space left) 
 That `trackInfo` property provides characteristics about the track linked to the error. For example, the video track's characteristics when a `BUFFER_APPEND_ERROR` is linked to a video segment.
---
The idea here mainly is  to allow applications to develop much more powerful error management logic:
- allowing logs of better …

Add `trackInfo` property to some `MediaError`

---

doc/api/Player_Events.md
src/core/api/public_api.ts
src/public_types.ts

While migrating some Canal+ application to the future v4.0.0 version, I noticed that an event, triggered when the list of available `Representation`s associated to a currently-chosen track changed, was missing.
---
Let's consider for example an application logic which stores information on the currently available qualities (so `Representation`) of the current video track.
With the `v4` it can constructs its list any time the video track is initially set or changes for any Period, simply by respectively listening to the `newAvailablePeriods` event (for when it is initially set) and to the `trackUpdate` event (for when it is changed).
This seems sufficient at first.
But now let's consider that we're playing encrypted contents, and that one of the `Representation` of those current video …

Add `representationListUpdate` event for the v4

---

doc/api/Player_Events.md
src/core/api/public_api.ts
src/core/api/track_management/track_dispatcher.ts
src/core/api/track_management/tracks_store.ts
src/public_types.ts

In the v3.x.x, the impossibility to play any `Representation` from a chosen track due to non-usable keys, lead to an error with the `NO_PLAYABLE_REPRESENTATION` error code .
This seemed sensible at the time, but we're now encountering use cases where it would be more sensible to change the current track instead, to one that perhaps has decipherable Representation(s).
The main example would be to have a separate video track linked to to another dynamic range (e.g. an HDR and a SDR track) each with different security policies (tracks with higher dynamic range would have more drastic security policies for example). Here, I would guess that an application would prefer that by default we switch to the SDR video track if no
`Representation` in the HDR one is decipherable, instead of just …

Improve `NO_PLAYABLE_REPRESENTATION` behavior for the v4

---

src/core/adaptive/__tests__/buffer_based_chooser.test.ts
src/core/adaptive/adaptive_representation_selector.ts
src/core/adaptive/buffer_based_chooser.ts
src/core/adaptive/guess_based_chooser.ts
src/core/adaptive/network_analyzer.ts
src/core/adaptive/utils/representation_score_calculator.ts
src/default_config.ts
src/utils/is_null_or_undefined.ts

__EDIT: After some tests, I decided to also limit switch in the buffer-based algorithm (based on BOLA) through special mechanisms.__
We noticed that some final users of the RxPlayer had a lot of quality switches: e.g. the video quality raised and lowered frequently (in a few seconds).
In most cases, this lead to poor experience, on some devices, such as some Samsung TVs, it also seems to create some visual glitches.
Consequently we decided to propose a development that we long though about: trading higher quality stability for less perceived quality accuracy, especially by being more on the pessimistic-side to prevent rebuffering while doing that.
 
Here are the exact changes proposed in this PR:
- Everytime we raise up in quality, we now do it non-urgently, meaning that we wait for the …

ABR: Try reducing the frequency of potential quality switches

---

doc/api/Player_Events.md
src/core/api/public_api.ts
src/core/api/utils.ts
tests/integration/utils/launch_tests_for_content.js

As I've been working a lot more with application code (media player UIs) lately, I saw that a real concept of whether playback was playing or paused was missing in the RxPlayer API.
You could approximate it by getting the player's state, but some states, like `"BUFFERING"` or `"LOADING"`, even if they indicate that playback is not happening right now, do not indicate whether we're actually paused or not.
For example, once the buffering period is over, will we play directly or still be paused? Or, after `"LOADING"`, will we play or just be paused on the first loaded frame?
One area where this concept is central to an application is for example to know whether the "play/pause" button should currently play or pause, which also dictates what the button should look like: if we're playing, this …

Add `"play"` and `"pause"` events

---

src/core/init/directfile_content_initializer.ts
src/core/init/media_source_content_initializer.ts
src/core/init/utils/rebuffering_controller.ts

Note: This may be a controversial PR :p, don't hesitate to exchange here if you see problem with this logic or if you have ideas for improving it.
This should only impact contents relying on DRM.
---
The majority of our bugs are now DRM-related and device-specific, generally platform lower-level (CDM, browser integration...) bugs. Even if we very frequently exchange with partners to obtain fixes, this is not always possible (sometimes because there are too many people relying on the older logic and thus risks in changing it, sometimes because there are a lot of higher priorities on their side).
We are now encountering frequently, for some contents with DRM, what we call a "playback freeze": playback does not advance despite having data in the buffer, all being known to be decipherable (we …

DRM: Reload when playback is unexpectedly frozen with encrypted but only decipherable data in the buffer

---

src/core/init/media_source_content_initializer.ts
src/core/stream/adaptation/adaptation_stream.ts
src/core/stream/adaptation/types.ts
src/core/stream/orchestrator/stream_orchestrator.ts
src/core/stream/period/period_stream.ts

This commit performs a small modifications so that the `Stream` module, when asking for the current content to be "reloaded" (that is: to replace its MediaSource, generally both for compatibility reasons and to ensure buffers are flushed), no longer needs to both calculate the position to reload to nor if it should auto-play after the reload.
This is a simplification of a "reload" event from the point of view of the `Stream`. A "reload" there now is mostly done "in-place" (with a possible time offset to apply, e.g. to re-play the last second after changing the audio track, the `Stream` could be asking for a `timeOffset` of `-1`) and playback characteristics are mostly kept as they were before the reload.
The position and playing status is now computed by the …

Decide the position and autoplay status of a Reload in the Initializer

---

src/core/stream/representation/utils/get_buffer_status.ts

The RxPlayer usually loads only media segments containing media data from the current playback position onward.
However, there is an exception to that rule: for the last segment of the content it is possible to load it even if it ends before the current playback position (this may happen for example when audio data ends before video data, and then seeking at the end of the video data, here we may load the last audio segment even if it ends before the current position).
This is done to better handle the ending logic of malformed contents. The browser provides the [`endOfStream`](https://developer.mozilla.org/en-US/docs/Web/API/MediaSource/endOfStream) EME API. Calling this API allows to indicate that the last segments have been pushed which then lead to HTML5 "ended" support (both the …

Only load the last audio and video segments of a content when seeking after it

---

src/compat/__tests__/should_wait_for_have_enough_data.test.ts
src/compat/index.ts
src/compat/should_wait_for_have_enough_data.ts
src/core/init/utils/get_loaded_reference.ts

We noticed that on a PlayStation 5, an `HTMLMediaElement`'s [`readyState`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/readyState) property can switch to `3` even if the content is encrypted and its decryption key hasn't be obtained yet.
This is unusual (we usually encounters a `readyState` of `1` in that case) and perhaps not compliant to the WHATWG HTML5 standard. More importantly, it might cause the RxPlayer to switch to the `LOADED` state too soon, before switching to a `BUFFERING` state until the key is obtained (whereas it is expected that the RxPlayer can play immediately after reaching the `LOADED` state).
Thankfully, a simple work-around can be applied on this case: we know that on the PlayStation 5, we'll always reach a `readyState` of `4` as soon as we can …

PS5: wait for a readyState of `4` before considering the content loaded

---

src/core/adaptive/adaptive_representation_selector.ts

I just found out an issue that may be here for some time when calling `setVideoBitrate` and `setAudioBitrate` in `"seamless"` `manualBitrateSwitchingMode` (which sadly is the mode by default - though not the one by default in the demo page).
Calling it work for a time but after some time, we may still raise in quality if the buffer grows.
Turns out, the buffer-based algorithm still has an influence over the choice of Representation when a bitrate is forced manually because I forgot to cancel it (no risk of leak though - it only happen in this scenario).
I tried a first simple solution which is to just resetting the `onAddedSegment` callback to a noop function when we cancel the auto mode (such as when bitrate choice switches to manual), though this means that when bitrate choice is back …

Fix setVideoBitrate and setAudioBitrate in seamless manualBitrateSwitchingMode

---

scripts/list-npm-scripts.js

This is an update of the "list" npm script, which brings two things to improve its usefulness:
- if less than 10 numbered inputs are possible, the script won't wait for the enter key to be entered for validating your choice.
- Listed commands are now choosable, and choosing one will execute it.
This is to allow new RxPlayer developpers to more easily familiarize themselves to the high number of scripts there are in the RxPlayer (to build, build a demo, build the doc, doing the various kinds of tests - unit, integration, memory & performance -, doing the various kinds of code checks - linting, typechecking -, doing some maintenance, updating the version, updating the served demo and documentation pages and so on...).
Here the idea is to just use a single script at the beginning, `npm run …

Update "list" npm script so it may actually execute commands

---

src/parsers/manifest/dash/wasm-parser/Cargo.lock
src/parsers/manifest/dash/wasm-parser/Cargo.toml
src/parsers/manifest/dash/wasm-parser/rs/errors.rs
src/parsers/manifest/dash/wasm-parser/rs/events.rs
src/parsers/manifest/dash/wasm-parser/rs/lib.rs
src/parsers/manifest/dash/wasm-parser/rs/processor/attributes.rs
src/parsers/manifest/dash/wasm-parser/rs/processor/mod.rs
src/parsers/manifest/dash/wasm-parser/rs/processor/s_element.rs
src/parsers/manifest/dash/wasm-parser/rs/reader.rs
src/parsers/manifest/dash/wasm-parser/rs/reportable.rs
src/parsers/manifest/dash/wasm-parser/rs/utils.rs

This commit updates the dependency in our Rust code, `quick-xml`, which allows to parse XML documents (which DASH MPD are) in our WASM MPD parser in a SAX-like manner.
The major change here is that the types for element names and attributes is now implemented by single-field structs whose field is the reference to the corresponding name whereas it was directly the reference initially.
Thankfully, there's no need to bring that new struct's name in all our pattern-matching cases (which would have been less readable), as calling the `as_ref` method implemented on that struct returns directly the reference we had before (we can thus pattern match on this instead, and keep the previous code for all matched patterns).
This is actually what is presented in quick-xml examples so it also seems …

DASH_WASM: Update quick-xml (Rust) dependency and consequently update Rust code

---

doc/api/Player_Errors.md
src/core/api/track_management/tracks_store.ts
src/core/fetchers/manifest/manifest_fetcher.ts
src/core/stream/period/period_stream.ts
src/core/stream/representation/utils/append_segment_to_buffer.ts
src/errors/media_error.ts
src/manifest/__tests__/manifest.test.ts
src/manifest/__tests__/period.test.ts
src/manifest/manifest.ts
src/manifest/period.ts
src/transports/dash/manifest_parser.ts
src/transports/local/pipelines.ts
src/transports/metaplaylist/pipelines.ts
src/transports/smooth/pipelines.ts
src/transports/types.ts

After doing many tests, it seems that the strategy of sending a `MANIFEST_INCOMPATIBLE_CODECS_ERROR` warning each time we spot an audio or video AdaptationSet with no supported codec in the MPD is not optimal for very large MPD (or equivalent in smooth streaming / local Manifests / MetaPlaylists).
Specifically, MPD with a very large amount of unsupported AdaptationSet (multi-Period MPDs, MPDs with a large choice of AdaptationSet with multiple codecs, dynamic range, audio channels, or all of this together), might produce A LOT of warnings - even more for contents where the Manifest has to be updated.
In turn, those warnings produce a lot of uninteresting warning logs, and might have in some extreme cases a non-null impact on memory as parsing issues were until known stored as a property of …

[Proposal] [v4] Errors: Replace trackInfo prop by tracksInfo to group similar errors

---

src/errors/__tests__/network_error.test.ts
src/errors/__tests__/request_error.test.ts
src/errors/request_error.ts

While debugging some issues, we noticed that our network-related error messages could do with more verbosity. This is what this PR does.
It also adds the HTTP status code in the message when this is the source, of the network error. Today it is only present as a `status` property.

Implement better messages for request errors

---

doc/Getting_Started/Migration_From_v3/loadVideo_Options.md
doc/api/Loading_a_Content.md
doc/reference/API_Reference.md
src/core/api/option_utils.ts
src/core/api/public_api.ts
src/public_types.ts
src/transports/types.ts

This PR un-documents the `manifestUpdateUrl` API, so it is effectively not part of the official API anymore, even if its behavior stays for now (renamed as `__priv_manifestUpdateUrl`).
The `manifestUpdateUrl` was an advanced DASH optimization where it was possible to update a dynamic MPD through a shorter version of it, thus much faster.
This was a clever solution for a real issue we had for a long time at Canal+, but it relied on complex and easy-to-break logic to perform updates.
Now, we prefer other solutions, which are either standard (e.g. DASH packaging techniques to reduce the size of the MPD) or purely based on code optimizations (WebAssembly-based parsers, advanced parsing modes) - thus not relying on special URL like it was with this.
As It is not needed at Canal+ anymore, it is …

[Proposal] "Remove" `manifestUpdateUrl` loadVideo option for the v4

---

src/utils/reference.ts

"Shared References" is an RxPlayer structure which allows to pass a value around and making receivers able to register a callback to listen and react for when that value changes, with added niceties like being able through type only to enforce that some code block is only able to read that value, not update it.
It is used a lot to implement RxPlayer API which can change the RxPlayer's behavior during playback such as `wantedBufferAhead`, `setPlaybackRate` but also for things like track switching. It was originally created when removing RxJS from the RxPlayer, and it is similar to RxJS' `BehaviorSubject` in some ways.
It turned out that we also needed some kind of mapping function for some edge cases where we want to communicate a value based on a Shared Reference. An example is the …

utils: Reference mapping finishes when source finishes

---

src/parsers/manifest/dash/common/parse_adaptation_sets.ts

The RxPlayer merge together multiple DASH AdaptationSet with similar characteristics and a two-ways `"adaptation-set-switching"` SupplementalProperty into a single track, as this is a trick often used by packagers to make a single "track" linked to several key ids compliant with the DASH-IF IOP while still allowing navigating between the two freely through adaptive bitrate mechanisms.
I noticed that, because of a forgotten `break;` call, we could have duplicate tracks if at least 3 AdaptationSet where "switchable" (with the duplicate being the last one encountered each time).
This is not a huge deal, as the video track has in any case less priority, and is still a playable track, but it was still unwanted.
This is now fixed.

DASH: Fix track duplication when merging more than one switchable AdaptationSet

---

src/compat/is_debug_mode_enabled.ts
src/index.ts
src/minimal.ts
src/typings/globals.d.ts

The RxPlayer has an hidden feature of setting automatically debug logs if a `__RX_PLAYER_DEBUG_MODE__` variable has been set to `true` in the globak scope. This allows to ease-up debugging work by preventing people to always having to manually set the log verbosity of the RxPlayer, and it is used by [RxPaired](https://github.com/peaBerberian/RxPaired), the RxPlayer-specialized remote debugger we routinely use and develop on.
Because in most scenarios, `__RX_PLAYER_DEBUG_MODE__` is not even defined as a global variable, just checking it that way will throw an error in JavaScript, so we have to be careful when relying on it: we HAVE TO rely on the `typeof` operator first, as it doesn't lead to an error if the variable given as argument does not exist.
However, TypeScript doesn't seem to …

Centralize debug mode handling

---

src/core/stream/representation/representation_stream.ts

The mechanism to check for new segment to request is done on several events but was not done on a Manifest update.
Even if for complex reasons, there are small advantages to not check for new segments directly after a Manifest update, it also seems in most cases more logical and efficient.
I decided to add it.

RepresentationStream: Also check segments after a Manifest update

---

src/core/stream/orchestrator/get_time_ranges_for_content.ts

When content become undecipherable the RxPlayer first tries to remove the corresponding data from the buffer. When it is not known when the corresponding undecipherable data is in the buffer (a normally rare occurence, but can theoretically happen), it previously removed everything that is currently known to be buffered.
This code now removes the whole buffer and doesn't limit itself at "what is known to be buffered" at that particular point in time:
- There may be unfinished push operations still going on (should be very rare) in which case the data may not be removed in the previous behavior.
- It simplifies things, especially with the still-on-draft WebWorker branch (#1272) which may lead to the buffered data not obtainable synchronously (when MSE run in main thread, as that code would …

Clean-up whole buffer in get_time_ranges_for_content.ts to be safe

---

src/core/segment_buffers/inventory/segment_inventory.ts

The RxPlayer maintains an inventory of which segments should be right now in browser buffers and at which position, through the `SegmentInventory` structure.
This is a complex part of the code which has to be frequently re-synchronized with the browser's buffer yet it allows a LOT of optimizations (preventing reloads when not needed, allowing to not re-load segments on seek, allowing fast-switching, allowing to implement in-JS buffer-memory limitations, allowing more efficient buffer-based adaptive algorithms, allowing to advertise the current played quality...).
I recently found out that `bufferedStart` - a mechanism to indicate the probable start time in seconds of a segment in the browser's buffer in that structure, was not set if the browser's buffer had a large time range of …

Add forgotten bufferedStart setting in SegmentInventory

---

src/core/init/utils/initial_seek_and_play.ts

The code implementing the initial seek (e.g. to play the initial position of a live content, or to implement the `startAt` option) and play (e.g. to implement `autoPlay`) could lead to an error in the for-now improbable (impossible?) scenario where the HTMLMediaElement already has at least the `HAVE_METADATA` `readyState` before that function is called, due to a callback using a variable before it was defined.
I don't know of any current issue that may be triggered by this, but some future work triggered it, so let's just fix that future issue.

Fix error in improbable case where content is already ready on load

---

src/core/init/media_source_content_initializer.ts
src/core/init/utils/create_stream_playback_observer.ts

When working on the WebWorker branch (#1272), I noticed a (small) memory leak where a created PlaybackObserver could still be running after a reload for the same content, whereas it should not.
This removes that leak by ensuring all logic is cleaned-up on each reload.
However, we do have memory-leak tests checking for leaks in that area and it didn't find anything, running the corresponding test before and after the commit is applied seems to result in roughly the same JS heap size. We may have to look if the test does not do what we want it to do or if the leak in question is very insignificant/does not apply in our current code.

Fix theoretical memory leak on reload in stream PlaybackObserver creation code

---

src/core/init/media_source_content_initializer.ts
src/core/init/utils/stream_events_emitter/refresh_scheduled_events_list.ts
src/core/init/utils/stream_events_emitter/stream_events_emitter.ts

The `StreamEventsEmitter` is the RxPlayer module storing events found in the Manifest (for now only DASH' `EventStream` elements) and emitting `streamEvent`/`streamEventSkip` RxPlayer events when they are encountered.
In the WebWorker work (#1272), I had to refacto the `StreamEventsEmitter` from being a long-lived function to being a class, to make it possible to be communicated manifest updates less awkwardly and more idiomatically, through an `onManifestUpdate` method.
However, I liked the result and find it much more easy to understand than the previous one, which bears the mark of having been previously an RxJS-based logic. The new has some more lines, but it just seems much more idiomatic and easy-to-understand with a regular event-emitter-based logic, than with callbacks parameters. …

StreamEventsEmitter is now a class

---

src/core/decrypt/__tests__/__global__/media_key_system_access.test.ts
src/core/decrypt/__tests__/__global__/media_keys.test.ts
src/errors/__tests__/encrypted_media_error.test.ts
src/errors/__tests__/error_message.test.ts
src/errors/__tests__/format_error.test.ts
src/errors/__tests__/media_error.test.ts
src/errors/__tests__/network_error.test.ts
src/errors/__tests__/other_error.test.ts
src/errors/custom_loader_error.ts
src/errors/encrypted_media_error.ts
src/errors/error_message.ts
src/errors/media_error.ts
src/errors/network_error.ts
src/errors/other_error.ts
src/manifest/__tests__/update_periods.test.ts
src/parsers/manifest/utils/__tests__/update_segment_timeline.test.ts
src/transports/utils/__tests__/check_isobmff_integrity.test.ts

Until now, the RxPlayer's errors set the Error's `name` property inside its `message` property.
When logged in the console, such errors are automatically formatted by the browser which generally choose to re-use the `name` to produce a meaningful error string.
This lead to a repeat like:
`EncryptedMediaError: EncryptedMediaError (INCOMPATIBLE_KEYSYSTEMS) Some description message`
This was unnecessary and kind of ugly but we were afraid some apps were for whatever reasons exploiting the `message` string and thus did not change it in the v3.
For the `v4` we choose a more consize message: The code, followed by a colon, followed by a description of what happened. As such, the previous example would look like in a JS console when logged:
`EncryptedMediaError: INCOMPATIBLE_KEYSYSTEMS: Some …

Implement better error message for the v4

---

src/compat/event_listeners.ts
src/core/adaptive/__tests__/buffer_based_chooser.test.ts
src/core/adaptive/adaptive_representation_selector.ts
src/core/adaptive/buffer_based_chooser.ts
src/core/adaptive/network_analyzer.ts
src/core/api/track_management/track_dispatcher.ts

We noticed a strange issue on some older Edge browser versions (like the one used on some XBox or some other UWP applications) where the ABR (Adaptive BitRate, the code in charge of choosing the right audio and video quality) would make poor quality choices, even when the user had a high bandwidth, only in the future v4 version.
It turned out that the issue wasn't directly linked to ABR, but due to some other assumptions wrongly assumed by the RxPlayer (only in the future v4) which broke behavior only on older Edge browsers.
Basically:
- The adaptive code assumed that all quality given to it were sorted from the lowest to the highest bitrate, as is almost convention in the RxPlayer code. Some of its algorithms were dependents on that assumption.
- Although most of the code handling …

Fix ABR on old Edge browser

---

src/experimental/features/__tests__/index.test.ts
src/experimental/features/index.ts
src/features/list/__tests__/index.test.ts

We noticed that we unfortunately forgot to export the `LOCAL_MANIFEST` feature in the last `v3.32.0` release.
It is still theoretically possible to depend on it by importing the corresponding file buried in the `dist` directory, but it is not at all the intended API-documented way, so this is definitely bug.
Thankfully this is not the most relied on feature but still, some applications at Canal+ depend on it (and reported this issue to us).

Fix LOCAL_MANIFEST feature import

---

src/transports/smooth/segment_loader.ts

Thanks to a test rewrite linked to #1291, I noticed that the v4 broke the possibility of relying on a `segmentLoader` when relying on smooth streaming, due to forgetting to update some property name in a refactoring of the transport code.
This commit/branch fixes just that.

Fix usage of an external segmentLoader when playing smooth streaming contents

---

demo/full/scripts/controllers/ProgressBar.tsx

Fix a bug in the demo of the Rx-Player : 
Playing a live content in the demo resulted in wrong values in the progress bar.
The content was unexpectedly interpreted as non-live content, because `isLive` was not tracked as a dependency in the react callback.

fix(demo): live content had wrong values on the progress bar

---

src/parsers/manifest/dash/common/__tests__/flatten_overlapping_period.test.ts
src/parsers/manifest/dash/common/flatten_overlapping_periods.ts

Some streaming technologies/protocols such as DASH have a concept of `Period`, which is a temporal subpart of the content with its own tracks, qualities and other characteristics. You can think of it for example as various programs in a contents, some having multiple audio languages and subtitles, other not.
In the RxPlayer, Period are meant to be non-overlapping, to always rely on a single known list of available tracks (for audio, video and text) and available qualities at any given position.
This means that you may have a Period from the position `10` (let's say seconds) to `20`, then from `20` to `30`, but never something like from position `10` to `25` then from `20` to `30`, as the `20-25` interval would be ambiguous regarding its available tracks and qualities: the two Periods are …

DASH: Fix Period overlap resolution logic for when the first Period is removed

---

doc/api/Basic_Methods/reload.md
src/core/api/option_utils.ts
src/core/api/public_api.ts

A majority of the bigger issues we encounter in production is DRM-related, leading us to either work-around those in the RxPlayer, or to facilitate a work-around on the application-side through a better DRM-related API.
Recently, we've seen that many Windows/Edge users (but still a minority of them) could encounter an issue on the `generateRequest` EME call when relying on PlayReady SL3000 (hardware-backed decryption and playback, seen as one the most secure DRM mechanism for OTT contents) which would lead to a failure to play the content.
When this happens, fallbacking to a different key system like PlayReady SL2000 (where decryption happens in software) or Widevine usually (though not always) seems to avoid the issue, even if it might lead to less protection and thus might lead …

Add the possibility to set a new `keySystems` option on the `reload` API

---

src/core/segment_buffers/implementations/text/html/__tests__/utils.test.ts
src/core/segment_buffers/implementations/text/html/text_track_cues_store.ts
src/core/segment_buffers/implementations/text/html/utils.ts

When playing a video in low-latency mode with subtitle, the subtitle were disappearing and reappear very quickly making the subtitles "blink".
This was only experienced in low-latency mode.
--------
It was due to the size of the subtitles segments that differs in normal mode vs low-latency: 
- Normal mode: around 2 seconds
- Low latency: around 2 seconds with chunks of 40 milliseconds
When sorting segments in the buffer, there is a logic that compare which segments should come first, and it determines if there are segments that are the "same" or if they overlap.
The logic that compute if two segments are the "same" were relying on a constant `MAX_DELTA_BUFFER_TIME` equals to 200ms.
200ms of tolerance is fine for segments that lasts 2s, but for segments of 40ms in low-latency it's way too …

fix bug: subtitle no longer blink in low latency

---

src/core/api/public_api.ts

We have a minor issue with an undocumented API letting applications know the content of the various buffers (audio, video and text), which may show in some rare cases to an unsynchronized view into one of those buffers.
As this API is not documented and put behind an unwelcoming method name, the only impact that unsynchronized status could have are:
- information shown in the RxPlayer's debug element (through the `createDebugElement API`) could not reflect the exact reality.
The only case I've seen now is that when enabling then disabling text tracks, we may still see a view making it seems that the since-remove text segments pushed were still here (it is in reality not, as should be expected).
- Likewise, our demo page's buffer graph, which rely on the same API, could show an …

Debug: always synchronize SegmentInventory before reporting it through the API

---

demo/full/scripts/controllers/Player.tsx
demo/full/scripts/controllers/charts/index.tsx
demo/full/scripts/modules/player/index.ts
demo/full/styles/style.css

The `createDebugElement` method allows to generate an RxPlayer-made debug element.
It is used most often as a stats-for-nerds-like kind of things to quickly inspect, debug and report issues by displaying some interesting playback stats without having to dive into debug logs to obtain them.
We didn't yet had a possibility to show them in the demo, so this commit quickly does that. It does it in the laziest way possible, by just adding a "Display debug element" checkbox in the chart area of the demo, which will display debug information on top of the media element when enabled and playing content.
_Debug element shown on top of the video element, with the corresponding checkbox enabled (at the bottom of the screenshot)_
It may have more its place in the controls (which is what e.g. YouTube …

Demo/v4: Add possibility to see the debug element in the demo page

---

src/core/api/debug/buffer_graph.ts

When displaying the RxPlayer's debug element, a graph describing the audio, video and text qualities in the various buffers might be displayed.
At maximum, that graph could display 10000 seconds of content, which made in that case the graph poorly readable.
I now chose to reduce it to maximum 30 minutes, as you rarely intend to see more when displaying debug information, making it much more readable.

Debug: update buffer graph maximum size so it becomes more readable for lengthy contents

---

doc/api/Miscellaneous/Debug_Element.md
src/core/api/debug/modules/general_info.ts
src/public_types.ts

The debug element that might be displayed with the `createDebugElement` method filtered from listed video and audio bitrates those that were not for decipherable or decodable Representation.
This makes sense, but it bothered us when debugging why some qualities were not advertised anymore through that window on some difficult-to-debug devices lately: was it an RxPlayer bug, a DRM policy not respected, or codecs that were unsupported.
This commit adds audio and video bitrates which are not actually playable, suffixing them by `E!` when it is because it's not decipherable, by `U!` when it's because the codec is not supported, or both (`U! E!`) when it's both.

Add unsupported and undecipherable bitrates to the debug element

---

demo/full/scripts/controllers/Player.tsx

Changing the video/audio switching mode in the demo was not taken into account when you update it more than 1 time:
- Load a video
- Set Default Audio Representations switching mode to "direct"
- Reload the video
- Set Default Audio Representations switching mode to "lazy"  --> The switching mode will be stuck on "direct"

fix a bug in the demo: changing video/audio switching mode had no effect

---

src/core/segment_buffers/implementations/audio_video/audio_video_segment_buffer.ts
src/core/segment_buffers/implementations/image/image_segment_buffer.ts
src/core/segment_buffers/implementations/text/html/html_text_segment_buffer.ts
src/core/segment_buffers/implementations/text/native/native_text_segment_buffer.ts
src/core/segment_buffers/index.ts
src/core/segment_buffers/inventory/index.ts
src/core/segment_buffers/inventory/segment_inventory.ts
src/core/stream/representation/utils/get_buffer_status.ts

This PR fixes a kind of rare issue that is tricky to reproduce that may happen after a `QuotaExceededError` is encountered when pushing a chunk to the audio and video `SourceBuffer` due to memory limitations.
In that situation, we could be left in the following scenario:
1. We're loading a chunk and pushing it to the `SourceBuffer`
2. The `SourceBuffer` throws a `QuotaExceededError`, generally this means that the device needs more memory to add that chunk
3. The SegmentBuffer code still adds the chunk to its `SegmentInventory` (as it may still have been partially pushed to the SourceBuffer, we're not 100% sure of what happened on the lower-level code) and to that `SegmentInventory`'s `BufferedHistory`.
4. The stream code catches the error, try to remove some buffered data and retry to …

Do not add failed push operations in the BufferedHistory

---

src/core/decrypt/get_media_keys.ts

The `throw new EncryptedMediaError` was never reached as the condition before
`isNullOrUndefined(keySystemOptions.persistentLicenseConfig)` was already catching the case where `persistentLicenseConfig` is `undefined`.

refactor: code in create persistent session was unreachable

---

src/core/adaptive/adaptive_representation_selector.ts
src/core/adaptive/network_analyzer.ts
src/core/api/index.ts
src/core/api/playback_observer.ts
src/core/api/public_api.ts
src/core/api/utils.ts
src/core/init/directfile_content_initializer.ts
src/core/init/media_source_content_initializer.ts
src/core/init/utils/content_time_boundaries_observer.ts
src/core/init/utils/create_stream_playback_observer.ts
src/core/init/utils/initial_seek_and_play.ts
src/core/init/utils/rebuffering_controller.ts
src/core/init/utils/stream_events_emitter/stream_events_emitter.ts
src/core/segment_buffers/garbage_collector.ts
src/core/stream/adaptation/get_representations_switch_strategy.ts
src/core/stream/orchestrator/stream_orchestrator.ts
src/core/stream/period/period_stream.ts
src/core/stream/period/types.ts
src/core/stream/period/utils/get_adaptation_switch_strategy.ts
src/core/stream/representation/representation_stream.ts
src/core/stream/representation/types.ts
src/core/stream/representation/utils/append_segment_to_buffer.ts
src/core/stream/representation/utils/get_buffer_status.ts
src/default_config.ts
tests/contents/DASH_static_SegmentTimeline/media/discontinuity.mpd
tests/integration/scenarios/dash_live.js
tests/integration/utils/launch_tests_for_content.js

Tizen devices (mainly samsung TVs) are the only devices on which seek operations is not precize.
On those devices for example, you might want to seek at a given position, let's say `51` seconds, and tizen could actually after media segments are loaded decide to finally play at an earlier position instead, let's say `50` seconds.
The choice actually made by tizen seems to correspond to the closest IDR video frame instead of what the RxPlayer wants, we guess because of performance reasons.
This caused many problems in the RxPlayer as we generally want to seek at a very specific position for very valid reasons, for example it could be because we need the position to be within a specific Period's boundaries or because we need to make sure the current position is after a known audio …

Refacto current position handling again just to work-around tizen mischievous seek-backs

---

doc/Getting_Started/Migration_From_v3/loadVideo_Options.md
doc/api/Loading_a_Content.md
doc/api/Miscellaneous/plugins.md
src/manifest/adaptation.ts
src/public_types.ts

When porting supplementalCodec support (allowing today to better support retro-compatible Dolby Vision codecs when playing DASH contents, planned for the incoming v3.33.0) to the `MULTI_THREAD` branch (#1272, allowing to run the RxPlayer in a WebWorker optionally, even using MSE-in-worker API when available, to improve performance and ABR stability - this is a huge work we're pretty confident will be released, surely in a `v4.1.0` so still not for today), we found out that the feature was incompatible with that branch because of a subtle reason.
Basically, the supplementalCodec work on v3.x.x branches only expose as a codec the codec that will actually be used on the device (e.g. the Dolby Vision codec on compatible devices, or the retro-compatible more supported codec on others). The …

Rename codec to codecs in the representationFilter for the v4

---

src/core/stream/orchestrator/stream_orchestrator.ts
src/default_config.ts

The `maxBufferAhead` RxPlayer option allows to manually garbage collect media data that is too far ahead from the playing position.
It can be set to a number of seconds, and was previously applied to audio, video and text media segments.
For example when setting `maxBufferAhead` to `30`, and playing at position `20`, we would remove if present media data already buffered a position `50` or more (which could for example mostly happen when seeking back in the content).
We found out however that applying that same value to the text buffer may not always be sensible:
- `maxBufferAhead` is most likely defined by an application to restrict memory usage. The space taken by the text cues have much less weight than audio and video
- We encounter several contents where loaded text segments span for …

Add maxBufferAhead exception for text garbage collection

---

demo/full/scripts/contents.ts

Change the URL that was no longer working

chore: replace demo manifest that is no longer available

---

src/core/init/utils/initial_seek_and_play.ts

Seeking to the last frame of the video result in restarting the video from the beginning. This is because VideoElement.play() method restart the play from beginning if video is ended.
According to the spec:
> If the playback has ended and the direction of playback is forwards,
> seek to the earliest possible position of the media resource.
In this case checking if the video is ended and not call play() fixes the issue.

fix: seeking to the last frame restart the video

---

src/core/stream/orchestrator/stream_orchestrator.ts
src/core/stream/representation/utils/get_buffer_status.ts
src/manifest/manifest.ts
src/manifest/period.ts

We found out that an issue prevented from switching the track when the current position was exactly at the position indicated by a Period's `end` property if there was no immediately consecutive Period.
For example if a content had, as a last Period, one starting at position `10` (seconds) and ending at `30`, and if the player was currently paused at position `30` a `setAudioTrack` or any track switching call wouldn't have any effect.
This is because the logic handling which Period should currently be handled decides that a Period finishes as soon as we reached the position indicated by its `end` property. Because under that logic we're not playing the last Period anymore when we reached it, API updating tracks of the current Period do not have any effect.
It actually makes perfect sense …

Fix issue arising when using track APIs at the exact last possible position of a Period with no consecutive Period

---

src/experimental/tools/mediaCapabilitiesProber/index.ts

Some applicant might need type `ICompatibleKeySystem` and was therefore imported through 
`import { ICompatibleKeySystem } from 'rx-player/dist/es2017/experimental/tools/mediaCapabilitiesProber/types';`
This was not very robust has a change in the ES target changed the import path.
Exporting it will allow to import in a stabler way.
`import { mediaCapabilitiesProber } from 'rx-player/experimental/tools';`

types: export type IcompatibleKeySystem to the public API

---

src/core/api/public_api.ts
src/core/segment_buffers/implementations/types.ts
src/core/segment_buffers/inventory/segment_inventory.ts

The `synchronizeInventory` method is an internal method of the RxPlayer allowing to synchronize our internal representation of media buffers (representing which segments are buffered where) with the anounced buffered TimeRanges of the media buffer as indicated by the web browser, which should be more up-to-date (e.g. take into consideration garbage collection).
As this internal representation of the buffer is very valuable when debugging, the `synchronizeInventory` produce logs each time it is called.
Yet that method is very often called when the debug element (under the `DEBUG_ELEMENT` feature) to be sure it is mostly up-to-date with the browser's buffer as the debug element is only shown in debugging contexts.
Calling that method in this context of visual debugging here has consequently …

Add ugly `skipLog` parameter to the synchronizeInventory method

---

src/core/api/track_management/track_dispatcher.ts
src/core/init/multithread/worker/track_choice_setter.ts
src/core/stream/adaptation/types.ts

During our work on making the RxPlayer use a WebWorker for most of its core logic, we encountered some issues that made declaring types (through TypeScript) more difficult.
One of the main issue was with the object emitting Representations (a.k.a. qualities) choices.
That object makes heavy use of TypeScript variance rules to enforce some type of read/write permissions on variables. This requires various TypeScript tricks (yet still sound).
When I made the initial worker code, I didn't think too much about that part, so I chose the easy way: to just remove that type-level permission checking where it bothered me.
This PR now brings back that security.

Better type Representation choice code in multithread mode

---

demo/full/tsconfig.json

using global import, ex: `__ENVIRONMENT__` in the `demo/full` folder didn't work because there is a `demo/full/tsconfig` file that has more priority than `src/tsconfig` in the `demo/full` folder. The fix was to add the global import file in the `demo/full/tsconfig`

fix(demo): fix ts error in global declaration

---

demo/full/scripts/components/Options/VideoAdaptiveSettings.tsx
demo/full/scripts/controllers/Settings.tsx
demo/full/scripts/lib/defaultOptionsValues.ts

Property `limitVideoWidth` has been removed in the API for v4.0.0 but the changes was not reflected in the demo.
This PR change this obsolete property by the new `videoResolutionLimit` in the demo.

demo: change removed property limitVideoWidth to videoResolutionLimit

---

demo/full/scripts/controllers/VolumeBar.tsx
demo/full/scripts/controllers/VolumeButton.tsx
demo/full/scripts/modules/player/events.ts
demo/full/scripts/modules/player/index.ts
doc/Getting_Started/Migration_From_v3/Player_Events.md
doc/Getting_Started/Migration_From_v3/Player_Methods.md
doc/api/Player_Events.md
doc/api/Volume_Control/mute.md
doc/api/Volume_Control/unMute.md
src/core/api/__tests__/public_api.test.ts
src/core/api/public_api.ts
src/default_config.ts
tests/integration/scenarios/idle.js
tests/integration/utils/launch_tests_for_content.js

Previous RxPlayer's `mute` and `unMute` method actually set the volume to `0` instead of changing the `muted` HTMLMediaElement property.
I here propose that we update their behavior to mutate the `muted` property instead as:
1. It would seem more natural to an application I would guess
2. It might integrate better with browsers built-in making use of the `HTMLMediaElement` properties directly (things like Picture-in-Picture and so on).
I also consequently updated that the `volumeChange` event to notify about both properties, and noticed it wasn't even documented in the API documentation.

Set more standard mute/unMute behaviors

---

src/compat/browser_detection.ts
src/compat/should_prevent_seeking_at_0_initially.ts
src/core/init/utils/initial_seek_and_play.ts

We noticed that on Xbox game consoles, the browser didn't send a `"seeking"` event if we were seeking at a `0` position initially.
We could theoretically never seek at `0` initially as the initial position of an `HTMLMediaElement` should be at `0` anyway, but we still do it as a safe solution, as many devices have a buggy integration of HTML5 media API.
So here we just avoid doing so for xbox

[WIP] Hotfix xbox seek initial

---

src/compat/browser_detection.ts

safari v.17 (macOS v.14) introduce a new feature to save any webpage as a web app. The app is added to the dock and can be used independently from safari. Hower this app still use safari engine under the hood. It appears that when using safari in a webapp property "window.safari" is undefined.
As the detection of safari browser rely on this property, the browser is mistakenly considered as non safari.
The goal of this change is to rely on userAgent that may be more reliable.
https://support.apple.com/en-us/104996
https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent#which_part_of_the_user_agent_contains_the_information_you_are_looking_for

fix: detect safari when launching from dock

---

src/core/api/playback_observer.ts
src/core/init/multithread/worker/content_preparer.ts
src/core/init/multithread/worker/track_choice_setter.ts
src/utils/__tests__/object_assign.test.ts
src/utils/object_assign.ts

Out of the box type definition of `Object.assign` is confusing and wrong: 
```ts
const myObj = { a: "a"};
let merged = Object.assign({a: "a"}, {a: 1})
typeof merged.a // "never"       but it should be "number" !
```
Return type of `object.assign(a: U, b: T)`  is  intersection `U & T`.
However intersecting two object that share some property but with different types will result in no overlapping and it's then typed as `never`.
```ts
type A = { a: string };
type B = { a : number };
type C = A & B 
// ^? { a : never }
```
https://www.typescriptlang.org/play?#code/C4TwDgpgBA8gRgKwgY2AQQM4YJYHMB2UAvFKJAPYBmsiKwAdAIZZ74DcAUB8ufhsFAC2IeAmJQA3lEYAuKACJG8gL6cOAGwgDBEAE64IAE3Gi6TFgQAUE5QBpJshUrsO5ARmUBKLmQhUhegaGTFAA9KFQ+BAAbnoAhFBwAK4C2AIYABbkSerGcNDy+EmC+bryQA
The solution is to change the return …

types: improve object assign type def

---

doc/api/Creating_a_Player.md

API Documentation warn 2 times that the maxvideoBufferSize options has no effect when in DirectFile mode.
(and the second statement use the term "method" which is not exact as it should be "option" or "property")
So I propose to keep the first warn statement only.
> This option will have no effect for contents loaded in Directfile mode (see [loadVideo options](https://developers.canal-plus.com/rx-player/versions/4.0.0-beta.3/doc//api/Loading_a_Content.html#transport)).
> In DirectFile mode (see [loadVideo options](https://developers.canal-plus.com/rx-player/versions/4.0.0-beta.3/doc//api/Loading_a_Content.html#transport)), this method has no effect.`

doc: remove duplicate warning for maxvideoBufferSize

---

src/manifest/classes/manifest.ts

While doing some testing on `<UTCTiming>` elements in a DASH MPD, it has been brought to us that if all attempts to load its linked URL failed for the initial fetch of the Manifest (in which case we fallback to a mode where we don't rely on that element) and if the Manifest has to be refreshed multiple times, then the URL will be accessed every time the Manifest is refreshed, even if just one sucessful attempt would have been enough.
The issue was very simple to fix, as it was just that a newly obtained `clockOffset` - the actual metadata derived from parsing an `<UTCTiming>` element, was not actually copied when updating the base Manifest by its new parsed version.
Once that `clockOffset` is set to the base Manifest, that information will be communicated to our Manifest parser when the …

Don't re-load a Manifest's optional external resource each time if initial failed

---

src/main_thread/decrypt/__tests__/__global__/get_license.test.ts
src/utils/__tests__/retry_promise_with_backoff.test.ts
src/utils/retry_promise_with_backoff.ts

Asserting after a `setTimeout()` is not highly reliable since device performance variations can lead to inconsistent outcomes.  That was highly noticeable on the CI where failures occurred frequently..
To address this issue, we ensure that the license has been received before performing the assertion.
Replace a `setTimeout` by the use of `setInterval` to periodically check the if the license has been received.
I was wondering if the condition is never met, will we infinitely get stuck in the setInterval ? But the test runner has his own timeout for every test case, so it does not feel necessary to add one in the code.

fix(test): fix flaky test get_license

---

.github/workflows/checks.yml
.gitignore
package.json
scripts/build_wasm_release.sh
scripts/install_rust_toolchain.sh

Since we brought the WebAssembly MPD parser to fix performance issues we had with some contents at canal+, we added another language (Rust) to the project which is not compatible with most of the JS-world tools we and other JS developers usually deal with.
Now that we added the `MULTI_THREAD` experimental feature and embeds, the WebAssembly generation from that other language is even a required step in our main build script (`npm run build`).
Consequently, when another developer or a CI needs to build an RxPlayer (e.g. to test a development before a release is made), they have to install:
1. NodeJS + npm
2. our JavaScript dependencies
3. A Rust toolchain able to output WebAssembly. We generally go through `rustup` here basically an helper tool to install Rust toolchains
4. `binaryen`, …

Auto-install Rust compiler toolchain locally for CI and JS devs of other projects
